package sheenrox82.RioV.src.util;

import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityEggInfo;
import net.minecraft.entity.EntityList;
import net.minecraft.item.Item;
import net.minecraft.util.DamageSource;
import net.minecraft.util.EntityDamageSourceIndirect;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.DimensionManager;
import net.minecraftforge.common.MinecraftForge;
import sheenrox82.RioV.src.base.Config;
import sheenrox82.RioV.src.base.Crafting;
import sheenrox82.RioV.src.base.TheMistsOfRioV;
import sheenrox82.RioV.src.content.Biomes;
import sheenrox82.RioV.src.content.Blocks;
import sheenrox82.RioV.src.content.Enchantments;
import sheenrox82.RioV.src.content.EntityLoader;
import sheenrox82.RioV.src.content.Items;
import sheenrox82.RioV.src.entity.projectile.EntityCustomArrow;
import sheenrox82.RioV.src.event.BonemealEvent;
import sheenrox82.RioV.src.event.EntityDropEvent;
import sheenrox82.RioV.src.handler.ConnectionHandler;
import sheenrox82.RioV.src.handler.FuelHandler;
import sheenrox82.RioV.src.handler.HudHandler;
import sheenrox82.RioV.src.handler.SoundHandler;
import sheenrox82.RioV.src.tileentity.TileEntityBloodChest;
import sheenrox82.RioV.src.tileentity.TileEntityCherryBlossomChest;
import sheenrox82.RioV.src.tileentity.TileEntityDarkener;
import sheenrox82.RioV.src.tileentity.TileEntityGlimmerwoodChest;
import sheenrox82.RioV.src.tileentity.TileEntityInfuser;
import sheenrox82.RioV.src.tileentity.TileEntitySkywoodChest;
import sheenrox82.RioV.src.world.WorldGenOverworld;
import sheenrox82.RioV.src.world.provider.WorldProviderBlindOasis;
import sheenrox82.RioV.src.world.provider.WorldProviderFlamonor;
import sheenrox82.RioV.src.world.provider.WorldProviderSanctuatite;
import sheenrox82.RioV.src.world.provider.WorldProviderVaeryn;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class Registry 
{
	public static double rand;
	public static int id = 500;

	public static void preInit(FMLPreInitializationEvent initEvent)
	{		
		TheMistsOfRioV.commonProxy.init();
		TheMistsOfRioV.commonProxy.cape();
		ModMetadata data = initEvent.getModMetadata();
		data.autogenerated = false;
		data.modId = Util.MOD_ID;
		data.name = Util.MOD_NAME;
		data.logoFile = "/assets/riov/textures/misc/RioV.png";
		data.version = (Util.VERSION);
		data.url = "http://www.minecraftforum.net/user/630621-sheenrox82/";
		data.authorList = Arrays.asList(new String[] {"sheenrox82"});
		data.description = Util.MOD_NAME + " - The imagined world is called RioV, " +
				"in the year of 1301 DoC (Death of Carigon.), the land of RioV is " +
				"filled with Nizonians. A native creature that are basically giant beasts. " +
				"In 1278 DoC the Natives found a new threat across the land called humans, " +
				"another wild creature. Since then, the races have been weakened and new races have " +
				"arrived, such as the dark elves. There is a myth that in 1610 a monster called a " +
				"Soverian Overlord will destroy the land of RioV and leave it in ashes. " +
				"This is The Mists of RioV.";
		Config.initialize(initEvent);
		MinecraftForge.EVENT_BUS.register(new EntityDropEvent());
		MinecraftForge.EVENT_BUS.register(new BonemealEvent());
		MinecraftForge.EVENT_BUS.register(new HudHandler());
		MinecraftForge.EVENT_BUS.register(new SoundHandler());
		Items.add();
		Blocks.add();
		Crafting.add();
		Biomes.add();
		Enchantments.add();

		//0's
		MinecraftForge.setBlockHarvestLevel(Blocks.darkeningAltar, "pickaxe", 0);
		MinecraftForge.setBlockHarvestLevel(Blocks.infuser, "axe", 0);
		MinecraftForge.setBlockHarvestLevel(Blocks.darkeningAltar, "axe", 0);
		MinecraftForge.setBlockHarvestLevel(Blocks.infuser, "pickaxe", 0);
		//0's

		//1's
		MinecraftForge.setToolClass(Items.skywoodPickaxe, "pickaxe", 1);
		MinecraftForge.setToolClass(Items.skywoodAxe, "axe", 1);
		MinecraftForge.setToolClass(Items.skywoodShovel, "shovel", 1);
		MinecraftForge.setBlockHarvestLevel(Blocks.slate, "pickaxe", 1);
		MinecraftForge.setBlockHarvestLevel(Blocks.sanctuaryStone, "pickaxe", 1);
		MinecraftForge.setBlockHarvestLevel(Blocks.flamonorRock, "pickaxe", 1);
		MinecraftForge.setBlockHarvestLevel(Blocks.amethystOre, "pickaxe", 1);
		//1's

		//2's
		MinecraftForge.setToolClass(Items.glimmerwoodPickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.glimmerwoodAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.glimmerwoodShovel, "shovel", 2);
		MinecraftForge.setToolClass(Items.cherryBlossomPickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.cherryBlossomAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.cherryBlossomShovel, "shovel", 2);
		MinecraftForge.setToolClass(Items.bloodPickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.bloodAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.bloodShovel, "shovel", 2);
		MinecraftForge.setToolClass(Items.sanctuaryStonePickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.sanctuaryStoneAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.sanctuaryStoneShovel, "shovel", 2);
		MinecraftForge.setToolClass(Items.topazPickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.topazAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.topazShovel, "shovel", 2);
		MinecraftForge.setToolClass(Items.sapphirePickaxe, "pickaxe", 2);
		MinecraftForge.setToolClass(Items.sapphireAxe, "axe", 2);
		MinecraftForge.setToolClass(Items.sapphireShovel, "shovel", 2);
		MinecraftForge.setBlockHarvestLevel(Blocks.sapphireOre, "pickaxe", 2);
		MinecraftForge.setBlockHarvestLevel(Blocks.topazOre, "pickaxe", 2);
		MinecraftForge.setBlockHarvestLevel(Blocks.onyxOre, "pickaxe", 2);
		//2's

		//3's
		MinecraftForge.setToolClass(Items.infusedTopazPickaxe, "pickaxe", 3);
		MinecraftForge.setToolClass(Items.infusedTopazAxe, "axe", 3);
		MinecraftForge.setToolClass(Items.infusedTopazShovel, "shovel", 3);
		MinecraftForge.setToolClass(Items.amethystPickaxe, "pickaxe", 3);
		MinecraftForge.setToolClass(Items.amethystAxe, "axe", 3);
		MinecraftForge.setToolClass(Items.amethystShovel, "shovel", 3);
		MinecraftForge.setToolClass(Items.onyxPickaxe, "pickaxe", 3);
		MinecraftForge.setToolClass(Items.onyxAxe, "axe", 3);
		MinecraftForge.setToolClass(Items.onyxShovel, "shovel", 3);
		MinecraftForge.setToolClass(Items.infusedAmethystPickaxe, "pickaxe", 3);
		MinecraftForge.setToolClass(Items.infusedAmethystAxe, "axe", 3);
		MinecraftForge.setToolClass(Items.infusedAmethystShovel, "shovel", 3);
		MinecraftForge.setBlockHarvestLevel(Blocks.garnetOre, "pickaxe", 3);
		MinecraftForge.setBlockHarvestLevel(Blocks.bloodRock, "pickaxe", 3);
		MinecraftForge.setBlockHarvestLevel(Blocks.blackRock, "pickaxe", 3);
		//3's

		//4's
		MinecraftForge.setToolClass(Items.infusedSapphirePickaxe, "pickaxe", 4);
		MinecraftForge.setToolClass(Items.infusedSapphireAxe, "axe", 4);
		MinecraftForge.setToolClass(Items.infusedSapphireShovel, "shovel", 4);
		MinecraftForge.setToolClass(Items.infusedOnyxPickaxe, "pickaxe", 4);
		MinecraftForge.setToolClass(Items.infusedOnyxAxe, "axe", 4);
		MinecraftForge.setToolClass(Items.infusedOnyxShovel, "shovel", 4);
		MinecraftForge.setToolClass(Items.blindonitePickaxe, "pickaxe", 4);
		MinecraftForge.setToolClass(Items.blindoniteAxe, "axe", 4);
		MinecraftForge.setToolClass(Items.blindoniteShovel, "shovel", 4);
		MinecraftForge.setBlockHarvestLevel(Blocks.blindoniteOre, "pickaxe", 4);
		//4's

		//5's
		MinecraftForge.setToolClass(Items.infusedBlindonitePickaxe, "pickaxe", 5);
		MinecraftForge.setToolClass(Items.infusedBlindoniteAxe, "axe", 5);
		MinecraftForge.setToolClass(Items.infusedBlindoniteShovel, "shovel", 5);
		//5's

		//8's
		MinecraftForge.setToolClass(Items.agonitePickaxe, "pickaxe", 8);
		MinecraftForge.setBlockHarvestLevel(Blocks.nironiteOre, "pickaxe", 8);
		MinecraftForge.setBlockHarvestLevel(Blocks.dragonOre, "pickaxe", 8);
		MinecraftForge.setBlockHarvestLevel(Blocks.vraviniteOre, "pickaxe", 8);
		//8's

		//9's
		MinecraftForge.setToolClass(Items.dragonPickaxe, "pickaxe", 9);
		MinecraftForge.setToolClass(Items.dragonAxe, "axe", 9);
		MinecraftForge.setToolClass(Items.dragonShovel, "shovel", 9);
		//9's

		//11's
		MinecraftForge.setToolClass(Items.infusedDragonPickaxe, "pickaxe", 11);
		MinecraftForge.setToolClass(Items.infusedDragonAxe, "axe", 11);
		MinecraftForge.setToolClass(Items.infusedDragonShovel, "shovel", 11);
		//11's

		//12's
		MinecraftForge.setToolClass(Items.vravinitePickaxe, "pickaxe", 12);
		MinecraftForge.setToolClass(Items.vraviniteAxe, "axe", 12);
		MinecraftForge.setToolClass(Items.vraviniteShovel, "shovel", 12);
		//12's

		//13's
		MinecraftForge.setToolClass(Items.infusedVravinitePickaxe, "pickaxe", 13);
		MinecraftForge.setToolClass(Items.infusedVraviniteAxe, "axe", 13);
		MinecraftForge.setToolClass(Items.infusedVraviniteShovel, "shovel", 13);
		MinecraftForge.setBlockHarvestLevel(Blocks.drakiuzOre, "pickaxe", 13);
		MinecraftForge.setBlockHarvestLevel(Blocks.jaavikOre, "pickaxe", 13);
		//13's

		//14's
		MinecraftForge.setToolClass(Items.alerisPickaxe, "pickaxe", 14);
		MinecraftForge.setToolClass(Items.alerisAxe, "axe", 14);
		MinecraftForge.setToolClass(Items.alerisShovel, "shovel", 14);
		MinecraftForge.setBlockHarvestLevel(Blocks.alerisOre, "pickaxe", 13);
		//14's

		GameRegistry.registerFuelHandler(new FuelHandler());
		GameRegistry.registerTileEntity(TileEntityInfuser.class, "Infuser");
		GameRegistry.registerTileEntity(TileEntityDarkener.class, "DarkeningAltar");
		GameRegistry.registerTileEntity(TileEntityGlimmerwoodChest.class, "GlimmerwoodChest");
		GameRegistry.registerTileEntity(TileEntityCherryBlossomChest.class, "CherryBlossomChest");
		GameRegistry.registerTileEntity(TileEntityBloodChest.class, "BloodChest");
		GameRegistry.registerTileEntity(TileEntitySkywoodChest.class, "SkywoodChest");
		NetworkRegistry.instance().registerGuiHandler(TheMistsOfRioV.getInstance(), TheMistsOfRioV.guiHandler);
		registerDimension(Config.blindOasisID, WorldProviderBlindOasis.class);
		registerDimension(Config.vaerynID, WorldProviderVaeryn.class);
		registerDimension(Config.flamonorID, WorldProviderFlamonor.class);
		registerDimension(Config.sanctuatiteID, WorldProviderSanctuatite.class);

		LanguageRegistry.instance().addStringLocalization("itemGroup." + Util.MOD_ID, Util.MOD_NAME);
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.white.name", "White Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.orange.name", "Orange Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.magenta.name", "Magenta Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.lightBlue.name", "Light Blue Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.yellow.name", "Yellow Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.lime.name", "Lime Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.pink.name", "Pink Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.gray.name", "Gray Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.lightGray.name", "Light Gray Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.cyan.name", "Cyan Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.purple.name", "Purple Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.blue.name", "Blue Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.brown.name", "Brown Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.green.name", "Green Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.red.name", "Red Planks");
		LanguageRegistry.instance().addStringLocalization("tile.plank_Core.black.name", "Black Planks");
	}

	public static void init(FMLInitializationEvent init)
	{		
		TheMistsOfRioV.commonProxy.registerItemRenderers();
		EntityLoader.add();
		EntityLoader.addOverworldSpawning();
		EntityLoader.addNetherSpawning();
		EntityLoader.addEndSpawning();
		EntityLoader.addNightSpawning();
		EntityLoader.addDimensionSpawning();
		BiomeGenBase.extremeHills.theBiomeDecorator.treesPerChunk = 15;
		BiomeGenBase.plains.theBiomeDecorator.treesPerChunk = 1;
		BiomeGenBase.plains.theBiomeDecorator.bigMushroomsPerChunk = 1;
		BiomeGenBase.plains.theBiomeDecorator.flowersPerChunk = 30;
		GameRegistry.registerWorldGenerator(new WorldGenOverworld());
		NetworkRegistry.instance().registerConnectionHandler(new ConnectionHandler());

		try
		{
			Class.forName("sheenrox82.RioVPaladin.Paladin");
			FMLLog.info(Util.MOD_NAME + ": Paladin detected, initiating.");
			TheMistsOfRioV.riovPaladin = true;
			if(TheMistsOfRioV.riovPaladin = true)
			{
				Items.RioVPaladin();
				EntityLoader.addPMobs();
			}
		}
		catch (Throwable var11)
		{
			FMLLog.info(Util.MOD_NAME + ": Paladin wasn't detected, not initializing.");
			TheMistsOfRioV.riovPaladin = false;
		}

		try
		{
			Class.forName("sheenrox82.RioVValis.Valis");
			FMLLog.info(Util.MOD_NAME + ": Valis detected, initiating.");
			TheMistsOfRioV.riovValis = true;
		}
		catch (Throwable var11)
		{
			FMLLog.info(Util.MOD_NAME + ": Valis wasn't detected, not initializing.");
			TheMistsOfRioV.riovValis = false;
		}

		try
		{
			Class.forName("RioVTrees.RioVTrees");
			FMLLog.info(Util.MOD_NAME + ": Trees detected, initiating.");
			TheMistsOfRioV.riovTrees = true;
			if(TheMistsOfRioV.riovTrees = true)
			{
				Items.RioVTrees();
				Blocks.RioVTrees();
			}
		}
		catch (Throwable var11)
		{
			FMLLog.info(Util.MOD_NAME + ": Trees wasn't detected, not initializing.");
			TheMistsOfRioV.riovTrees = false;
		}
	}

	public static void registerItem(Item var0, String var1)
	{
		GameRegistry.registerItem(var0, var1);
		LanguageRegistry.addName(var0, var1);
	}

	public static void registerBlock(Block var0, String var1)
	{
		GameRegistry.registerBlock(var0, var1);
		LanguageRegistry.addName(var0, var1);
	}

	public static DamageSource causeArrowDamage(EntityCustomArrow entityDarknessArrow, Entity par1Entity)
	{
		return (new EntityDamageSourceIndirect("arrow", entityDarknessArrow, par1Entity)).setProjectile();
	}

	public static void registerEntity(Class entityClass, String entityName)
	{
		int entityID = Config.addEntity(entityName);
		EntityRegistry.registerGlobalEntityID(entityClass, entityName, entityID);
		EntityRegistry.registerModEntity(entityClass, entityName, entityID, TheMistsOfRioV.getInstance(), 128, 1, true);
		LanguageRegistry.instance().addStringLocalization("entity." + entityName + ".name", entityName);
	}

	public static void registerEgg(Class entityClass)
	{
		int ID = uniqueEggID();
		EntityList.IDtoClassMapping.put(ID, entityClass);
		EntityList.entityEggs.put(ID, new EntityEggInfo(ID, 0xffffff, 0x000000));
	}

	public static int uniqueEggID()
	{
		return id++;
	}	

	public static void registerDimension(int id, Class worldProvider)
	{
		DimensionManager.registerProviderType(id, worldProvider, true);
		DimensionManager.registerDimension(id, id);
	}
}
