package sheenrox82.RioV.src.content;

import net.minecraft.block.Block;
import net.minecraft.block.BlockFlowing;
import net.minecraft.block.material.Material;
import sheenrox82.RioV.src.base.Config;
import sheenrox82.RioV.src.block.BlockAnvil;
import sheenrox82.RioV.src.block.BlockBamboo;
import sheenrox82.RioV.src.block.BlockBlackFire;
import sheenrox82.RioV.src.block.BlockBlackQuartz;
import sheenrox82.RioV.src.block.BlockBlindOasisPortal;
import sheenrox82.RioV.src.block.BlockBloodChest;
import sheenrox82.RioV.src.block.BlockBloodGrass;
import sheenrox82.RioV.src.block.BlockBloodLog;
import sheenrox82.RioV.src.block.BlockBloodRock;
import sheenrox82.RioV.src.block.BlockBricks;
import sheenrox82.RioV.src.block.BlockBush;
import sheenrox82.RioV.src.block.BlockCherryBlossomChest;
import sheenrox82.RioV.src.block.BlockCherryLog;
import sheenrox82.RioV.src.block.BlockCoreOne;
import sheenrox82.RioV.src.block.BlockFlamonorPortal;
import sheenrox82.RioV.src.block.BlockFloorboard;
import sheenrox82.RioV.src.block.BlockGlimmerGrass;
import sheenrox82.RioV.src.block.BlockGlimmerwoodChest;
import sheenrox82.RioV.src.block.BlockGlimmerwoodLog;
import sheenrox82.RioV.src.block.BlockInfuser;
import sheenrox82.RioV.src.block.BlockMagicBinder;
import sheenrox82.RioV.src.block.BlockPlanks;
import sheenrox82.RioV.src.block.BlockPlantCore;
import sheenrox82.RioV.src.block.BlockRedFire;
import sheenrox82.RioV.src.block.BlockRioVCake;
import sheenrox82.RioV.src.block.BlockRioVDoor;
import sheenrox82.RioV.src.block.BlockRioVFence;
import sheenrox82.RioV.src.block.BlockRioVFenceGate;
import sheenrox82.RioV.src.block.BlockRioVLadder;
import sheenrox82.RioV.src.block.BlockRioVLeaf;
import sheenrox82.RioV.src.block.BlockRioVSapling;
import sheenrox82.RioV.src.block.BlockRioVTallGrass;
import sheenrox82.RioV.src.block.BlockRioVTrapDoor;
import sheenrox82.RioV.src.block.BlockRioVWorkbench;
import sheenrox82.RioV.src.block.BlockRuneAbstractor;
import sheenrox82.RioV.src.block.BlockRunestoneAltar;
import sheenrox82.RioV.src.block.BlockSanctuatiteFire;
import sheenrox82.RioV.src.block.BlockSanctuatiteFlowing;
import sheenrox82.RioV.src.block.BlockSanctuatiteGrass;
import sheenrox82.RioV.src.block.BlockSanctuatitePortal;
import sheenrox82.RioV.src.block.BlockSancuatiteStill;
import sheenrox82.RioV.src.block.BlockShrine;
import sheenrox82.RioV.src.block.BlockSkycloud;
import sheenrox82.RioV.src.block.BlockSkywoodChest;
import sheenrox82.RioV.src.block.BlockSkywoodLog;
import sheenrox82.RioV.src.block.BlockStainedGlass;
import sheenrox82.RioV.src.block.BlockVaerynPortal;
import sheenrox82.RioV.src.block.BlockVoidFlowing;
import sheenrox82.RioV.src.block.BlockVoidStill;
import sheenrox82.RioV.src.block.BlockWhiteFire;
import sheenrox82.RioV.src.item.metadata.ItemBlackQuartzBlock;
import sheenrox82.RioV.src.item.metadata.ItemBricks;
import sheenrox82.RioV.src.item.metadata.ItemPlanksColored;
import sheenrox82.RioV.src.item.metadata.ItemStainedGlass;
import sheenrox82.RioV.src.util.Color;
import sheenrox82.RioV.src.util.MethodUtil;
import sheenrox82.RioV.src.util.Util;
import cpw.mods.fml.common.registry.GameRegistry;

public class Blocks 
{
	public static final Block onyxOre = (new BlockCoreOne(Config.addBlock("Onyx Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("onyxOre");
	public static final Block garnetOre = (new BlockCoreOne(Config.addBlock("Garnet Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("garnetOre");
	public static final Block infuser = (new BlockInfuser(Config.addBlock("Infuser"), true)).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("infuser_side");
	public static final Block slate = (new BlockCoreOne(Config.addBlock("Slate"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("slate");
	public static final Block nironiteOre = (new BlockCoreOne(Config.addBlock("Nironite Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("nironiteOre");
	public static final Block dragonOre = (new BlockCoreOne(Config.addBlock("Dragon Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("dragonOre");
	public static final Block netherCrystal = (new BlockCoreOne(Config.addBlock("Black Quartz Ore"))).setHardness(0.2F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("netherCrystal");
	public static final Block bloodRock = (new BlockBloodRock(Config.addBlock("Blood Rock"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("bloodRock");
	public static final Block blackDuriiPlant = (new BlockPlantCore(Config.addBlock("Black Durii Plant"))).setUnlocalizedName("blackDuriiPlant");
	public static final Block tomatoPlant = (new BlockPlantCore(Config.addBlock("Tomato Plant"))).setUnlocalizedName("tomatoPlant");
	public static final Block grapePlant = (new BlockPlantCore(Config.addBlock("Grape Plant"))).setUnlocalizedName("grapePlant");
	public static final Block onyxBlock = (new BlockCoreOne(Config.addBlock("Onyx Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("onyxBlock");
	public static final Block amethystBlock = (new BlockCoreOne(Config.addBlock("Amethyst Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("amethystBlock");
	public static final Block garnetBlock = (new BlockCoreOne(Config.addBlock("Garnet Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("garnetBlock");
	public static final Block nironiteBlock = (new BlockCoreOne(Config.addBlock("Nironite Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("nironiteBlock");
	public static final Block dragonBlock = (new BlockCoreOne(Config.addBlock("Dragon Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("dragonBlock");
	public static final Block plankColored = (new BlockPlanks(Config.addBlock("Dyed Planks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("plank_Core");
	public static final Block glimmerwoodPlanks = (new BlockCoreOne(Config.addBlock("Glimmerwood Planks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodPlanks");
	public static final Block cherryPlanks = (new BlockCoreOne(Config.addBlock("Cherry Blossom Planks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryPlanks");
	public static final Block skywoodPlanks = (new BlockCoreOne(Config.addBlock("Skywood Planks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodPlanks");
	public static final Block bloodPlanks = (new BlockCoreOne(Config.addBlock("Blood Planks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodPlanks");
	public static final Block pepperPlant = (new BlockPlantCore(Config.addBlock("Pepper Plant"))).setUnlocalizedName("pepperPlant");
	public static final Block sapphireOre = (new BlockCoreOne(Config.addBlock("Sapphire Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("sapphireOre");
	public static final Block sapphireBlock = (new BlockCoreOne(Config.addBlock("Sapphire Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("sapphireBlock");
	public static final Block opalBlock = (new BlockCoreOne(Config.addBlock("Opal Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("opalBlock");
	public static final Block topazOre = (new BlockCoreOne(Config.addBlock("Mystic Topaz Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("topazOre");
	public static final Block topazBlock = (new BlockCoreOne(Config.addBlock("Mystic Topaz Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("topazBlock");
	public static final Block cherryPlant = (new BlockPlantCore(Config.addBlock("Cherry Plant"))).setCreativeTab(null).setUnlocalizedName("cherryPlant");
	public static final Block amethystOre = (new BlockCoreOne(Config.addBlock("Amethyst Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("amethystOre");
	public static final Block lamp = (new BlockCoreOne(Config.addBlock("Lamp"))).setHardness(0.0F).setStepSound(Block.soundGlassFootstep).setLightValue(0.9F).setUnlocalizedName("lamp");
	public static final Block blackQuartz = (new BlockBlackQuartz(Config.addBlock("Black Quartz Block"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("blackQuartz");
	public static final Block blueFlower = (new BlockPlantCore(Config.addBlock("Blue Flower"))).setUnlocalizedName("blueFlower");
	public static final BlockBlindOasisPortal blindOasisPortal = (BlockBlindOasisPortal)(new BlockBlindOasisPortal(Config.addBlock("Blind Oasis Portal"))).setUnlocalizedName("blindOasisPortal");
	public static final BlockBlackFire blackFire = (BlockBlackFire)(new BlockBlackFire(Config.addBlock("Black Fire"))).setLightValue(1.0F).setUnlocalizedName("blackFire").setTextureName("blackFire");
	public static final Block blindoniteOre = (new BlockCoreOne(Config.addBlock("Blindonite Ore"))).setLightValue(0.7F).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("blindoniteOre");
	public static final Block blackRock = (new BlockCoreOne(Config.addBiomeBlock("Black Rock"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("blackRock");
	public static final Block whiteStone = (new BlockCoreOne(Config.addBiomeBlock("White Stone"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("whiteStone");
	public static final Block blindoniteBlock = (new BlockCoreOne(Config.addBlock("Blindonite Block"))).setLightValue(1.0F).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("blindoniteBlock");
	public static final Block glimmerwoodLeaf = new BlockRioVLeaf(Config.addBlock("Glimmerwood Leaves"), Material.leaves).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("glimmerwoodLeaf");
	public static final Block glimmerwoodLog = new BlockGlimmerwoodLog(Config.addBlock("Glimmerwood Log")).setUnlocalizedName("glimmerwoodSide");
	public static final Block glimmerwoodSapling = new BlockRioVSapling(Config.addBlock("Glimmerwood Sapling"), 0).setUnlocalizedName("glimmerwoodSapling");
	public static final Block glimmerGrass = (new BlockGlimmerGrass(Config.addBiomeBlock("Glimmer Grass"))).setHardness(0.6F).setUnlocalizedName("glimmerGrassSide");
	public static final Block glimmerDirt = (new BlockCoreOne(Config.addBiomeBlock("Glimmer Dirt"))).setStepSound(Block.soundGrassFootstep).setHardness(0.5F).setUnlocalizedName("glimmerDirt");
	public static final BlockVaerynPortal vaerynPortal = (BlockVaerynPortal)(new BlockVaerynPortal(Config.addBlock("Vaeryn Portal"))).setUnlocalizedName("vaerynPortal");
	public static final BlockWhiteFire whiteFire = (BlockWhiteFire)(new BlockWhiteFire(Config.addBlock("White Fire"))).setLightValue(1.0F).setUnlocalizedName("RioV:whiteFire").setTextureName("whiteFire");;
	public static final Block glimmerwoodWorkbench = (new BlockRioVWorkbench(Config.addBlock("Glimmerwood Workbench"))).setHardness(2.5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodWorkbench");
	public static final Block vraviniteOre = (new BlockCoreOne(Config.addBlock("Vravinite Ore"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("vraviniteOre");
	public static final Block glimmerwoodFence = (new BlockRioVFence(Config.addBlock("Glimmerwood Fence"), "RioV:glimmerwoodPlanks", Material.wood)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodFence");
	public static final Block glimmerwoodFenceGate = (new BlockRioVFenceGate(Config.addBlock("Glimmerwood Fencegate"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodFenceGate");
	public static final Block glimmerRock = (new BlockCoreOne(Config.addBiomeBlock("Glimmer Rock"))).setHardness(0.5F).setUnlocalizedName("glimmerRock");
	public static final BlockRioVDoor glimmerwoodDoor = (BlockRioVDoor) (new BlockRioVDoor(Config.addBlock("Glimmerwood Door"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodDoor");
	public static final Block glimmerwoodLadder = (new BlockRioVLadder(Config.addBlock("Glimmerwood Ladder"))).setHardness(0.4F).setStepSound(Block.soundLadderFootstep).setUnlocalizedName("glimmerwoodLadder");
	public static final Block glimmerwoodTrapdoor = (new BlockRioVTrapDoor(Config.addBlock("Glimmerwood Trapdoor"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("glimmerwoodTrapDoor");
	public static final Block bloodGrass = (new BlockBloodGrass(Config.addBiomeBlock("Blood Grass"))).setStepSound(Block.soundGrassFootstep).setHardness(0.6F).setUnlocalizedName("bloodGrassSide");
	public static final Block bloodDirt = (new BlockCoreOne(Config.addBiomeBlock("Blood Dirt"))).setStepSound(Block.soundGrassFootstep).setHardness(0.5F).setUnlocalizedName("bloodDirt");
	public static final BlockFlamonorPortal flamonorPortal = (BlockFlamonorPortal)(new BlockFlamonorPortal(Config.addBlock("Flamonor Portal"))).setUnlocalizedName("flamonorPortal");
	public static final Block flamonorRock = (new BlockCoreOne(Config.addBiomeBlock("Flamonor Rock"))).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("flamonorRock");
	public static final BlockRedFire redFire = (BlockRedFire)(new BlockRedFire(Config.addBlock("Red Fire"))).setLightValue(1.0F).setUnlocalizedName("redFire");
	public static final Block drakiuzOre = (new BlockCoreOne(Config.addBlock("Drakiuz Ore"))).setStepSound(Block.soundStoneFootstep).setHardness(6.0F).setUnlocalizedName("drakiuzOre");
	public static final BlockGlimmerwoodChest glimmerwoodChest = (BlockGlimmerwoodChest)(new BlockGlimmerwoodChest(Config.addBlock("Glimmerwood Chest"), 0)).setStepSound(Block.soundWoodFootstep).setHardness(0.5F).setUnlocalizedName("glimmerwoodChest");
	public static final Block slateCobble = (new BlockCoreOne(Config.addBlock("Cobbleslate"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("slateCobble");
	public static final Block slateBricks = (new BlockCoreOne(Config.addBlock("Cobbleslate Bricks"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("slateBricks");
	public static final Block cherryLeaf = new BlockRioVLeaf(Config.addBlock("Cherry Blossom Leaves"), Material.leaves).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("cherryLeaf");
	public static final Block cherryLog = new BlockCherryLog(Config.addBlock("Cherry Blossom Log")).setUnlocalizedName("cherryLog");
	public static final Block cherryBlossomSapling = new BlockRioVSapling(Config.addBlock("Cherry Blossom Sapling"), 0).setUnlocalizedName("cherryBlossomSapling");
	public static final Block cherryWorkbench = (new BlockRioVWorkbench(Config.addBlock("Cherry Blossom Workbench"))).setHardness(2.5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryWorkbench");
	public static final Block cherryBlossomFence = (new BlockRioVFence(Config.addBlock("Cherry Blossom Fence"), "RioV:cherryPlanks", Material.wood)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryBlossomFence");
	public static final Block cherryBlossomFenceGate = (new BlockRioVFenceGate(Config.addBlock("Cherry Blossom Fencegate"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryBlossomFenceGate");
	public static final BlockRioVDoor cherryBlossomDoor = (BlockRioVDoor) (new BlockRioVDoor(Config.addBlock("Cherry Blossom Door"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryBlossomDoor");
	public static final Block cherryBlossomLadder = (new BlockRioVLadder(Config.addBlock("Cherry Blossom Ladder"))).setHardness(0.4F).setStepSound(Block.soundLadderFootstep).setUnlocalizedName("cherryBlossomLadder");
	public static final Block cherryBlossomTrapdoor = (new BlockRioVTrapDoor(Config.addBlock("Cherry Blossom Trapdoor"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("cherryBlossomTrapDoor");
	public static final BlockCherryBlossomChest cherryBlossomChest = (BlockCherryBlossomChest)(new BlockCherryBlossomChest(Config.addBlock("Cherry Blossom Chest"), 0)).setStepSound(Block.soundWoodFootstep).setHardness(0.5F).setUnlocalizedName("cherryBlossomChest");
	public static final Block paleLeaf = new BlockRioVLeaf(Config.addBlock("Pale Leaf"), Material.leaves).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("paleLeaf");
	public static final Block bloodLog = new BlockBloodLog(Config.addBlock("Blood Log")).setUnlocalizedName("bloodLog");
	public static final Block bloodSapling = new BlockRioVSapling(Config.addBlock("Blood Sapling"), 0).setUnlocalizedName("bloodSapling");
	public static final BlockFlowing sanctuatiteMoving = (BlockFlowing)(new BlockSanctuatiteFlowing(Config.addBlock("Sanctuatite Moving"), Material.water)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("sancuatiteMoving");
	public static final Block sanctuatiteStill = (new BlockSancuatiteStill(Config.addBlock("Sanctuatite Still"), Material.water)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("sancuatiteStill");
	public static final BlockSanctuatitePortal sanctuatitePortal = (BlockSanctuatitePortal)(new BlockSanctuatitePortal(Config.addBlock("Sanctuatite Portal"))).setUnlocalizedName("sancuatitePortal");
	public static final BlockSanctuatiteFire sanctuatiteFire = (BlockSanctuatiteFire)(new BlockSanctuatiteFire(Config.addBlock("Sanctuatite Fire"))).setLightValue(1.0F).setUnlocalizedName("flamonorFire");
	public static final Block sanctuatiteGrass = (new BlockSanctuatiteGrass(Config.addBiomeBlock("Sanctuatite Grass"))).setHardness(0.6F).setUnlocalizedName("sanctuatiteGrassSide");
	public static final Block sanctuatiteDirt = (new BlockCoreOne(Config.addBiomeBlock("Sanctuatite Dirt"))).setStepSound(Block.soundGrassFootstep).setHardness(0.5F).setUnlocalizedName("sanctuatiteDirt");
	public static final Block sanctuatiteTallGrass = new BlockRioVTallGrass(Config.addBlock("Sanctuatite Tall Grass"), Material.grass).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("sanctuatiteTallGrass");
	public static final Block sanctuaryStone = (new BlockCoreOne(Config.addBiomeBlock("Sanctuatite Stone"))).setHardness(2F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("sanctuaryStone");
	public static final Block skycloud = new BlockSkycloud(Config.addBlock("Skycloud")).setStepSound(Block.soundClothFootstep).setUnlocalizedName("skycloud");
	public static final Block skywoodLog = new BlockSkywoodLog(Config.addBlock("Skywood Log")).setUnlocalizedName("skywoodLog");
	public static final Block skywoodSapling = new BlockRioVSapling(Config.addBlock("Skywood Sapling"), 0).setUnlocalizedName("sanctuaryTreeSapling");
	public static final Block bloodWorkbench = (new BlockRioVWorkbench(Config.addBlock("Blood Workbench"))).setHardness(2.5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodWorkbench");
	public static final Block bloodFence = (new BlockRioVFence(Config.addBlock("Blood Fence"), "RioV:bloodPlanks", Material.wood)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodFence");
	public static final Block bloodFenceGate = (new BlockRioVFenceGate(Config.addBlock("Blood Fencegate"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodFenceGate");
	public static final BlockRioVDoor bloodDoor = (BlockRioVDoor) (new BlockRioVDoor(Config.addBlock("Blood Door"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodDoor");
	public static final Block bloodLadder = (new BlockRioVLadder(Config.addBlock("Blood Ladder"))).setHardness(0.4F).setStepSound(Block.soundLadderFootstep).setUnlocalizedName("bloodLadder");
	public static final Block bloodTrapdoor = (new BlockRioVTrapDoor(Config.addBlock("Blood Trapdoor"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("bloodTrapDoor");
	public static final BlockBloodChest bloodChest = (BlockBloodChest)(new BlockBloodChest(Config.addBlock("Blood Chest"), 0)).setStepSound(Block.soundWoodFootstep).setHardness(0.5F).setUnlocalizedName("bloodChest");
	public static final Block skywoodWorkbench = (new BlockRioVWorkbench(Config.addBlock("Skywood Workbench"))).setHardness(2.5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodWorkbench");
	public static final Block skywoodFence = (new BlockRioVFence(Config.addBlock("Skywood Fence"), "RioV:cherryPlanks", Material.wood)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodFence");
	public static final Block skywoodFenceGate = (new BlockRioVFenceGate(Config.addBlock("Skywood Fencegate"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodFenceGate");
	public static final BlockRioVDoor skywoodDoor = (BlockRioVDoor) (new BlockRioVDoor(Config.addBlock("Skywood Door"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodDoor");
	public static final Block skywoodLadder = (new BlockRioVLadder(Config.addBlock("Skywood Ladder"))).setHardness(0.4F).setStepSound(Block.soundLadderFootstep).setUnlocalizedName("skywoodLadder");
	public static final Block skywoodTrapdoor = (new BlockRioVTrapDoor(Config.addBlock("Skywood Trapdoor"), Material.wood)).setHardness(3.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("skywoodTrapDoor");
	public static final BlockSkywoodChest skywoodChest = (BlockSkywoodChest)(new BlockSkywoodChest(Config.addBlock("Skywood Chest"), 0)).setStepSound(Block.soundWoodFootstep).setHardness(0.5F).setUnlocalizedName("skywoodChest");
	public static final Block alerisOre = (new BlockCoreOne(Config.addBlock("Aleris Ore"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("alerisOre");
	public static final Block anvil = (new BlockAnvil(Config.addBlock("Anvil"))).setStepSound(Block.soundAnvilFootstep).setUnlocalizedName("anvil:3");
	public static final BlockFlowing voidMoving = (BlockFlowing)(new BlockVoidFlowing(Config.addBiomeBlock("Void Liquid Moving"), Material.water)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("voidMoving");
	public static final Block voidStill = (new BlockVoidStill(Config.addBiomeBlock("Void Liquid Still"), Material.water)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("voidStill");
	public static final Block bamboo = (new BlockBamboo(Config.addBlock("Bamboo"))).setUnlocalizedName("bamboo");
	public static final Block blueBerryBush = (new BlockBush(Config.addBlock("Berry Bush"))).setUnlocalizedName("blueBerryBush");
	public static final Block raspBerryBush = (new BlockBush(Config.addBlock("Raspberry Bush"))).setUnlocalizedName("raspberryBush");
	public static final Block blackBerryBush = (new BlockBush(Config.addBlock("Blackberry Bush"))).setUnlocalizedName("blackBerryBush");
	public static final Block strawberryBush = (new BlockBush(Config.addBlock("Strawberry Bush"))).setUnlocalizedName("strawberryBush");
	public static final Block bambooFloorboard = (new BlockFloorboard(Config.addBlock("Bamboo Floorboard"))).setUnlocalizedName("bambooFloorboard");
	public static final Block bush = (new BlockBush(Config.addBlock("Bush"))).setUnlocalizedName("bush");
	public static final Block bloodBerryBush = (new BlockBush(Config.addBlock("Bloodberry Bush"))).setUnlocalizedName("bloodBerryBush");
	public static final Block jaavikOre = (new BlockCoreOne(Config.addBlock("Jaavik Ore"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("jaavikOre");
	public static final Block jaavikBlock = (new BlockCoreOne(Config.addBlock("Jaavik Block"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("jaavikBlock");
	public static final Block steamingBloodDeposit = (new BlockBloodRock(Config.addBlock("Steaming Blood Deposit"))).setLightValue(0.9F).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("steamingBloodDeposit");
	public static final BlockFlowing steamingBloodFlowing = (BlockFlowing)(new BlockSanctuatiteFlowing(Config.addBlock("Steaming Blood Flowing"), Material.lava)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("steamingBloodFlowing");
	public static final Block steamingBloodStill = (new BlockSancuatiteStill(Config.addBlock("Steaming Blood Still"), Material.lava)).setHardness(100.0F).setLightOpacity(3).setUnlocalizedName("steamingBloodStill");
	public static final Block magicBinder = new BlockMagicBinder(Config.addBlock("Magic Binder")).setLightValue(0.6F).setUnlocalizedName("magicBinder");
	public static final Block alerisBlock = (new BlockCoreOne(Config.addBlock("Aleris Block"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("alerisBlock");
	public static final Block drakiuzBlock = (new BlockCoreOne(Config.addBlock("Drakiuz Block"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("drakiuzBlock");
	public static final Block crackedSlateBricks = (new BlockCoreOne(Config.addBlock("Cracked Cobbleslate Bricks"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("crackedSlateBricks");
	public static final Block bricks = (new BlockBricks(Config.addBlock("Bricks"))).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("bricks");
	public static final Block vraviniteBlock = (new BlockCoreOne(Config.addBlock("Vravinite Block"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("vraviniteBlock");
	public static final Block stainedGlass = (new BlockStainedGlass(Config.addBlock("Stained Glass"))).setHardness(0.6F).setResistance(1F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("stainedGlass");
	public static final Block runestone = (new BlockCoreOne(Config.addBlock("Runestone Block"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("runestone");
	public static final Block abstractor = (new BlockRuneAbstractor(Config.addBlock("Runestone Abstractor"), false)).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("abstractor");
	public static final Block abstractorActive = (new BlockRuneAbstractor(Config.addBlock("Runestone Abstractorm Active"), true)).setCreativeTab(null).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("abstractorOn");
	public static final Block runestoneAltar = (new BlockRunestoneAltar(Config.addBlock("Runestone Altar"))).setHardness(6.0F).setStepSound(Block.soundStoneFootstep).setHardness(0.5F).setUnlocalizedName("runestoneAltar");
	public static final Block bloodFlower = (new BlockPlantCore(Config.addBlock("Blood Flower"))).setUnlocalizedName("bloodFlower");
	public static final Block paleBush = (new BlockBush(Config.addBlock("Pale Bush"))).setUnlocalizedName("paleBush");
	public static final Block waterFilledGlowstone = (new BlockCoreOne(Config.addBlock("Water Filled Glowstone"))).setCreativeTab(null).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("waterFilledGlowstone");
	public static final Block coconut = (new BlockBush(Config.addBlock("Coconut"))).setCreativeTab(null).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("coconut");
	public static final Block shrine = (new BlockShrine(Config.addBlock("Shrine"))).setHardness(6.0F).setResistance(6.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("shrine");
    public static final Block chocolateCake = (new BlockRioVCake(Config.addBlock("Chocolate Cake"))).setHardness(0.5F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("chocolateCake");

	public static void add()
	{	
		GameRegistry.registerBlock(stainedGlass, ItemStainedGlass.class, Util.MOD_ID + (stainedGlass.getUnlocalizedName().substring(5)));	
		GameRegistry.registerBlock(blackQuartz, ItemBlackQuartzBlock.class, Util.MOD_ID + (blackQuartz.getUnlocalizedName().substring(5)));		
		GameRegistry.registerBlock(bricks, ItemBricks.class, Util.MOD_ID + (bricks.getUnlocalizedName().substring(5)));		
		GameRegistry.registerBlock(plankColored, ItemPlanksColored.class, Util.MOD_ID + (plankColored.getUnlocalizedName().substring(5)));		
		MethodUtil.registerBlock(steamingBloodFlowing, Color.DARK_RED + "Steaming Blood Flowing");
		MethodUtil.registerBlock(steamingBloodStill, Color.DARK_RED + "Steaming Blood Still");
		MethodUtil.registerBlock(steamingBloodDeposit, Color.DARK_RED + "Steaming Blood Deposit");
		MethodUtil.registerBlock(bloodBerryBush, Color.DARK_RED + "Blood Berry Bush");
		MethodUtil.registerBlock(bloodFlower, Color.DARK_RED + "Blood Flower");
		MethodUtil.registerBlock(waterFilledGlowstone, Color.AQUA + "Hydrogenic Glowstone");
		MethodUtil.registerBlock(chocolateCake, "Chocolate Cake");
		MethodUtil.registerBlock(paleBush, "Pale Bush");
		MethodUtil.registerBlock(shrine, "Shrine");
		MethodUtil.registerBlock(coconut, "Coconut");
		MethodUtil.registerBlock(runestone, "Runestone Deposit");
		MethodUtil.registerBlock(runestoneAltar, "Runestone Altar");
		MethodUtil.registerBlock(abstractor, "Runestone Abstractor");
		MethodUtil.registerBlock(abstractorActive, "Runestone Abstractor Active");
		MethodUtil.registerBlock(drakiuzBlock, "Drakiuz Block");
		MethodUtil.registerBlock(vraviniteBlock, "Vravinite Block");
		MethodUtil.registerBlock(crackedSlateBricks, "Cracked Slate Bricks");
		MethodUtil.registerBlock(alerisBlock, "Aleris Block");
		MethodUtil.registerBlock(glimmerwoodPlanks, "Glimmerwood Planks");
		MethodUtil.registerBlock(magicBinder, "Magic Binder");
		MethodUtil.registerBlock(cherryPlanks, "Cherry Blossom Planks");
		MethodUtil.registerBlock(skywoodPlanks, "Skywood Planks");
		MethodUtil.registerBlock(bloodPlanks, "Blood Planks");
		MethodUtil.registerBlock(bush, "Bush");
		MethodUtil.registerBlock(bambooFloorboard, "Bamboo Floorboard");
		MethodUtil.registerBlock(bamboo, "Bamboo");
		MethodUtil.registerBlock(blueBerryBush, "Blueberry Bush");
		MethodUtil.registerBlock(raspBerryBush, "Raspberry Bush");
		MethodUtil.registerBlock(blackBerryBush, "Blackberry Bush");
		MethodUtil.registerBlock(strawberryBush, "Strawberry Bush");
		MethodUtil.registerBlock(jaavikBlock, "Jaavik Block");
		MethodUtil.registerBlock(jaavikOre, "Jaavik Ore");
		MethodUtil.registerBlock(voidMoving, "Void Liquid Moving");
		MethodUtil.registerBlock(voidStill, "Void Liquid Still");
		MethodUtil.registerBlock(anvil, "Anvil");
		MethodUtil.registerBlock(alerisOre, "Aleris Ore");
		MethodUtil.registerBlock(bloodChest, "Blood Chest");
		MethodUtil.registerBlock(bloodLadder, "Blood Ladder");
		MethodUtil.registerBlock(bloodTrapdoor, "Blood Trapdoor");
		MethodUtil.registerBlock(bloodFence, "Blood Fence");
		MethodUtil.registerBlock(bloodFenceGate, "Blood Fence Gate");
		MethodUtil.registerBlock(bloodWorkbench, "Blood Workbench");
		MethodUtil.registerBlock(skywoodChest, "Skywood Chest");
		MethodUtil.registerBlock(skywoodLadder, "Skywood Ladder");
		MethodUtil.registerBlock(skywoodTrapdoor, "Skywood Trapdoor");
		MethodUtil.registerBlock(skywoodFence, "Skywood Fence");
		MethodUtil.registerBlock(skywoodFenceGate, "Skywood Fence Gate");
		MethodUtil.registerBlock(skywoodWorkbench, "Skywood Workbench");
		MethodUtil.registerBlock(skycloud, "Skycloud");
		MethodUtil.registerBlock(skywoodLog, "Skywood Log");
		MethodUtil.registerBlock(skywoodSapling, "Skywood Sapling");
		MethodUtil.registerBlock(sanctuaryStone, "Sanctuary Stone");
		MethodUtil.registerBlock(sanctuatiteTallGrass, "Sanctuatite Tall Grass");
		MethodUtil.registerBlock(sanctuatitePortal, "Sanctuatite Portal");
		MethodUtil.registerBlock(sanctuatiteGrass, "Sanctuatite Grass");
		MethodUtil.registerBlock(sanctuatiteDirt, "Sanctuatite Dirt");
		MethodUtil.registerBlock(sanctuatiteFire, "Fire of Flamonor");
		MethodUtil.registerBlock(sanctuatiteMoving, "Sancuatite Moving");
		MethodUtil.registerBlock(sanctuatiteStill, "Sancuatite Still");
		MethodUtil.registerBlock(paleLeaf, "Pale Leaf");
		MethodUtil.registerBlock(bloodLog, "Blood Log");
		MethodUtil.registerBlock(bloodSapling, "Blood Sapling");
		MethodUtil.registerBlock(cherryBlossomChest, "Cherry Blossom Chest");
		MethodUtil.registerBlock(cherryBlossomLadder, "Cherry Blossom Ladder");
		MethodUtil.registerBlock(cherryBlossomTrapdoor, "Cherry Blossom Trapdoor");
		MethodUtil.registerBlock(cherryBlossomFence, "Cherry Blossom Fence");
		MethodUtil.registerBlock(cherryBlossomFenceGate, "Cherry Blossom Fence Gate");
		MethodUtil.registerBlock(cherryWorkbench, "Cherry Blossom Workbench");
		MethodUtil.registerBlock(cherryBlossomSapling, "Cherry Blossom Sapling");
		MethodUtil.registerBlock(cherryLog, "Cherry Blossom Log");
		MethodUtil.registerBlock(cherryLeaf, "Cherry Blossom Leaf");
		MethodUtil.registerBlock(slateBricks, "Slate Bricks");
		MethodUtil.registerBlock(slateCobble, "Cobbleslate");
		MethodUtil.registerBlock(glimmerwoodChest, "Glimmerwood Chest");
		MethodUtil.registerBlock(drakiuzOre, "Drakiuz Ore");
		MethodUtil.registerBlock(flamonorRock, "Flamonor Rock");
		MethodUtil.registerBlock(flamonorPortal, "Flamonor Portal");
		MethodUtil.registerBlock(bloodGrass, "Blood Grass");
		MethodUtil.registerBlock(bloodDirt, "Blood Dirt");
		MethodUtil.registerBlock(glimmerwoodTrapdoor, "Glimmerwood Trapdoor");
		MethodUtil.registerBlock(glimmerwoodLadder, "Glimmerwood Ladder");
		MethodUtil.registerBlock(glimmerRock, "Glimmer Rock");
		MethodUtil.registerBlock(glimmerwoodFenceGate, "Glimmerwood Fence Gate");
		MethodUtil.registerBlock(glimmerwoodFence, "Glimmerwood Fence");
		MethodUtil.registerBlock(vraviniteOre, "Vravinite Ore");
		MethodUtil.registerBlock(glimmerwoodWorkbench, "Glimmerwood Workbench");
		MethodUtil.registerBlock(vaerynPortal, "Vaeryn Portal");
		MethodUtil.registerBlock(whiteFire, "White Fire");
		MethodUtil.registerBlock(glimmerGrass, "Glimmer Grass");
		MethodUtil.registerBlock(glimmerDirt, "Glimmer Dirt");
		MethodUtil.registerBlock(glimmerwoodLeaf, "Glimmerwood Leaf");
		MethodUtil.registerBlock(glimmerwoodLog, "Glimmerwood Log");
		MethodUtil.registerBlock(glimmerwoodSapling, "Glimmerwood Sapling");
		MethodUtil.registerBlock(blindoniteBlock, "Blindonite Block");
		MethodUtil.registerBlock(whiteStone, "White Stone");
		MethodUtil.registerBlock(blindoniteOre, "Blindonite Ore");
		MethodUtil.registerBlock(blackFire, "Black Fire");
		MethodUtil.registerBlock(blindOasisPortal, "Blind Oasis Portal");
		MethodUtil.registerBlock(blackRock, "Black Stone");
		MethodUtil.registerBlock(blueFlower, "Blue Flower");
		MethodUtil.registerBlock(lamp, "Lamp");
		MethodUtil.registerBlock(amethystOre, "Amethyst Ore");
		MethodUtil.registerBlock(cherryPlant, "Cherry Plant");
		MethodUtil.registerBlock(topazBlock, "Mystic Topaz Block");
		MethodUtil.registerBlock(topazOre, "Mystic Topaz Ore");
		MethodUtil.registerBlock(opalBlock, "Opal Block");
		MethodUtil.registerBlock(sapphireBlock, "Sapphire Block");
		MethodUtil.registerBlock(sapphireOre, "Sapphire Ore");
		MethodUtil.registerBlock(pepperPlant, "Pepper Plant");
		MethodUtil.registerBlock(grapePlant, "Grape Plant");
		MethodUtil.registerBlock(tomatoPlant, "Tomato Plant");
		MethodUtil.registerBlock(onyxOre, "Onyx Ore");
		MethodUtil.registerBlock(blackDuriiPlant, "Black Durii Plant");
		MethodUtil.registerBlock(garnetOre, "Garnet Ore");
		MethodUtil.registerBlock(infuser, "Infuser");
		MethodUtil.registerBlock(slate, "Slate");
		MethodUtil.registerBlock(nironiteOre, "Nironite Ore");
		MethodUtil.registerBlock(dragonOre, "Dragon Ore");
		MethodUtil.registerBlock(netherCrystal, "Black Quartz Ore");
		MethodUtil.registerBlock(bloodRock, "Blood Rock");
		MethodUtil.registerBlock(onyxBlock, "Onyx Block");
		MethodUtil.registerBlock(amethystBlock, "Amethyst Block");
		MethodUtil.registerBlock(garnetBlock, "Garnet Block");
		MethodUtil.registerBlock(nironiteBlock, "Nironite Block");
		MethodUtil.registerBlock(dragonBlock, "Dragon Soul Block");
	}
}
