package sheenrox82.RioV.src.content;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraftforge.common.EnumHelper;
import sheenrox82.RioV.src.base.Config;
import sheenrox82.RioV.src.base.TheMistsOfRioV;
import sheenrox82.RioV.src.item.RioVActivators;
import sheenrox82.RioV.src.item.RioVArmor;
import sheenrox82.RioV.src.item.RioVAxe;
import sheenrox82.RioV.src.item.RioVBag;
import sheenrox82.RioV.src.item.RioVBucket;
import sheenrox82.RioV.src.item.RioVConsumable;
import sheenrox82.RioV.src.item.RioVDoor;
import sheenrox82.RioV.src.item.RioVDrinkable;
import sheenrox82.RioV.src.item.RioVExplosives;
import sheenrox82.RioV.src.item.RioVItem;
import sheenrox82.RioV.src.item.RioVPickaxe;
import sheenrox82.RioV.src.item.RioVPotions;
import sheenrox82.RioV.src.item.RioVShield;
import sheenrox82.RioV.src.item.RioVSpade;
import sheenrox82.RioV.src.item.RioVSummoners;
import sheenrox82.RioV.src.item.RioVVoidHolder;
import sheenrox82.RioV.src.item.RioVWand;
import sheenrox82.RioV.src.item.RioVWeapon;
import sheenrox82.RioV.src.item.unique.ItemBamboo;
import sheenrox82.RioV.src.item.unique.ItemBowOfWurTun;
import sheenrox82.RioV.src.item.unique.ItemDragonChestplate;
import sheenrox82.RioV.src.item.unique.ItemEnforcedBowOfWurTun;
import sheenrox82.RioV.src.item.unique.ItemGuide;
import sheenrox82.RioV.src.item.unique.ItemRune;
import sheenrox82.RioV.src.item.unique.ItemScrollUsable;
import sheenrox82.RioV.src.item.unique.ItemTasaravChestplate;
import sheenrox82.RioV.src.item.unique.ItemTasaravHelmet;
import sheenrox82.RioV.src.item.unique.ItemVraviniteBow;
import sheenrox82.RioV.src.proxy.CommonProxy;
import sheenrox82.RioV.src.util.Color;
import sheenrox82.RioV.src.util.MethodUtil;

public class Items 
{
	public static final int render = CommonProxy.addArmor("armor");
	public static String level1 = "I";
	public static String level2 = "II";
	public static String level3 = "III";

	static EnumToolMaterial Sapphire = EnumHelper.addToolMaterial("Sapphire", 2, 300, 4F, 1, 10);
	static EnumToolMaterial Topaz = EnumHelper.addToolMaterial("Topaz", 2, 350, 4F, 1, 10);
	static EnumToolMaterial InfusedSapphire = EnumHelper.addToolMaterial("Sapphire", 4, 400, 5F, 2, 10);
	static EnumToolMaterial InfusedTopaz = EnumHelper.addToolMaterial("Topaz", 3, 450, 5F, 2, 10);
	static EnumToolMaterial Amethyst = EnumHelper.addToolMaterial("Amethyst", 3, 400, 5F, 4, 8);
	static EnumToolMaterial InfusedAmethyst = EnumHelper.addToolMaterial("InfusedAmethyst", 3, 500, 9F, 5, 9);
	static EnumToolMaterial Onyx = EnumHelper.addToolMaterial("Onyx", 3, 600, 10F, 5, 10);
	static EnumToolMaterial InfusedOnyx = EnumHelper.addToolMaterial("InfusedOnyx", 4, 700, 11F, 6, 11);
	static EnumToolMaterial Agonite = EnumHelper.addToolMaterial("Agonite", 8, 1000, 9F, 3, 14);
	static EnumToolMaterial Dragon = EnumHelper.addToolMaterial("Dragon", 9, 3000, 15F, 10, 15);
	static EnumToolMaterial Daetori = EnumHelper.addToolMaterial("Daetori", 2, 500, 5F, 9, 12);
	static EnumToolMaterial Sorrow = EnumHelper.addToolMaterial("Sorrow", 2, 700, 5F, 10, 13);
	static EnumToolMaterial AxeOfAunTun = EnumHelper.addToolMaterial("AxeOfAunTun", 2, 2500, 5F, 18, 16);
	static EnumToolMaterial UltraAxeOfAunTun = EnumHelper.addToolMaterial("UltraAxeOfAunTun", 2, 5000, 5F, 26, 30);
	static EnumToolMaterial Vulron = EnumHelper.addToolMaterial("Vulron", 6, 200, 9F, 6, 12);
	static EnumToolMaterial InfusedDragon = EnumHelper.addToolMaterial("InfusedDragon", 11, 3400, 18F, 11, 16);
	static EnumToolMaterial Galokin = EnumHelper.addToolMaterial("Galokin", 4, 400, 6F, 6, 12);
	static EnumToolMaterial Flame = EnumHelper.addToolMaterial("Flame", 6, 900, 9F, 7, 16);
	static EnumToolMaterial Blindonite = EnumHelper.addToolMaterial("Blindonite", 4, 400, 6F, 5, 14);
	static EnumToolMaterial InfusedBlindonite = EnumHelper.addToolMaterial("InfusedBlindonite", 5, 600, 8F, 7, 15);
	static EnumToolMaterial Glimmerwood = EnumHelper.addToolMaterial("Glimmerwood", 2, 250, 4F, 2, 20);
	static EnumToolMaterial CherryBlossom = EnumHelper.addToolMaterial("CherryBlossom", 2, 100, 2F, 0, 20);
	static EnumToolMaterial Aleris = EnumHelper.addToolMaterial("Aleris", 14, 2400, 14F, 16, 21);
	static EnumToolMaterial InfusedVravinite = EnumHelper.addToolMaterial("InfusedVravinite", 13, 1000, 13F, 11, 12);
	static EnumToolMaterial Vravinite = EnumHelper.addToolMaterial("Vravinite", 12, 900, 13F, 10, 12);

	static EnumArmorMaterial InfusedAmethystArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDAMETHYST", 17, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial InfusedOnyxArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDONYX", 18, new int[] {5, 6, 6, 5}, 20);
	static EnumArmorMaterial InfusedSapphireArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDSAPPHIRE", 15, new int[] {3, 6, 6, 3}, 20);
	static EnumArmorMaterial InfusedTopazArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDTOPAZ", 14, new int[] {3, 5, 5, 3}, 20);
	static EnumArmorMaterial InfusedDragonArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDDRAGON", 39, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial DragonArmorMaterial = EnumHelper.addArmorMaterial("DRAGON", 37, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial AunTunArmorMaterial = EnumHelper.addArmorMaterial("AUNTUN", 40, new int[] {3, 8, 6, 3}, 20);
	static EnumArmorMaterial GarnetArmorMaterial = EnumHelper.addArmorMaterial("GARNET", 22, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial AmethystArmorMaterial = EnumHelper.addArmorMaterial("AMETHYST", 15, new int[] {3, 5, 6, 3}, 20);
	static EnumArmorMaterial OnyxArmorMaterial = EnumHelper.addArmorMaterial("ONYX", 16, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial MythrilArmorMaterial = EnumHelper.addArmorMaterial("MYTHRIL", 36, new int[] {4, 8, 6, 4}, 20);
	static EnumArmorMaterial GalokinArmorMaterial = EnumHelper.addArmorMaterial("GALOKIN", 33, new int[] {3, 8, 6, 3}, 20);
	static EnumArmorMaterial SapphireArmorMaterial = EnumHelper.addArmorMaterial("SAPPHIRE", 10, new int[] {3, 5, 5, 3}, 20);
	static EnumArmorMaterial TopazArmorMaterial = EnumHelper.addArmorMaterial("TOPAZ", 9, new int[] {3, 4, 4, 3}, 20);
	static EnumArmorMaterial FlameArmorMaterial = EnumHelper.addArmorMaterial("FLAME", 30, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial BlindoniteArmorMaterial = EnumHelper.addArmorMaterial("BLINDONITE", 20, new int[] {3, 4, 6, 3}, 20);
	static EnumArmorMaterial InfusedBlindoniteArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDBLINDONITE", 23, new int[] {3, 4, 6, 3}, 20);
	static EnumArmorMaterial AlerisArmorMaterial = EnumHelper.addArmorMaterial("ALERIS", 48, new int[] {5, 8, 6, 5}, 20);
	static EnumArmorMaterial InfusedVraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 33, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial VraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 32, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial KupinumArmorMaterial = EnumHelper.addArmorMaterial("KUPINUM", 45, new int[] {3, 7, 6, 3}, 16);
	static EnumArmorMaterial SupremeAunTunArmorMaterial = EnumHelper.addArmorMaterial("SUPREMEAUNTUN", 68, new int[] {7, 10, 9, 9}, 50);

	public static Item onyxHelmet = (new RioVArmor(Config.addItem("Onyx Helmet"), OnyxArmorMaterial, render, 0, "onyx", false)).setUnlocalizedName("onyxHelmet");
	public static Item onyxChestplate = (new RioVArmor(Config.addItem("Onyx Chestplate"), OnyxArmorMaterial, render, 1, "onyx", false)).setUnlocalizedName("onyxChestplate");
	public static Item onyxLeggings = (new RioVArmor(Config.addItem("Onyx Leggings"), OnyxArmorMaterial, render, 2, "onyx", false)).setUnlocalizedName("onyxLeggings");
	public static Item onyxBoots = (new RioVArmor(Config.addItem("Onyx Boots"), OnyxArmorMaterial, render, 3, "onyx", false)).setUnlocalizedName("onyxBoots");
	public static Item amethystHelmet = (new RioVArmor(Config.addItem("Amethyst Helmet"), AmethystArmorMaterial, render, 0, "amethyst", false)).setUnlocalizedName("amethystHelmet");
	public static Item amethystChestplate = (new RioVArmor(Config.addItem("Amethyst Chestplate"), AmethystArmorMaterial, render, 1, "amethyst", false)).setUnlocalizedName("amethystChestplate");
	public static Item amethystLeggings = (new RioVArmor(Config.addItem("Amethyst Leggings"), AmethystArmorMaterial, render, 2, "amethyst", false)).setUnlocalizedName("amethystLeggings");
	public static Item amethystBoots = (new RioVArmor(Config.addItem("Amethyst Boots"), AmethystArmorMaterial, render, 3, "amethyst", false)).setUnlocalizedName("amethystBoots");
	public static Item infusedOnyxHelmet = (new RioVArmor(Config.addItem("Infused Onyx Helmet"), InfusedOnyxArmorMaterial, render, 0, "onyx", true)).setUnlocalizedName("infusedOnyxHelmet");;
	public static Item infusedOnyxChestplate = (new RioVArmor(Config.addItem("Infused Onyx Chestplate"), InfusedOnyxArmorMaterial, render, 1, "onyx", true)).setUnlocalizedName("infusedOnyxChestplate");;
	public static Item infusedOnyxLeggings = (new RioVArmor(Config.addItem("Infused Onyx Leggings"), InfusedOnyxArmorMaterial, render, 2, "onyx", true)).setUnlocalizedName("infusedOnyxLeggings");;
	public static Item infusedOnyxBoots = (new RioVArmor(Config.addItem("Infused Onyx Boots"), InfusedOnyxArmorMaterial, render, 3, "onyx", true)).setUnlocalizedName("infusedOnyxBoots");;
	public static Item infusedAmethystHelmet = (new RioVArmor(Config.addItem("Infused Amethyst Helmet"), InfusedAmethystArmorMaterial, render, 0, "amethyst", true)).setUnlocalizedName("infusedAmethystHelmet");
	public static Item infusedAmethystChestplate = (new RioVArmor(Config.addItem("Infused Amethyst Chestplate"), InfusedAmethystArmorMaterial, render, 1, "amethyst", true)).setUnlocalizedName("infusedAmethystChestplate");
	public static Item infusedAmethystLeggings = (new RioVArmor(Config.addItem("Infused Amethyst Leggings"), InfusedAmethystArmorMaterial, render, 2, "amethyst", true)).setUnlocalizedName("infusedAmethystLeggings");
	public static Item infusedAmethystBoots = (new RioVArmor(Config.addItem("Infused Amethyst Boots"), InfusedAmethystArmorMaterial, render, 3, "amethyst", true)).setUnlocalizedName("infusedAmethystBoots");
	public static Item auntunMinionHelmet = (new RioVArmor(Config.addItem("Aun'Tun Minion Helmet"), AunTunArmorMaterial, render, 0, "auntunminion", false)).setUnlocalizedName("auntunminionHelmet");
	public static Item auntunMinionChestplate = (new RioVArmor(Config.addItem("Aun'Tun Minion Chestplate"), AunTunArmorMaterial, render, 1, "auntunminion", false)).setUnlocalizedName("auntunminionChestplate");
	public static Item auntunMinionLeggings = (new RioVArmor(Config.addItem("Aun'Tun Minion Leggings"), AunTunArmorMaterial, render, 2, "auntunminion", false)).setUnlocalizedName("auntunminionLeggings");
	public static Item auntunMinionBoots = (new RioVArmor(Config.addItem("Aun'Tun Minion Boots"), AunTunArmorMaterial, render, 3, "auntunminion", false)).setUnlocalizedName("auntunminionBoots");
	public static Item garnetHelmet = (new RioVArmor(Config.addItem("Garnet Helmet"), GarnetArmorMaterial, render, 0, "garnet", false)).setUnlocalizedName("garnetHelmet");
	public static Item garnetChestplate = (new RioVArmor(Config.addItem("Garnet Chestplate"), GarnetArmorMaterial, render, 1, "garnet", false)).setUnlocalizedName("garnetChestplate");
	public static Item garnetLeggings = (new RioVArmor(Config.addItem("Garnet Leggings"), GarnetArmorMaterial, render, 2, "garnet", false)).setUnlocalizedName("garnetLeggings");
	public static Item garnetBoots = (new RioVArmor(Config.addItem("Garnet Boots"), GarnetArmorMaterial, render, 3, "garnet", false)).setUnlocalizedName("garnetBoots");
	public static Item mythrilHelmet = (new RioVArmor(Config.addItem("Mythril Helmet"), MythrilArmorMaterial, render, 0, "mythril", false)).setUnlocalizedName("mythrilHelmet");
	public static Item mythrilChestplate = (new RioVArmor(Config.addItem("Mythril Chestplate"), MythrilArmorMaterial, render, 1, "mythril", false)).setUnlocalizedName("mythrilChestplate");
	public static Item mythrilLeggings = (new RioVArmor(Config.addItem("Mythril Leggings"), MythrilArmorMaterial, render, 2, "mythril", false)).setUnlocalizedName("mythrilLeggings");
	public static Item mythrilBoots = (new RioVArmor(Config.addItem("Mythril Boots"), MythrilArmorMaterial, render, 3, "mythril", false)).setUnlocalizedName("mythrilBoots");
	public static Item dragonHelmet = (new RioVArmor(Config.addItem("Dragon Helmet"), DragonArmorMaterial, render, 0, "dragon", false)).setUnlocalizedName("dragonHelmet");
	public static Item dragonChestplate = (new ItemDragonChestplate(Config.addItem("Dragon Chestplate"), DragonArmorMaterial, render, 1, "dragon", false)).setUnlocalizedName("dragonChestplate");
	public static Item dragonLeggings = (new RioVArmor(Config.addItem("Dragon Leggings"), DragonArmorMaterial, render, 2, "dragon", false)).setUnlocalizedName("dragonLeggings");
	public static Item dragonBoots = (new RioVArmor(Config.addItem("Dragon Boots"), DragonArmorMaterial, render, 3, "dragon", false)).setUnlocalizedName("dragonBoots");
	public static Item amethystSword = (new RioVWeapon(Config.addItem("Amethyst Sword"), Amethyst, false)).setUnlocalizedName("amethystSword");
	public static Item infusedAmethystSword = (new RioVWeapon(Config.addItem("Infused Amethyst Sword"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystSword");
	public static Item onyxSword = (new RioVWeapon(Config.addItem("Onyx Sword"), Onyx, false)).setUnlocalizedName("onyxSword");
	public static Item infusedOnyxSword = (new RioVWeapon(Config.addItem("Infused Onyx Sword"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxSword");
	public static Item daetoriSword = (new RioVWeapon(Config.addItem("Daetori's Sword"), Daetori, false)).setUnlocalizedName("daetoriSword");
	public static Item sorrowSword = (new RioVWeapon(Config.addItem("Sorrow Sword"), Sorrow, false)).setUnlocalizedName("sorrowSword");
	public static Item axeOfAunTun = (new RioVWeapon(Config.addItem("Axe of Aun'Tun"), AxeOfAunTun, false)).setUnlocalizedName("axeOfAunTun");
	public static Item dragonSword = (new RioVWeapon(Config.addItem("Sharpened Slate Handaxe"), Dragon, false)).setUnlocalizedName("dragonSword");
	public static Item onyxPickaxe = (new RioVPickaxe(Config.addItem("Onyx Pickaxe"), Onyx, false)).setUnlocalizedName("onyxPickaxe");
	public static Item onyxAxe = (new RioVAxe(Config.addItem("Onyx Axe"), Onyx, false)).setUnlocalizedName("onyxAxe");
	public static Item onyxShovel = (new RioVSpade(Config.addItem("Onyx Shovel"), Onyx, false)).setUnlocalizedName("onyxShovel");
	public static Item amethystPickaxe = (new RioVPickaxe(Config.addItem("Amethyst Pickaxe"), Amethyst, false)).setUnlocalizedName("amethystPickaxe");
	public static Item amethystAxe = (new RioVAxe(Config.addItem("Amethyst Axe"), Amethyst, false)).setUnlocalizedName("amethystAxe");
	public static Item amethystShovel = (new RioVSpade(Config.addItem("Amethyst Shovel"), Amethyst, false)).setUnlocalizedName("amethystShovel");
	public static Item infusedAmethystPickaxe = (new RioVPickaxe(Config.addItem("Infused Amethyst Pickaxe"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystPickaxe");
	public static Item infusedAmethystAxe = (new RioVAxe(Config.addItem("Infused Amethyst Axe"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystAxe");
	public static Item infusedAmethystShovel = (new RioVSpade(Config.addItem("Infused Amethyst Shovel"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystShovel");
	public static Item infusedOnyxPickaxe = (new RioVPickaxe(Config.addItem("Infused Onyx Pickaxe"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxPickaxe");
	public static Item infusedOnyxAxe = (new RioVAxe(Config.addItem("Infused Onyx Axe"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxAxe");
	public static Item infusedOnyxShovel = (new RioVSpade(Config.addItem("Infused Onyx Shovel"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxShovel");
	public static Item agonitePickaxe = (new RioVPickaxe(Config.addItem("Agonite Pickaxe"), Agonite, false)).setUnlocalizedName("agonitePickaxe");
	public static Item dragonPickaxe = (new RioVPickaxe(Config.addItem("Dragon Pickaxe"), Dragon, false)).setUnlocalizedName("dragonPickaxe");
	public static Item dragonAxe = (new RioVAxe(Config.addItem("Dragon Axe"), Dragon, false)).setUnlocalizedName("dragonAxe");
	public static Item dragonShovel = (new RioVSpade(Config.addItem("Dragon Shovel"), Dragon, false)).setUnlocalizedName("dragonShovel");
	public static Item amethyst = (new RioVItem(Config.addItem("Amethyst"))).setUnlocalizedName("amethyst");
	public static Item onyx = (new RioVItem(Config.addItem("Onyx"))).setUnlocalizedName("onyx");
	public static Item blackBone = (new RioVItem(Config.addItem("Black Bone"))).setUnlocalizedName("blackBone");
	public static Item orb = (new RioVItem(Config.addItem("Orb"))).setUnlocalizedName("orb");
	public static Item slateFragment = (new RioVItem(Config.addItem("Slate Fragment"))).setUnlocalizedName("slateFragment");
	public static Item garnet = (new RioVItem(Config.addItem("Garnet"))).setUnlocalizedName("garnet");
	public static Item agonite = (new RioVItem(Config.addItem("Agonite"))).setUnlocalizedName("agonite");
	public static Item darkMatter = (new RioVExplosives(Config.addItem("Dark Matter"))).setUnlocalizedName("darkMatter");
	public static Item mythrilIngot = (new RioVItem(Config.addItem("Mythril Ingot"))).setUnlocalizedName("mythrilIngot");
	public static Item dragonSoul = (new RioVItem(Config.addItem("Dragon Soul Gem"))).setUnlocalizedName("dragonSoul");
	public static Item nironite = (new RioVItem(Config.addItem("Nironite"))).setUnlocalizedName("nironite");
	public static Item burnedQuartz = (new RioVItem(Config.addItem("Black Quartz"))).setUnlocalizedName("burnedQuartz");
	public static Item vulron = (new RioVItem(Config.addItem("Vulron"))).setUnlocalizedName("vulron");
	public static Item darknessArrow = (new RioVItem(Config.addItem("Darkness Arrow"))).setUnlocalizedName("darknessArrow");
	public static Item UnfusedaxeOfAunTun = (new RioVWeapon(Config.addItem("Unfused Axe of Aun'Tun"), Sapphire, false)).setUnlocalizedName("UnfusedaxeOfAunTun");
	public static Item HalfFusedaxeOfAunTun = (new RioVWeapon(Config.addItem("Half Fused Axe of Aun'Tun"), Sapphire, false)).setUnlocalizedName("HalfFusedaxeOfAunTun");
	public static Item ambrosia = (new RioVConsumable(Config.addItem("Ambrosia"), 6, 0, false)).setUnlocalizedName("ambrosia");
	public static Item tomato = (new RioVConsumable(Config.addItem("Tomato"), 5, 0, false)).setUnlocalizedName("tomato");
	public static Item cookedHorseMeat = (new RioVConsumable(Config.addItem("Cooked Horse Meat"), 5, 0, false)).setUnlocalizedName("cookedHorseMeat");
	public static Item horseMeat = (new RioVConsumable(Config.addItem("Horse Meat"), 3, 0, false)).setUnlocalizedName("horseMeat");
	public static Item blackDurii = (new RioVConsumable(Config.addItem("Black Durii"), 3, 0, false)).setUnlocalizedName("blackDurii");
	public static Item baseCrystal = (new RioVItem(Config.addItem("Base Crystal"))).setUnlocalizedName("baseCrystal");
	public static Item terronCrystal = (new RioVSummoners(Config.addItem("Terron Crystal"))).setUnlocalizedName("terronCrystal");
	public static Item demonAngelCrystal = (new RioVSummoners(Config.addItem("Demon Angel Crystal"))).setUnlocalizedName("demonAngelCrystal");
	public static Item auntunSummoner = (new RioVSummoners(Config.addItem("Aun'Tun Summoner"))).setUnlocalizedName("auntunSummoner");
	public static Item khuulisScythe = (new RioVWeapon(Config.addItem("Khuuli's Scythe"), Onyx, false)).setUnlocalizedName("khuulisScythe");
	public static Item bowOfWurTun = (new ItemBowOfWurTun(Config.addItem("Bow of Wur'Tun"))).setUnlocalizedName("bowOfWurTun");
	public static Item wineGlass = (new RioVItem(Config.addItem("Wine Glass"))).setUnlocalizedName("wineGlass");
	public static Item potionGlass = (new RioVPotions(Config.addItem("Potion Glass"), 0)).setUnlocalizedName("potionGlass");
	public static Item grapes = (new RioVConsumable(Config.addItem("Grapes"), 3, 0, true)).setUnlocalizedName("grapes");
	public static Item wine = (new RioVDrinkable(Config.addItem("Wine"), 2, 0, true)).setUnlocalizedName("wine");
	public static Item greenApple = (new RioVConsumable(Config.addItem("Green Apple"), 4, 0, true)).setUnlocalizedName("greenApple");
	public static Item spicedWine = (new RioVDrinkable(Config.addItem("Spiced Wine"), 3, 0, true)).setUnlocalizedName("spicedWine");
	public static Item pepper = (new RioVConsumable(Config.addItem("Pepper"), 2, 0, true)).setUnlocalizedName("pepper");
	public static Item pepperSpices = (new RioVConsumable(Config.addItem("Pepper Spices"), 1, 0, true)).setUnlocalizedName("pepperSpices");
	public static Item sapphire = (new RioVItem(Config.addItem("Sapphire"))).setUnlocalizedName("sapphire");
	public static Item sapphirePickaxe = (new RioVPickaxe(Config.addItem("Sapphire Pickaxe"), Sapphire, false)).setUnlocalizedName("sapphirePickaxe");
	public static Item sapphireAxe = (new RioVAxe(Config.addItem("Sapphire Axe"), Sapphire, false)).setUnlocalizedName("sapphireAxe");
	public static Item sapphireShovel = (new RioVSpade(Config.addItem("Sapphire Shovel"), Sapphire, false)).setUnlocalizedName("sapphireShovel");
	public static Item sapphireSword = (new RioVWeapon(Config.addItem("Sapphire Sword"), Sapphire, false)).setUnlocalizedName("sapphireSword");
	public static Item sapphireHelmet = (new RioVArmor(Config.addItem("Sapphire Helmet"), SapphireArmorMaterial, render, 0, "sapphire", false)).setUnlocalizedName("sapphireHelmet");
	public static Item sapphireChestplate = (new RioVArmor(Config.addItem("Sapphire Chestplate"), SapphireArmorMaterial, render, 1, "sapphire", false)).setUnlocalizedName("sapphireChestplate");
	public static Item sapphireLeggings = (new RioVArmor(Config.addItem("Sapphire Leggings"), SapphireArmorMaterial, render, 2, "sapphire", false)).setUnlocalizedName("sapphireLeggings");
	public static Item sapphireBoots = (new RioVArmor(Config.addItem("Sapphire Boots"), SapphireArmorMaterial, render, 3, "sapphire", false)).setUnlocalizedName("sapphireBoots");
	public static Item opal = (new RioVItem(Config.addItem("Opal"))).setUnlocalizedName("opal");
	public static Item topaz = (new RioVItem(Config.addItem("Mystic Topaz"))).setUnlocalizedName("topaz");
	public static Item topazPickaxe = (new RioVPickaxe(Config.addItem("Mystic Topaz Pickaxe"), Topaz, false)).setUnlocalizedName("topazPickaxe");
	public static Item topazAxe = (new RioVAxe(Config.addItem("Mystic Topaz Axe"), Topaz, false)).setUnlocalizedName("topazAxe");
	public static Item topazShovel = (new RioVSpade(Config.addItem("Mystic Topaz Shovel"), Topaz, false)).setUnlocalizedName("topazShovel");
	public static Item topazSword = (new RioVWeapon(Config.addItem("Mystic Topaz Sword"), Topaz, false)).setUnlocalizedName("topazSword");
	public static Item topazHelmet = (new RioVArmor(Config.addItem("Mystic Topaz Helmet"), TopazArmorMaterial, render, 0, "topaz", false)).setUnlocalizedName("topazHelmet");
	public static Item topazChestplate = (new RioVArmor(Config.addItem("Mystic Topaz Chestplate"), TopazArmorMaterial, render, 1, "topaz", false)).setUnlocalizedName("topazChestplate");
	public static Item topazLeggings = (new RioVArmor(Config.addItem("Mystic Topaz Leggings"), TopazArmorMaterial, render, 2, "topaz", false)).setUnlocalizedName("topazLeggings");
	public static Item topazBoots = (new RioVArmor(Config.addItem("Mystic Topaz Boots"), TopazArmorMaterial, render, 3, "topaz", false)).setUnlocalizedName("topazBoots");
	public static Item manchet = (new RioVConsumable(Config.addItem("Manchet"), 6, 0, true)).setUnlocalizedName("manchet");
	public static Item cherry = (new RioVConsumable(Config.addItem("Cherry"), 8, 0, true)).setUnlocalizedName("cherry");
	public static Item vaiziCurrency = (new RioVItem(Config.addItem("Vaizi"))).setUnlocalizedName("vaiziCurrency");
	public static Item galokinHelmet = (new RioVArmor(Config.addItem("Galokin Helmet"), GalokinArmorMaterial, render, 0, "galokin", false)).setUnlocalizedName("galokinHelmet");
	public static Item galokinChestplate = (new RioVArmor(Config.addItem("Galokin Chestplate"), GalokinArmorMaterial, render, 1, "galokin", false)).setUnlocalizedName("galokinChestplate");
	public static Item galokinLeggings = (new RioVArmor(Config.addItem("Galokin Leggings"), GalokinArmorMaterial, render, 2, "galokin", false)).setUnlocalizedName("galokinLeggings");
	public static Item galokinBoots = (new RioVArmor(Config.addItem("Galokin Boots"), GalokinArmorMaterial, render, 3, "galokin", false)).setUnlocalizedName("galokinBoots");
	public static Item galokinSword = (new RioVWeapon(Config.addItem("Galokin Sword"), Galokin, false)).setUnlocalizedName("galokinSword");
	public static Item galokinCrystal = (new RioVItem(Config.addItem("Galokin Crystal"))).setUnlocalizedName("galokinCrystal");
	public static Item clothOfMagic = (new RioVItem(Config.addItem("Cloth of Magic"))).setUnlocalizedName("clothOfMagic");
	public static Item magickaHelmet = (new RioVArmor(Config.addItem("Magicka Helmet"), EnumArmorMaterial.CHAIN, render, 0, "magic", true)).setUnlocalizedName("magickaHelmet");
	public static Item magickaChestplate = (new RioVArmor(Config.addItem("Magicka Chestplate"), EnumArmorMaterial.CHAIN, render, 1, "magic", true)).setUnlocalizedName("magickaChestplate");
	public static Item magickaLeggings = (new RioVArmor(Config.addItem("Magicka Leggings"), EnumArmorMaterial.CHAIN, render, 2, "magic", true)).setUnlocalizedName("magickaLeggings");
	public static Item magickaBoots = (new RioVArmor(Config.addItem("Magicka Boots"), EnumArmorMaterial.CHAIN, render, 3, "magic", true)).setUnlocalizedName("magickaBoots");
	public static Item theDarknessCrystal = (new RioVSummoners(Config.addItem("The Darkness Crystal"))).setUnlocalizedName("theDarknessCrystal");
	public static Item infusedSapphirePickaxe = (new RioVPickaxe(Config.addItem("Infused Sapphire Pickaxe"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphirePickaxe");
	public static Item infusedSapphireAxe = (new RioVAxe(Config.addItem("Infused Sapphire Axe"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireAxe");
	public static Item infusedSapphireShovel = (new RioVSpade(Config.addItem("Infused Sapphire Shovel"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireShovel");
	public static Item infusedSapphireSword = (new RioVWeapon(Config.addItem("Infused Sapphire Sword"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireSword");
	public static Item infusedSapphireHelmet = (new RioVArmor(Config.addItem("Infused Sapphire Helmet"), InfusedSapphireArmorMaterial, render, 0, "sapphire", true)).setUnlocalizedName("infusedSapphireHelmet");
	public static Item infusedSapphireChestplate = (new RioVArmor(Config.addItem("Infused Sapphire Chestplate"), InfusedSapphireArmorMaterial, render, 1, "sapphire", true)).setUnlocalizedName("infusedSapphireChestplate");
	public static Item infusedSapphireLeggings = (new RioVArmor(Config.addItem("Infused Sapphire Leggings"), InfusedSapphireArmorMaterial, render, 2, "sapphire", true)).setUnlocalizedName("infusedSapphireLeggings");
	public static Item infusedSapphireBoots = (new RioVArmor(Config.addItem("Infused Sapphire Boots"), InfusedSapphireArmorMaterial, render, 3, "sapphire", true)).setUnlocalizedName("infusedSapphireBoots");
	public static Item infusedTopazPickaxe = (new RioVPickaxe(Config.addItem("Infused Mystic Topaz Pickaxe"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazPickaxe");
	public static Item infusedTopazAxe = (new RioVAxe(Config.addItem("Infused Mystic Topaz Axe"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazAxe");
	public static Item infusedTopazShovel = (new RioVSpade(Config.addItem("Infused Mystic Topaz Shovel"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazShovel");
	public static Item infusedTopazSword = (new RioVWeapon(Config.addItem("Infused Mystic Topaz Sword"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazSword");
	public static Item infusedTopazHelmet = (new RioVArmor(Config.addItem("Infused Mystic Topaz Helmet"), InfusedTopazArmorMaterial, render, 0, "topaz", true)).setUnlocalizedName("infusedTopazHelmet");
	public static Item infusedTopazChestplate = (new RioVArmor(Config.addItem("Infused Mystic Topaz Chestplate"), InfusedTopazArmorMaterial, render, 1, "topaz", true)).setUnlocalizedName("infusedTopazChestplate");
	public static Item infusedTopazLeggings = (new RioVArmor(Config.addItem("Infused Mystic Topaz Leggings"), InfusedTopazArmorMaterial, render, 2, "topaz", true)).setUnlocalizedName("infusedTopazLeggings");
	public static Item infusedTopazBoots = (new RioVArmor(Config.addItem("Infused Mystic Topaz Boots"), InfusedTopazArmorMaterial, render, 3, "topaz", true)).setUnlocalizedName("infusedTopazBoots");
	public static Item ingotOfFlame = (new RioVItem(Config.addItem("Ingot of Flame"))).setUnlocalizedName("ingotOfFlame");
	public static Item swordOfFlame = (new RioVWeapon(Config.addItem("Sword of Flame"), Flame, false)).setUnlocalizedName("swordOfFlame");
	public static Item purpleFeather = (new RioVItem(Config.addItem("Purple Feather"))).setUnlocalizedName("purpleFeather");
	public static Item helmetOfFlame = (new RioVArmor(Config.addItem("Helmet of Flame"), FlameArmorMaterial, render, 0, "flame", false)).setUnlocalizedName("helmetOfFlame");
	public static Item chestplateOfFlame = (new RioVArmor(Config.addItem("Chestplate of Flame"), FlameArmorMaterial, render, 1, "flame", false)).setUnlocalizedName("chestplateOfFlame");
	public static Item leggingsOfFlame = (new RioVArmor(Config.addItem("Leggings of Flame"), FlameArmorMaterial, render, 2, "flame", false)).setUnlocalizedName("leggingsOfFlame");
	public static Item bootsOfFlame = (new RioVArmor(Config.addItem("Boots of Flame"), FlameArmorMaterial, render, 3, "flame", false)).setUnlocalizedName("bootsOfFlame");
	public static Item infusedDragonHelmet = (new RioVArmor(Config.addItem("Infused Dragon Helmet"), InfusedDragonArmorMaterial, render, 0, "dragon", true)).setUnlocalizedName("infusedDragonHelmet");
	public static Item infusedDragonChestplate = (new ItemDragonChestplate(Config.addItem("Infused Dragon Chestplate"), InfusedDragonArmorMaterial, render, 1, "dragon", true)).setUnlocalizedName("infusedDragonChestplate");
	public static Item infusedDragonLeggings = (new RioVArmor(Config.addItem("Infused Dragon Leggings"), InfusedDragonArmorMaterial, render, 2, "dragon", true)).setUnlocalizedName("infusedDragonLeggings");
	public static Item infusedDragonBoots = (new RioVArmor(Config.addItem("Infused Dragon Boots"), InfusedDragonArmorMaterial, render, 3, "dragon", true)).setUnlocalizedName("infusedDragonBoots");
	public static Item infusedDragonSword = (new RioVWeapon(Config.addItem("Infused Dragon Sword"), InfusedDragon, true)).setUnlocalizedName("infusedDragonSword");
	public static Item infusedDragonPickaxe = (new RioVPickaxe(Config.addItem("Infused Dragon Pickaxe"), InfusedDragon, true)).setUnlocalizedName("infusedDragonPickaxe");
	public static Item infusedDragonAxe = (new RioVAxe(Config.addItem("Infused Dragon Axe"), InfusedDragon, true)).setUnlocalizedName("infusedDragonAxe");
	public static Item infusedDragonShovel = (new RioVSpade(Config.addItem("Infused Dragon Shovel"), InfusedDragon, true)).setUnlocalizedName("infusedDragonShovel");
	public static Item enforcedBowOfWurTun = (new ItemEnforcedBowOfWurTun(Config.addItem("Enforced Bow of Wur'Tun"))).setUnlocalizedName("enforcedbowOfWurTun");
	public static Item blindonite = (new RioVItem(Config.addItem("Blindonite"))).setUnlocalizedName("blindonite");
	public static Item blindOasisActivator = (new RioVActivators(Config.addItem("Blind Oasis Activator"))).setUnlocalizedName("blindOasisActivator");
	public static Item tefHelmet = (new RioVArmor(Config.addItem("Tef Helmet"), FlameArmorMaterial, render, 0, "tef", false)).setUnlocalizedName("tefHelmet");
	public static Item tefChestplate = (new RioVArmor(Config.addItem("Tef Chestplate"), FlameArmorMaterial, render, 1, "tef", false)).setUnlocalizedName("tefChestplate");
	public static Item tefLeggings = (new RioVArmor(Config.addItem("Tef Leggings"), FlameArmorMaterial, render, 2, "tef", false)).setUnlocalizedName("tefLeggings");
	public static Item tefBoots = (new RioVArmor(Config.addItem("Tef Boots"), FlameArmorMaterial, render, 3, "tef", false)).setUnlocalizedName("tefBoots");
	public static Item tefCrystal = (new RioVSummoners(Config.addItem("Tef Crystal"))).setUnlocalizedName("tefCrystal");
	public static Item blindoniteHelmet = (new RioVArmor(Config.addItem("Blindonite Helmet"), BlindoniteArmorMaterial, render, 0, "blindonite", false)).setUnlocalizedName("blindoniteHelmet");
	public static Item blindoniteChestplate = (new RioVArmor(Config.addItem("Blindonite Chestplate"), BlindoniteArmorMaterial, render, 1, "blindonite", false)).setUnlocalizedName("blindoniteChestplate");
	public static Item blindoniteLeggings = (new RioVArmor(Config.addItem("Blindonite Leggings"), BlindoniteArmorMaterial, render, 2, "blindonite", false)).setUnlocalizedName("blindoniteLeggings");
	public static Item blindoniteBoots = (new RioVArmor(Config.addItem("Blindonite Boots"), BlindoniteArmorMaterial, render, 3, "blindonite", false)).setUnlocalizedName("blindoniteBoots");
	public static Item blindonitePickaxe = (new RioVPickaxe(Config.addItem("Blindonite Pickaxe"), Blindonite, false)).setUnlocalizedName("blindonitePickaxe");
	public static Item blindoniteAxe = (new RioVAxe(Config.addItem("Blindonite Axe"), Blindonite, false)).setUnlocalizedName("blindoniteAxe");
	public static Item blindoniteShovel = (new RioVSpade(Config.addItem("Blindonite Shovel"), Blindonite, false)).setUnlocalizedName("blindoniteShovel");
	public static Item blindoniteSword = (new RioVWeapon(Config.addItem("Blindonite Sword"), Blindonite, false)).setUnlocalizedName("blindoniteSword");
	public static Item infusedBlindoniteHelmet = (new RioVArmor(Config.addItem("Infused Blindonite Helmet"), InfusedBlindoniteArmorMaterial, render, 0, "blindonite", true)).setUnlocalizedName("infusedBlindoniteHelmet");
	public static Item infusedBlindoniteChestplate = (new RioVArmor(Config.addItem("Infused Blindonite Chestplate"), InfusedBlindoniteArmorMaterial, render, 1, "blindonite", true)).setUnlocalizedName("infusedBlindoniteChestplate");
	public static Item infusedBlindoniteLeggings = (new RioVArmor(Config.addItem("Infused Blindonite Leggings"), InfusedBlindoniteArmorMaterial, render, 2, "blindonite", true)).setUnlocalizedName("infusedBlindoniteLeggings");
	public static Item infusedBlindoniteBoots = (new RioVArmor(Config.addItem("Infused Blindonite Boots"), InfusedBlindoniteArmorMaterial, render, 3, "blindonite", true)).setUnlocalizedName("infusedBlindoniteBoots");
	public static Item infusedBlindonitePickaxe = (new RioVPickaxe(Config.addItem("Infused Blindonite Pickaxe"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindonitePickaxe");
	public static Item infusedBlindoniteAxe = (new RioVAxe(Config.addItem("Infused Blindonite Axe"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteAxe");
	public static Item infusedBlindoniteShovel = (new RioVSpade(Config.addItem("Infused Blindonite Shovel"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteShovel");
	public static Item infusedBlindoniteSword = (new RioVWeapon(Config.addItem("Infused Blindonite Sword"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteSword");
	public static Item vaerynActivator = (new RioVActivators(Config.addItem("Vaeryn Activator"))).setUnlocalizedName("vaerynActivator");
	public static Item glimmerwoodSticks = (new RioVItem(Config.addItem("Glimmerwood Sticks"))).setUnlocalizedName("glimmerwoodSticks");
	public static Item glimmerwoodPickaxe = (new RioVPickaxe(Config.addItem("Glimmerwood Pickaxe"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodPickaxe");
	public static Item glimmerwoodAxe = (new RioVAxe(Config.addItem("Glimmerwood Axe"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodAxe");
	public static Item glimmerwoodShovel = (new RioVSpade(Config.addItem("Glimmerwood Shovel"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodShovel");
	public static Item glimmerwoodSword = (new RioVWeapon(Config.addItem("Glimmerwood Sword"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodSword");
	public static Item blueMagicApple = (new RioVConsumable(Config.addItem("Magical Blue Apple"), 8, 0, true)).setUnlocalizedName("blueApple");
	public static Item vraviniteBow = (new ItemVraviniteBow(Config.addItem("Vravinite Bow"))).setUnlocalizedName("vraviniteBow");
	public static Item vraviniteArrow = (new RioVItem(Config.addItem("Vravinite Arrow"))).setUnlocalizedName("vraviniteArrow");
	public static Item vravinite = (new RioVItem(Config.addItem("Vravinite"))).setUnlocalizedName("vravinite");
	public static Item vraviniteHelmet = (new RioVArmor(Config.addItem("Vravinite Helmet"), VraviniteArmorMaterial, render, 0, "vravinite", false)).setUnlocalizedName("vraviniteHelmet");
	public static Item vraviniteChestplate = (new RioVArmor(Config.addItem("Vravinite Chestplate"), VraviniteArmorMaterial, render, 1, "vravinite", false)).setUnlocalizedName("vraviniteChestplate");
	public static Item vraviniteLeggings = (new RioVArmor(Config.addItem("Vravinite Leggings"), VraviniteArmorMaterial, render, 2, "vravinite", false)).setUnlocalizedName("vraviniteLeggings");
	public static Item vraviniteBoots = (new RioVArmor(Config.addItem("Vravinite Boots"), VraviniteArmorMaterial, render, 3, "vravinite", false)).setUnlocalizedName("vraviniteBoots");
	public static Item vravinitePickaxe = (new RioVPickaxe(Config.addItem("Vravinite Pickaxe"), Vravinite, false)).setUnlocalizedName("vravinitePickaxe");
	public static Item vraviniteAxe = (new RioVAxe(Config.addItem("Vravinite Axe"), Vravinite, false)).setUnlocalizedName("vraviniteAxe");
	public static Item vraviniteShovel = (new RioVSpade(Config.addItem("Vravinite Shovel"), Vravinite, false)).setUnlocalizedName("vraviniteShovel");
	public static Item vraviniteSword = (new RioVWeapon(Config.addItem("Vravinite Sword"), Vravinite, false)).setUnlocalizedName("vraviniteSword");
	public static Item glimmerwoodDoorItem = (new RioVDoor(Config.addItem("Glimmerwood Door Item"), Material.wood)).setUnlocalizedName("glimmerwoodDoorItem");
	public static Item flamonorActivator = (new RioVActivators(Config.addItem("Flamonor Activator"))).setUnlocalizedName("flamonorActivator");
	public static Item drakiuz = (new RioVItem(Config.addItem("Drakiuz"))).setUnlocalizedName("drakiuz");
	public static Item fireballWand = (new RioVWand(Config.addItem("Fireball Wand"), 0, 1, 4)).setUnlocalizedName("fireballWand");
	public static Item cherryBlossomDoorItem = (new RioVDoor(Config.addItem("Cherry Blossom Door Item"), Material.wood)).setUnlocalizedName("cherryBlossomDoorItem");
	public static Item cherryBlossomSticks = (new RioVItem(Config.addItem("Cherry Blossom Sticks"))).setUnlocalizedName("cherryBlossomSticks");
	public static Item cherryBlossomPickaxe = (new RioVPickaxe(Config.addItem("Cherry Blossom Pickaxe"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomPickaxe");
	public static Item cherryBlossomAxe = (new RioVAxe(Config.addItem("Cherry Blossom Axe"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomAxe");
	public static Item cherryBlossomShovel = (new RioVSpade(Config.addItem("Cherry Blossom Shovel"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomShovel");
	public static Item cherryBlossomSword = (new RioVWeapon(Config.addItem("Cherry Blossom Sword"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomSword");
	public static Item glimmerwoodBucket = (new RioVBucket(Config.addItem("Glimmerwood Bucket"), 0)).setUnlocalizedName("glimmerwoodBucket").setMaxStackSize(16);
	public static Item glimmerwoodBucketWater = (new RioVBucket(Config.addItem("Glimmerwood Bucket Water"), Block.waterMoving.blockID)).setUnlocalizedName("glimmerwoodBucketWater").setContainerItem(glimmerwoodBucket);
	public static Item glimmerwoodBucketLava = (new RioVBucket(Config.addItem("Glimmerwood Bucket Lava"), Block.lavaMoving.blockID)).setUnlocalizedName("glimmerwoodBucketLava").setContainerItem(glimmerwoodBucket);
	public static Item bloodBucket = (new RioVBucket(Config.addItem("Blood Bucket"), 0)).setUnlocalizedName("bloodBucket").setMaxStackSize(16);
	public static Item bloodBucketWater = (new RioVBucket(Config.addItem("Blood Bucket Water"), Block.waterMoving.blockID)).setUnlocalizedName("bloodBucketWater").setContainerItem(bloodBucket);
	public static Item bloodBucketLava = (new RioVBucket(Config.addItem("Blood Bucket Lava"), Block.lavaMoving.blockID)).setUnlocalizedName("bloodBucketLava").setContainerItem(bloodBucket);
	public static Item potionGlassSanctuatite = (new RioVPotions(Config.addItem("Potion Glass Sanctuatite"), Blocks.sanctuatiteMoving.blockID)).setUnlocalizedName("potionGlassSanctuatite");
	public static Item sanctuatiteActivator = (new RioVActivators(Config.addItem("Sanctuatite Activator"))).setUnlocalizedName("sanctuatiteActivator");
	public static Item skywoodDoorItem = (new RioVDoor(Config.addItem("Skywood Door Item"), Material.wood)).setUnlocalizedName("skywoodDoorItem");
	public static Item bloodDoorItem = (new RioVDoor(Config.addItem("Blood Door Item"), Material.wood)).setUnlocalizedName("bloodDoorItem");
	public static Item skywoodSticks = (new RioVItem(Config.addItem("Skywood Sticks"))).setUnlocalizedName("skywoodSticks");
	public static Item skywoodPickaxe = (new RioVPickaxe(Config.addItem("Skywood Pickaxe"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodPickaxe");
	public static Item skywoodAxe = (new RioVAxe(Config.addItem("Skywood Axe"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodAxe");
	public static Item skywoodShovel = (new RioVSpade(Config.addItem("Skywood Shovel"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodShovel");
	public static Item skywoodSword = (new RioVWeapon(Config.addItem("Skywood Sword"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodSword");
	public static Item bloodSticks = (new RioVItem(Config.addItem("Blood Sticks"))).setUnlocalizedName("bloodSticks");
	public static Item bloodPickaxe = (new RioVPickaxe(Config.addItem("Blood Pickaxe"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodPickaxe");
	public static Item bloodAxe = (new RioVAxe(Config.addItem("Blood Axe"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodAxe");
	public static Item bloodShovel = (new RioVSpade(Config.addItem("Blood Shovel"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodShovel");
	public static Item bloodSword = (new RioVWeapon(Config.addItem("Blood Sword"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodSword");
	public static Item sanctuaryStonePickaxe = (new RioVPickaxe(Config.addItem("Sanctuary Stone Pickaxe"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStonePickaxe");
	public static Item sanctuaryStoneAxe = (new RioVAxe(Config.addItem("Sanctuary Stone Axe"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneAxe");
	public static Item sanctuaryStoneShovel = (new RioVSpade(Config.addItem("Sanctuary Stone Shovel"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneShovel");
	public static Item sanctuaryStoneSword = (new RioVWeapon(Config.addItem("Sanctuary Stone Sword"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneSword");
	public static Item aleris = (new RioVItem(Config.addItem("Aleris"))).setUnlocalizedName("aleris");
	public static Item alerisHelmet = (new RioVArmor(Config.addItem("Aleris Helmet"), AlerisArmorMaterial, render, 0, "aleris", false)).setUnlocalizedName("alerisHelmet");
	public static Item alerisChestplate = (new RioVArmor(Config.addItem("Aleris Chestplate"), AlerisArmorMaterial, render, 1, "aleris", false)).setUnlocalizedName("alerisChestplate");
	public static Item alerisLeggings = (new RioVArmor(Config.addItem("Aleris Leggings"), AlerisArmorMaterial, render, 2, "aleris", false)).setUnlocalizedName("alerisLeggings");
	public static Item alerisBoots = (new RioVArmor(Config.addItem("Aleris Boots"), AlerisArmorMaterial, render, 3, "aleris", false)).setUnlocalizedName("alerisBoots");
	public static Item alerisPickaxe = (new RioVPickaxe(Config.addItem("Aleris Pickaxe"), Aleris, false)).setUnlocalizedName("alerisPickaxe");
	public static Item alerisAxe = (new RioVAxe(Config.addItem("Aleris Axe"), Aleris, false)).setUnlocalizedName("alerisStoneAxe");
	public static Item alerisShovel = (new RioVSpade(Config.addItem("Aleris Shovel"), Aleris, false)).setUnlocalizedName("alerisShovel");
	public static Item alerisSword = (new RioVWeapon(Config.addItem("Aleris Sword"), Aleris, false)).setUnlocalizedName("alerisSword");
	public static Item onyxShield = (new RioVShield(Config.addItem("Onyx Shield"), Onyx, 1)).setUnlocalizedName("onyxShield");
	public static Item amethystShield = (new RioVShield(Config.addItem("Amethyst Shield"), Amethyst, 1)).setUnlocalizedName("amethystShield");
	public static Item vraviniteShield = (new RioVShield(Config.addItem("Vravinite Shield"), Vravinite, 5)).setUnlocalizedName("vraviniteShield");
	public static Item sapphireShield = (new RioVShield(Config.addItem("Sapphire Shield"), Sapphire, 1)).setUnlocalizedName("sapphireShield");
	public static Item topazShield = (new RioVShield(Config.addItem("Mystic Topaz Shield"), Topaz, 1)).setUnlocalizedName("topazShield");
	public static Item shieldOfFlame = (new RioVShield(Config.addItem("Shield of Flame"), Flame, 2)).setUnlocalizedName("shieldOfFlame");
	public static Item blindoniteShield = (new RioVShield(Config.addItem("Blindonite Shield"), Blindonite, 2)).setUnlocalizedName("blindoniteShield");
	public static Item woodenShield = (new RioVShield(Config.addItem("Wooden Shield"), EnumToolMaterial.WOOD, 0)).setUnlocalizedName("woodenShield");
	public static Item stoneShield = (new RioVShield(Config.addItem("Stone Shield"), EnumToolMaterial.STONE, 1)).setUnlocalizedName("stoneShield");
	public static Item ironShield = (new RioVShield(Config.addItem("Iron Shield"), EnumToolMaterial.IRON, 2)).setUnlocalizedName("ironShield");
	public static Item goldShield = (new RioVShield(Config.addItem("Gold Shield"), EnumToolMaterial.GOLD, 1)).setUnlocalizedName("goldShield");
	public static Item diamondShield = (new RioVShield(Config.addItem("Diamond Shield"), EnumToolMaterial.EMERALD, 4)).setUnlocalizedName("diamondShield");
	public static Item dragonShield = (new RioVShield(Config.addItem("Dragon Shield"), Dragon, 3)).setUnlocalizedName("dragonShield");
	public static Item auntunShield = (new RioVShield(Config.addItem("Aun'Tun Shield"), AxeOfAunTun, 4)).setUnlocalizedName("auntunShield");
	public static Item mythrilShield = (new RioVShield(Config.addItem("Mythril Shield"), Dragon, 3)).setUnlocalizedName("mythrilShield");
	public static Item galokinShield = (new RioVShield(Config.addItem("Galokin Shield"), Galokin, 2)).setUnlocalizedName("galokinShield");
	public static Item infusedVraviniteHelmet = (new RioVArmor(Config.addItem("Infused Vravinite Helmet"), InfusedVraviniteArmorMaterial, render, 0, "vravinite", true)).setUnlocalizedName("infusedVraviniteHelmet");
	public static Item infusedVraviniteChestplate = (new RioVArmor(Config.addItem("Infused Vravinite Chestplate"), InfusedVraviniteArmorMaterial, render, 1, "vravinite", true)).setUnlocalizedName("infusedVraviniteChestplate");
	public static Item infusedVraviniteLeggings = (new RioVArmor(Config.addItem("Infused Vravinite Leggings"), InfusedVraviniteArmorMaterial, render, 2, "vravinite", true)).setUnlocalizedName("infusedVraviniteLeggings");
	public static Item infusedVraviniteBoots = (new RioVArmor(Config.addItem("Infused Vravinite Boots"), InfusedVraviniteArmorMaterial, render, 3, "vravinite", true)).setUnlocalizedName("infusedVraviniteBoots");
	public static Item infusedVravinitePickaxe = (new RioVPickaxe(Config.addItem("Infused Vravinite Pickaxe"), InfusedVravinite, true)).setUnlocalizedName("infusedVravinitePickaxe");
	public static Item infusedVraviniteAxe = (new RioVAxe(Config.addItem("Infused Vravinite Axe"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteAxe");
	public static Item infusedVraviniteShovel = (new RioVSpade(Config.addItem("Infused Vravinite Shovel"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteShovel");
	public static Item infusedVraviniteSword = (new RioVWeapon(Config.addItem("Infused Vravinite Sword"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteSword");
	public static Item voidHolder = (new RioVVoidHolder(Config.addItem("Void Holder"), 0)).setUnlocalizedName("voidHolder");
	public static Item voidHolderFilled = (new RioVVoidHolder(Config.addItem("Void Holder Filled"), Blocks.voidMoving.blockID)).setUnlocalizedName("voidHolder");
	public static Item berry = (new RioVConsumable(Config.addItem("Berry"), 4, 0, false)).setUnlocalizedName("berry");
	public static Item bambooItem = (new ItemBamboo(Config.addItem("Bamboo Item"), Blocks.bamboo)).setUnlocalizedName("bamboo");
	public static Item bambooPlanks = (new RioVItem(Config.addItem("Bamboo Planks"))).setUnlocalizedName("bambooPlank");
	public static Item blackBerry = (new RioVConsumable(Config.addItem("Blackberry"), 4, 0, false)).setUnlocalizedName("blackBerry");
	public static Item jaavik = (new RioVItem(Config.addItem("Jaavik"))).setUnlocalizedName("jaavik");
	public static Item raspBerry = (new RioVConsumable(Config.addItem("Raspberry"), 3, 0, false)).setUnlocalizedName("raspBerry");
	public static Item bloodBerry = (new RioVConsumable(Config.addItem("Bloodberry"), 6, 0, false)).setUnlocalizedName("bloodBerry");
	public static Item strawBerry = (new RioVConsumable(Config.addItem("Strawberry"), 3, 0, false)).setUnlocalizedName("strawBerry");
	public static Item chain = (new RioVItem(Config.addItem("Chain"))).setUnlocalizedName("chain");
	public static Item smallBag = (new RioVBag(Config.addItem("Small Bag"))).setUnlocalizedName("smallBag");
	public static Item mediumBag = (new RioVBag(Config.addItem("Medium Bag"))).setUnlocalizedName("mediumBag");
	public static Item largeBag = (new RioVBag(Config.addItem("Large Bag"))).setUnlocalizedName("largeBag");
	public static Item sheenBag = (new RioVBag(Config.addItem("Sheen's Bag"))).setUnlocalizedName("sheenBag");
	public static Item scroll = new RioVItem(Config.addItem("Scroll")).setUnlocalizedName("scroll");
	public static Item scrollEverlight = new ItemScrollUsable(Config.addItem("Scroll - Everlight"), 0, 1, 1, level1, false, false, false, false).setUnlocalizedName("scrollEverlight");
	public static Item scrollFireI = new ItemScrollUsable(Config.addItem("Scroll - Fire I"), 0, 1, 5, level1, true, false, false, false).setUnlocalizedName("scrollFireI");
	public static Item scrollFireII = new ItemScrollUsable(Config.addItem("Scroll - Fire II"), 0, 1, 3, level2, true, false, false, false).setUnlocalizedName("scrollFireII");
	public static Item scrollWindI = new ItemScrollUsable(Config.addItem("Scroll - Wind I"), 0, 1, 7, level1, false, false, false, true).setUnlocalizedName("scrollWindI");
	public static Item windElement = (new RioVItem(Config.addItem("Wind Element"))).setUnlocalizedName("windElement");
	public static Item rune = (new ItemRune(Config.addItem("Rune"))).setUnlocalizedName("rune");
	public static Item heart = (new RioVItem(Config.addItem("Heart"))).setUnlocalizedName("heart");
	public static Item supremeAunTunHelmet = (new RioVArmor(Config.addItem("Supreme Aun'Tun Helmet"), SupremeAunTunArmorMaterial, render, 0, "auntunminion", true)).setUnlocalizedName("supremeAunTunHelmet");
	public static Item supremeAunTunChestplate = (new RioVArmor(Config.addItem("Supreme Aun'Tun Chestplate"), SupremeAunTunArmorMaterial, render, 1, "auntunminion", true)).setUnlocalizedName("supremeAunTunChestplate");
	public static Item supremeAunTunLeggings = (new RioVArmor(Config.addItem("Supreme Aun'Tun Leggings"), SupremeAunTunArmorMaterial, render, 2, "auntunminion", true)).setUnlocalizedName("supremeAunTunLeggings");
	public static Item supremeAunTunBoots = (new RioVArmor(Config.addItem("Supreme Aun'Tun Boots"), SupremeAunTunArmorMaterial, render, 3, "auntunminion", true)).setUnlocalizedName("supremeAunTunBoots");
	public static Item ultraAxeOfAunTun = (new RioVWeapon(Config.addItem("Ultra Axe of Aun'Tun"), UltraAxeOfAunTun, true)).setUnlocalizedName("ultraAxeOfAunTun");
	public static Item tasaravHelmet = (new ItemTasaravHelmet(Config.addItem("Tasarav Mallor's Helmet"), AlerisArmorMaterial, render, 0, "tasarav", false)).setUnlocalizedName("tasaravHelmet");
	public static Item tasaravChestplate = (new ItemTasaravChestplate(Config.addItem("Tasarav Mallor's Chestplate"), AlerisArmorMaterial, render, 1, "tasarav", false)).setUnlocalizedName("tasaravChestplate");
	public static Item tasaravLeggings = (new RioVArmor(Config.addItem("Tasarav Mallor's Leggings"), AlerisArmorMaterial, render, 2, "tasarav", false)).setUnlocalizedName("tasaravLeggings");
	public static Item tasaravBoots = (new RioVArmor(Config.addItem("Tasarav Mallor's Boots"), AlerisArmorMaterial, render, 3, "tasarav", false)).setUnlocalizedName("tasaravBoots");
	public static Item tasaravSword = (new RioVWeapon(Config.addItem("Tasarav Mallor's Sword"), Aleris, false)).setUnlocalizedName("tasaravSword");
	public static Item paladinHelmet = (new RioVArmor(Config.addItem("Paladin Helmet"), FlameArmorMaterial, render, 0, "paladin", false)).setUnlocalizedName("paladinHelmet");
	public static Item paladinChestplate = (new RioVArmor(Config.addItem("Paladin Chestplate"), FlameArmorMaterial, render, 1, "paladin", false)).setUnlocalizedName("paladinChestplate");
	public static Item paladinLeggings = (new RioVArmor(Config.addItem("Paladin Leggings"), FlameArmorMaterial, render, 2, "paladin", false)).setUnlocalizedName("paladinLeggings");
	public static Item paladinBoots = (new RioVArmor(Config.addItem("Paladin Boots"), FlameArmorMaterial, render, 3, "paladin", false)).setUnlocalizedName("paladinBoots");
	public static Item paladinLongsword = (new RioVWeapon(Config.addItem("Paladin Longsword"), InfusedOnyx, false)).setUnlocalizedName("paladinLongsword");
	public static Item iceWand = (new RioVWand(Config.addItem("Ice Wand"), 0, 1, 1)).setUnlocalizedName("iceWand");
	public static Item graviWand = (new RioVWand(Config.addItem("Gravi Wand"), 0, 1, 3)).setUnlocalizedName("graviWand");
	public static Item eosPotion = (new RioVDrinkable(Config.addItem("Eos Potion"), 0, 0, true)).setAlwaysEdible().setUnlocalizedName("eosPotion");
	public static Item guide = (new ItemGuide(Config.addItem("Starting Guide"))).setUnlocalizedName("guide");

	public static void add()
	{		
		MethodUtil.registerItem(guide, "Guide");
		MethodUtil.registerItem(eosPotion, "Eos Potion");
		MethodUtil.registerItem(graviWand, "Gravi Wand");
		MethodUtil.registerItem(iceWand, "Ice Wand");
		MethodUtil.registerItem(paladinHelmet, "Paladin Helmet");
		MethodUtil.registerItem(paladinChestplate, "Paladin Chestplate");
		MethodUtil.registerItem(paladinLeggings, "Paladin Leggings");
		MethodUtil.registerItem(paladinBoots, "Paladin Boots");
		MethodUtil.registerItem(paladinLongsword, "Paladin Longsword");
		MethodUtil.registerItem(tasaravHelmet, Color.GOLD + "Tasarav Mallor's Helmet");
		MethodUtil.registerItem(tasaravChestplate, Color.GOLD + "Tasarav Mallor's Chestplate");
		MethodUtil.registerItem(tasaravLeggings, Color.GOLD + "Tasarav Mallor's Leggings");
		MethodUtil.registerItem(tasaravBoots, Color.GOLD + "Tasarav Mallor's Boots");
		MethodUtil.registerItem(tasaravSword, Color.GOLD + "Tasarav Mallor's Sword");
		MethodUtil.registerItem(supremeAunTunHelmet, Color.DARK_RED + "Supreme Aun'Tun Helmet");
		MethodUtil.registerItem(supremeAunTunChestplate, Color.DARK_RED + "Supreme Aun'Tun Chestplate");
		MethodUtil.registerItem(supremeAunTunLeggings, Color.DARK_RED + "Supreme Aun'Tun Leggings");
		MethodUtil.registerItem(supremeAunTunBoots, Color.DARK_RED + "Supreme Aun'Tun Boots");
		MethodUtil.registerItem(heart, "Heart");
		MethodUtil.registerItem(ultraAxeOfAunTun, "Ultra Axe of Aun'Tun");
		MethodUtil.registerItem(rune, "Runestone");
		MethodUtil.registerItem(windElement, "The Element of Wind");
		MethodUtil.registerItem(scroll, "Scroll");
		MethodUtil.registerItem(scrollWindI, "Scroll - Wind I");
		MethodUtil.registerItem(scrollFireI, "Scroll - Fire I");
		MethodUtil.registerItem(scrollEverlight, "Scroll - Everlight");
		MethodUtil.registerItem(scrollFireII, "Scroll - Fire II");
		MethodUtil.registerItem(sheenBag, "Sheen's Bag");
		MethodUtil.registerItem(largeBag, "Large Bag");
		MethodUtil.registerItem(mediumBag, "Medium Bag");
		MethodUtil.registerItem(smallBag, "Small Bag");
		MethodUtil.registerItem(chain, "Chain");
		MethodUtil.registerItem(blackBerry, "Blackberry");
		MethodUtil.registerItem(raspBerry, "Raspberry");
		MethodUtil.registerItem(bloodBerry, "Bloodberry");
		MethodUtil.registerItem(strawBerry, "Strawberry");
		MethodUtil.registerItem(jaavik, "Jaavik");
		MethodUtil.registerItem(berry, "Berry");
		MethodUtil.registerItem(bambooPlanks, "Bamboo Planks");
		MethodUtil.registerItem(bambooItem, "Bamboo Rods");
		MethodUtil.registerItem(voidHolderFilled, "Void Liquid Holder Filled");
		MethodUtil.registerItem(voidHolder, "Void Liquid Holder");
		MethodUtil.registerItem(infusedVraviniteHelmet, "Infused Vravinite Helmet");
		MethodUtil.registerItem(infusedVraviniteChestplate, "Infused Vravinite Chestplate");
		MethodUtil.registerItem(infusedVraviniteLeggings, "Infused Vravinite Leggings");
		MethodUtil.registerItem(infusedVraviniteBoots, "Infused Vravinite Boots");
		MethodUtil.registerItem(infusedVravinitePickaxe, "Infused Vravinite Pickaxe");
		MethodUtil.registerItem(infusedVraviniteAxe, "Infused Vravinite Axe");
		MethodUtil.registerItem(infusedVraviniteShovel, "Infused Vravinite Shovel");
		MethodUtil.registerItem(infusedVraviniteSword, "Infused Vravinite Sword");
		MethodUtil.registerItem(dragonShield, "Dragon Shield");
		MethodUtil.registerItem(auntunShield, "Aun'Tun Shield");
		MethodUtil.registerItem(mythrilShield, "Mythril Shield");
		MethodUtil.registerItem(galokinShield, "Galokin Shield");
		MethodUtil.registerItem(woodenShield, "Wooden Shield");
		MethodUtil.registerItem(stoneShield, "Stone Shield");
		MethodUtil.registerItem(ironShield, "Iron Shield");
		MethodUtil.registerItem(goldShield, "Gold Shield");
		MethodUtil.registerItem(diamondShield, "Diamond Shield");
		MethodUtil.registerItem(blindoniteShield, "Blindonite Shield");
		MethodUtil.registerItem(shieldOfFlame, "Shield of Flame");
		MethodUtil.registerItem(sapphireShield, "Sapphire Shield");
		MethodUtil.registerItem(topazShield, "Mystic Topaz Shield");
		MethodUtil.registerItem(vraviniteShield, "Vravinite Shield");
		MethodUtil.registerItem(onyxShield, "Onyx Shield");
		MethodUtil.registerItem(amethystShield, "Amethyst Shield");
		MethodUtil.registerItem(alerisPickaxe, "Aleris Pickaxe");
		MethodUtil.registerItem(alerisAxe, "Aleris Axe");
		MethodUtil.registerItem(alerisShovel, "Aleris Shovel");
		MethodUtil.registerItem(alerisSword, "Aleris Sword");
		MethodUtil.registerItem(alerisHelmet, "Aleris Helmet");
		MethodUtil.registerItem(alerisChestplate, "Aleris Chestplate");
		MethodUtil.registerItem(alerisLeggings, "Aleris Leggings");
		MethodUtil.registerItem(alerisBoots, "Aleris Boots");
		MethodUtil.registerItem(aleris, "Aleris");
		MethodUtil.registerItem(sanctuaryStonePickaxe, "Sanctuary Stone Pickaxe");
		MethodUtil.registerItem(sanctuaryStoneAxe, "Sanctuary Stone Axe");
		MethodUtil.registerItem(sanctuaryStoneShovel, "Sanctuary Stone Shovel");
		MethodUtil.registerItem(sanctuaryStoneSword, "Sanctuary Stone Sword");
		MethodUtil.registerItem(skywoodPickaxe, "Skywood Pickaxe");
		MethodUtil.registerItem(skywoodAxe, "Skywood Axe");
		MethodUtil.registerItem(skywoodShovel, "Skywood Shovel");
		MethodUtil.registerItem(skywoodSword, "Skywood Sword");
		MethodUtil.registerItem(skywoodSticks, "Skywood Sticks");
		MethodUtil.registerItem(bloodPickaxe, "Blood Pickaxe");
		MethodUtil.registerItem(bloodAxe, "Blood Axe");
		MethodUtil.registerItem(bloodShovel, "Blood Shovel");
		MethodUtil.registerItem(bloodSword, "Blood Sword");
		MethodUtil.registerItem(bloodSticks, "Blood Sticks");
		MethodUtil.registerItem(skywoodDoorItem, "Skywood Door");
		MethodUtil.registerItem(bloodDoorItem, "Blood Door");
		MethodUtil.registerItem(sanctuatiteActivator, "Sanctuatite Activator");
		MethodUtil.registerItem(potionGlassSanctuatite, "Sanctuatite Potion");
		MethodUtil.registerItem(bloodBucketWater, "Blood Water Bucket");
		MethodUtil.registerItem(bloodBucket, "Blood Bucket");
		MethodUtil.registerItem(bloodBucketLava, "Blood Lava Bucket");
		MethodUtil.registerItem(glimmerwoodBucketWater, "Glimmerwood Water Bucket");
		MethodUtil.registerItem(glimmerwoodBucket, "Glimmerwood Bucket");
		MethodUtil.registerItem(glimmerwoodBucketLava, "Glimmerwood Lava Bucket");
		MethodUtil.registerItem(cherryBlossomDoorItem, "Cherry Blossom Door");
		MethodUtil.registerItem(cherryBlossomPickaxe, "Cherry Blossom Pickaxe");
		MethodUtil.registerItem(cherryBlossomAxe, "Cherry Blossom Axe");
		MethodUtil.registerItem(cherryBlossomShovel, "Cherry Blossom Shovel");
		MethodUtil.registerItem(cherryBlossomSword, "Cherry Blossom Sword");
		MethodUtil.registerItem(cherryBlossomSticks, "Cherry Blossom Sticks");
		MethodUtil.registerItem(fireballWand, "Fireball Wand");
		MethodUtil.registerItem(drakiuz, "Drakiuz");
		MethodUtil.registerItem(flamonorActivator, "Flamonor Activator");
		MethodUtil.registerItem(glimmerwoodDoorItem, "Glimmerwood Door");
		MethodUtil.registerItem(vraviniteHelmet, "Vravinite Helmet");
		MethodUtil.registerItem(vraviniteChestplate, "Vravinite Chestplate");
		MethodUtil.registerItem(vraviniteLeggings, "Vravinite Leggings");
		MethodUtil.registerItem(vraviniteBoots, "Vravinite Boots");
		MethodUtil.registerItem(vravinitePickaxe, "Vravinite Pickaxe");
		MethodUtil.registerItem(vraviniteAxe, "Vravinite Axe");
		MethodUtil.registerItem(vraviniteShovel, "Vravinite Shovel");
		MethodUtil.registerItem(vraviniteSword, "Vravinite Sword");
		MethodUtil.registerItem(vravinite, "Vravinite");
		MethodUtil.registerItem(vraviniteArrow, "Vravinite Arrow");
		MethodUtil.registerItem(vraviniteBow, "Vravinite Bow");
		MethodUtil.registerItem(blueMagicApple, "Magical Blue Apple");
		MethodUtil.registerItem(glimmerwoodPickaxe, "Glimmerwood Pickaxe");
		MethodUtil.registerItem(glimmerwoodAxe, "Glimmerwood Axe");
		MethodUtil.registerItem(glimmerwoodShovel, "Glimmerwood Shovel");
		MethodUtil.registerItem(glimmerwoodSword, "Glimmerwood Sword");
		MethodUtil.registerItem(glimmerwoodSticks, "Glimmerwood Sticks");
		MethodUtil.registerItem(vaerynActivator, "Vaeryn Activator");
		MethodUtil.registerItem(infusedBlindoniteHelmet, "Infused Blindonite Helmet");
		MethodUtil.registerItem(infusedBlindoniteChestplate, "Infused Blindonite Chestplate");
		MethodUtil.registerItem(infusedBlindoniteLeggings, "Infused Blindonite Leggings");
		MethodUtil.registerItem(infusedBlindoniteBoots, "Infused Blindonite Boots");
		MethodUtil.registerItem(infusedBlindonitePickaxe, "Infused Blindonite Pickaxe");
		MethodUtil.registerItem(infusedBlindoniteAxe, "Infused Blindonite Axe");
		MethodUtil.registerItem(infusedBlindoniteShovel, "Infused Blindonite Shovel");
		MethodUtil.registerItem(infusedBlindoniteSword, "Infused Blindonite Sword");
		MethodUtil.registerItem(blindoniteHelmet, "Blindonite Helmet");
		MethodUtil.registerItem(blindoniteChestplate, "Blindonite Chestplate");
		MethodUtil.registerItem(blindoniteLeggings, "Blindonite Leggings");
		MethodUtil.registerItem(blindoniteBoots, "Blindonite Boots");
		MethodUtil.registerItem(blindonitePickaxe, "Blindonite Pickaxe");
		MethodUtil.registerItem(blindoniteAxe, "Blindonite Axe");
		MethodUtil.registerItem(blindoniteShovel, "Blindonite Shovel");
		MethodUtil.registerItem(blindoniteSword, "Blindonite Sword");
		MethodUtil.registerItem(tefCrystal, "Tef Crystal");
		MethodUtil.registerItem(tefHelmet, "Tef's Legendary Helmet");
		MethodUtil.registerItem(tefChestplate, "Tef's Legendary Chestplate");
		MethodUtil.registerItem(tefLeggings, "Tef's Legendary Leggings");
		MethodUtil.registerItem(tefBoots, "Tef's Legendary Boots");
		MethodUtil.registerItem(blindOasisActivator, "Blind Oasis Activator");
		MethodUtil.registerItem(blindonite, "Blindonite");
		MethodUtil.registerItem(enforcedBowOfWurTun, "Enforced Bow Of Wur-Tun");
		MethodUtil.registerItem(helmetOfFlame, "Helmet of Flame");
		MethodUtil.registerItem(chestplateOfFlame, "Chestplate of Flame");
		MethodUtil.registerItem(leggingsOfFlame, "Leggings of Flame");
		MethodUtil.registerItem(bootsOfFlame, "Boots of Flame");
		MethodUtil.registerItem(ingotOfFlame, "Ingot of Flame");
		MethodUtil.registerItem(purpleFeather, "Purple Feather");
		MethodUtil.registerItem(clothOfMagic, "Cloth of Magic");
		MethodUtil.registerItem(swordOfFlame, "Sword of Flame");
		MethodUtil.registerItem(infusedTopazHelmet, "Infused Mystic Topaz Helmet");
		MethodUtil.registerItem(infusedTopazChestplate, "Infused Mystic Topaz Chestplate");
		MethodUtil.registerItem(infusedTopazLeggings, "Infused Mystic Topaz Leggings");
		MethodUtil.registerItem(infusedTopazBoots, "Infused Mystic Topaz Boots");
		MethodUtil.registerItem(infusedTopazPickaxe, "Infused Mystic Topaz Pickaxe");
		MethodUtil.registerItem(infusedTopazAxe, "Infused Mystic Topaz Axe");
		MethodUtil.registerItem(infusedTopazShovel, "Infused Mystic Topaz Shovel");
		MethodUtil.registerItem(infusedTopazSword, "Infused Mystic Topaz Sword");
		MethodUtil.registerItem(infusedSapphireHelmet, "Infused Sapphire Helmet");
		MethodUtil.registerItem(infusedSapphireChestplate, "Infused Sapphire Chestplate");
		MethodUtil.registerItem(infusedSapphireLeggings, "Infused Sapphire Leggings");
		MethodUtil.registerItem(infusedSapphireBoots, "Infused Sapphire Boots");
		MethodUtil.registerItem(infusedSapphirePickaxe, "Infused Sapphire Pickaxe");
		MethodUtil.registerItem(infusedSapphireAxe, "Infused Sapphire Axe");
		MethodUtil.registerItem(infusedSapphireShovel, "Infused Sapphire Shovel");
		MethodUtil.registerItem(infusedSapphireSword, "Infused Sapphire Sword");
		MethodUtil.registerItem(theDarknessCrystal, "Crystal of Darkness");
		MethodUtil.registerItem(magickaHelmet, "Hood of Magic");
		MethodUtil.registerItem(magickaChestplate, "Robe of Magic");
		MethodUtil.registerItem(magickaLeggings, "Leggings of Magic");
		MethodUtil.registerItem(magickaBoots, "Boots of Magic");
		MethodUtil.registerItem(galokinCrystal, "Galokin Crystal");
		MethodUtil.registerItem(galokinSword, "Galokin Sword");
		MethodUtil.registerItem(galokinHelmet, "Galokin Helmet");
		MethodUtil.registerItem(galokinChestplate, "Galokin Chestplate");
		MethodUtil.registerItem(galokinLeggings, "Galokin Leggings");
		MethodUtil.registerItem(galokinBoots, "Galokin Boots");
		MethodUtil.registerItem(vaiziCurrency, "Vaizi");
		MethodUtil.registerItem(cherry, "Cherry");
		MethodUtil.registerItem(manchet, "Manchet");
		MethodUtil.registerItem(topazHelmet, "Mystic Topaz Helmet");
		MethodUtil.registerItem(topazChestplate, "Mystic Topaz Chestplate");
		MethodUtil.registerItem(topazLeggings, "Mystic Topaz Leggings");
		MethodUtil.registerItem(topazBoots, "Mystic Topaz Boots");
		MethodUtil.registerItem(topazPickaxe, "Mystic Topaz Pickaxe");
		MethodUtil.registerItem(topazAxe, "Mystic Topaz Axe");
		MethodUtil.registerItem(topazShovel, "Mystic Topaz Shovel");
		MethodUtil.registerItem(topazSword, "Mystic Topaz Sword");
		MethodUtil.registerItem(topaz, "Mystic Topaz");
		MethodUtil.registerItem(opal, "Opal");
		MethodUtil.registerItem(sapphireHelmet, "Sapphire Helmet");
		MethodUtil.registerItem(sapphireChestplate, "Sapphire Chestplate");
		MethodUtil.registerItem(sapphireLeggings, "Sapphire Leggings");
		MethodUtil.registerItem(sapphireBoots, "Sapphire Boots");
		MethodUtil.registerItem(sapphirePickaxe, "Sapphire Pickaxe");
		MethodUtil.registerItem(sapphireAxe, "Sapphire Axe");
		MethodUtil.registerItem(sapphireShovel, "Sapphire Shovel");
		MethodUtil.registerItem(sapphireSword, "Sapphire Sword");
		MethodUtil.registerItem(sapphire, "Sapphire");
		MethodUtil.registerItem(pepper, "Pepper");
		MethodUtil.registerItem(pepperSpices, "Pepper Spices");
		MethodUtil.registerItem(spicedWine, "Spiced Wine");
		MethodUtil.registerItem(greenApple, "Green Apple");
		MethodUtil.registerItem(wine, "Wine");
		MethodUtil.registerItem(grapes, "Grapes");
		MethodUtil.registerItem(potionGlass, "Potion Glass");
		MethodUtil.registerItem(wineGlass, "Wine Glass");
		MethodUtil.registerItem(cookedHorseMeat, "Cooked Horse Meat");
		MethodUtil.registerItem(horseMeat, "Horse Meat");
		MethodUtil.registerItem(tomato, "Tomato");
		MethodUtil.registerItem(khuulisScythe, "Khuuli's Scythe");
		MethodUtil.registerItem(blackDurii, "Black Durii");
		MethodUtil.registerItem(auntunSummoner, "Aun'Tun Summoner");
		MethodUtil.registerItem(vulron, "Vulron");
		MethodUtil.registerItem(bowOfWurTun, "Bow of Wur-Tun");
		MethodUtil.registerItem(darknessArrow, "Arrow of Darkness");
		MethodUtil.registerItem(daetoriSword, "Daetori's Sword");
		MethodUtil.registerItem(sorrowSword, "Sorrow Sword");
		MethodUtil.registerItem(axeOfAunTun, "Axe of Aun'Tun");
		MethodUtil.registerItem(HalfFusedaxeOfAunTun, "Half Fused Axe of Aun'Tun");
		MethodUtil.registerItem(UnfusedaxeOfAunTun, "Unfused Axe of Aun'Tun");
		MethodUtil.registerItem(blackBone, "Black Bone");
		MethodUtil.registerItem(amethyst, "Amethyst");
		MethodUtil.registerItem(onyx, "Onyx");
		MethodUtil.registerItem(slateFragment, "Slate Fragment");
		MethodUtil.registerItem(orb, "Orb");
		MethodUtil.registerItem(nironite, "Nironite");
		MethodUtil.registerItem(agonite, "Agonite");
		MethodUtil.registerItem(terronCrystal, "Terron Crystal");
		MethodUtil.registerItem(baseCrystal, "Base Crystal");
		MethodUtil.registerItem(garnet, "Garnet");
		MethodUtil.registerItem(infusedAmethystShovel, "Infused Amethyst Shovel");
		MethodUtil.registerItem(infusedAmethystPickaxe, "Infused Amethyst Pickaxe");
		MethodUtil.registerItem(infusedAmethystAxe, "Infused Amethyst Axe");
		MethodUtil.registerItem(infusedOnyxShovel, "Infused Onyx Shovel");
		MethodUtil.registerItem(infusedOnyxPickaxe, "Infused Onyx Pickaxe");
		MethodUtil.registerItem(infusedOnyxAxe, "Infused Onyx Axe");
		MethodUtil.registerItem(auntunMinionHelmet, "Aun'Tun Minion Helmet");
		MethodUtil.registerItem(auntunMinionChestplate, "Aun'Tun Minion Chestplate");
		MethodUtil.registerItem(auntunMinionLeggings, "Aun'Tun Minion Leggings");
		MethodUtil.registerItem(auntunMinionBoots, "Aun'Tun Minion Boots");
		MethodUtil.registerItem(onyxHelmet, "Onyx Helmet");
		MethodUtil.registerItem(onyxChestplate, "Onyx Chestplate");
		MethodUtil.registerItem(onyxLeggings, "Onyx Leggings");
		MethodUtil.registerItem(onyxBoots, "Onyx Boots");
		MethodUtil.registerItem(amethystHelmet, "Amethyst Helmet");
		MethodUtil.registerItem(amethystChestplate, "Amethyst Chestplate");
		MethodUtil.registerItem(amethystLeggings, "Amethyst Leggings");
		MethodUtil.registerItem(amethystBoots, "Amethyst Boots");
		MethodUtil.registerItem(infusedOnyxHelmet, "Infused Onyx Helmet");
		MethodUtil.registerItem(infusedOnyxChestplate, "Infused Onyx Chestplate");
		MethodUtil.registerItem(infusedOnyxLeggings, "Infused Onyx Leggings");
		MethodUtil.registerItem(infusedOnyxBoots, "Infused Onyx Boots");
		MethodUtil.registerItem(infusedAmethystHelmet, "Infused Amethyst Helmet");
		MethodUtil.registerItem(infusedAmethystChestplate, "Infused Amethyst Chestplate");
		MethodUtil.registerItem(infusedAmethystLeggings, "Infused Amethyst Leggings");
		MethodUtil.registerItem(infusedAmethystBoots, "Infused Amethyst Boots");
		MethodUtil.registerItem(amethystPickaxe, "Amethyst Pickaxe");
		MethodUtil.registerItem(amethystAxe, "Amethyst Axe");
		MethodUtil.registerItem(amethystShovel, "Amethyst Shovel");
		MethodUtil.registerItem(amethystSword, "Amethyst Sword");
		MethodUtil.registerItem(infusedAmethystSword, "Infused Amethyst Sword");
		MethodUtil.registerItem(onyxSword, "Onyx Sword");
		MethodUtil.registerItem(infusedOnyxSword, "Infused Onyx Sword");
		MethodUtil.registerItem(onyxPickaxe, "Onyx Pickaxe");
		MethodUtil.registerItem(agonitePickaxe, "Agonite Pickaxe");
		MethodUtil.registerItem(onyxAxe, "Onyx Axe");
		MethodUtil.registerItem(onyxShovel, "Onyx Shovel");
		MethodUtil.registerItem(garnetHelmet, "Garnet Helmet");
		MethodUtil.registerItem(garnetChestplate, "Garnet Chestplate");
		MethodUtil.registerItem(garnetLeggings, "Garnet Leggings");
		MethodUtil.registerItem(garnetBoots, "Garnet Boots");
		MethodUtil.registerItem(mythrilHelmet, "Mythril Helmet");
		MethodUtil.registerItem(mythrilChestplate, "Mythril Chestplate");
		MethodUtil.registerItem(mythrilLeggings, "Mythril Leggings");
		MethodUtil.registerItem(mythrilBoots, "Mythril Boots");
		MethodUtil.registerItem(darkMatter, "Dark Matter");
		MethodUtil.registerItem(ambrosia, "Ambrosia");
		MethodUtil.registerItem(mythrilIngot, "Mythril Ingot");
		MethodUtil.registerItem(burnedQuartz, "Black Quartz");
		MethodUtil.registerItem(dragonSword, Color.DARK_RED + "Dragon Sword");
		MethodUtil.registerItem(dragonSoul, Color.DARK_RED + "Dragon Soul Gem");
		MethodUtil.registerItem(demonAngelCrystal, Color.DARK_RED + "Demon Angel Crystal");
		MethodUtil.registerItem(dragonHelmet, Color.DARK_RED + "Dragon Helmet");
		MethodUtil.registerItem(dragonChestplate, Color.DARK_RED + "Dragon Chestplate");
		MethodUtil.registerItem(dragonLeggings, Color.DARK_RED + "Dragon Leggings");
		MethodUtil.registerItem(dragonBoots, Color.DARK_RED + "Dragon Boots");
		MethodUtil.registerItem(dragonPickaxe, Color.DARK_RED + "Dragon Pickaxe");
		MethodUtil.registerItem(dragonAxe, Color.DARK_RED + "Dragon Axe");
		MethodUtil.registerItem(dragonShovel, Color.DARK_RED + "Dragon Shovel");
		MethodUtil.registerItem(infusedDragonHelmet, Color.DARK_RED + "Infused Dragon Helmet");
		MethodUtil.registerItem(infusedDragonChestplate, Color.DARK_RED + "Infused Dragon Chestplate");
		MethodUtil.registerItem(infusedDragonLeggings, Color.DARK_RED + "Infused Dragon Leggings");
		MethodUtil.registerItem(infusedDragonBoots, Color.DARK_RED + "Infused Dragon Boots");
		MethodUtil.registerItem(infusedDragonPickaxe, Color.DARK_RED + "Infused Dragon Pickaxe");
		MethodUtil.registerItem(infusedDragonAxe, Color.DARK_RED + "Infused Dragon Axe");
		MethodUtil.registerItem(infusedDragonShovel, Color.DARK_RED + "Infused Dragon Shovel");
		MethodUtil.registerItem(infusedDragonSword, Color.DARK_RED + "Infused Dragon Sword");
	}

	public static Item infusedBloodwoodPickaxe;
	public static Item infusedBloodwoodAxe;
	public static Item infusedBloodwoodShovel;
	public static Item infusedBloodwoodSword;
	public static Item infusedGhostwoodSword;
	public static Item infusedGhostwoodPickaxe;
	public static Item infusedGhostwoodShovel;
	public static Item infusedGhostwoodAxe;
	public static Item infusedDarkwoodSword;
	public static Item infusedDarkwoodPickaxe;
	public static Item infusedDarkwoodShovel;
	public static Item infusedDarkwoodAxe;
	public static Item infusedFusewoodSword;
	public static Item infusedFusewoodPickaxe;
	public static Item infusedFusewoodShovel;
	public static Item infusedFusewoodAxe;
	public static Item infusedNetherquartzSword;
	public static Item infusedNetherquartzPickaxe;
	public static Item infusedNetherquartzShovel;
	public static Item infusedNetherquartzAxe;

	public static void addNatura()
	{
		if(TheMistsOfRioV.getInstance().natura)
		{
			EnumToolMaterial InfusedBloodwood = EnumHelper.addToolMaterial("InfusedBloodwood", 3, 450, 8.0F, 4.0F, 25);
			EnumToolMaterial InfusedGhostwood = EnumHelper.addToolMaterial("InfusedGhostwood", 1, 159, 3.0F, 1.0F, 16);
			EnumToolMaterial InfusedDarkwood = EnumHelper.addToolMaterial("InfusedDarkwood", 2, 231, 5.0F, 2.0F, 6);

			infusedBloodwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Bloodwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_pickaxe");
			infusedBloodwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Bloodwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_hatchet");
			infusedBloodwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Bloodwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_shovel");
			infusedBloodwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Bloodwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_sword");
			infusedGhostwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Ghostwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_pickaxe");
			infusedGhostwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Ghostwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_hatchet");
			infusedGhostwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Ghostwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_shovel");
			infusedGhostwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Ghostwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_sword");
			infusedDarkwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Darkwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_pickaxe");
			infusedDarkwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Darkwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_hatchet");
			infusedDarkwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Darkwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_shovel");
			infusedDarkwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Darkwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_sword");
			infusedFusewoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Fusewood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_pickaxe");
			infusedFusewoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Fusewood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_hatchet");
			infusedFusewoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Fusewood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_shovel");
			infusedFusewoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Fusewood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_sword");
			infusedNetherquartzPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Netherquartz Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_pickaxe");
			infusedNetherquartzAxe = (new RioVAxe(Config.addExpansionItem("Infused Netherquartz Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_hatchet");
			infusedNetherquartzShovel = (new RioVSpade(Config.addExpansionItem("Infused Netherquartz Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_shovel");
			infusedNetherquartzSword = (new RioVWeapon(Config.addExpansionItem("Infused Netherquartz Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_sword");
			
			MethodUtil.registerItem(infusedFusewoodPickaxe, "Infused Fusewood Pickaxe");
			MethodUtil.registerItem(infusedFusewoodAxe, "Infused Fusewood Axe");
			MethodUtil.registerItem(infusedFusewoodShovel, "Infused Fusewood Shovel");
			MethodUtil.registerItem(infusedFusewoodSword, "Infused Fusewood Sword");
			MethodUtil.registerItem(infusedNetherquartzPickaxe, "Infused Netherquartz Pickaxe");
			MethodUtil.registerItem(infusedNetherquartzAxe, "Infused Netherquartz Axe");
			MethodUtil.registerItem(infusedNetherquartzShovel, "Infused Netherquartz Shovel");
			MethodUtil.registerItem(infusedNetherquartzSword, "Infused Netherquartz Sword");
			MethodUtil.registerItem(infusedBloodwoodPickaxe, "Infused Bloodwood Pickaxe");
			MethodUtil.registerItem(infusedBloodwoodAxe, "Infused Bloodwood Axe");
			MethodUtil.registerItem(infusedBloodwoodShovel, "Infused Bloodwood Shovel");
			MethodUtil.registerItem(infusedBloodwoodSword, "Infused Bloodwood Sword");
			MethodUtil.registerItem(infusedGhostwoodPickaxe, "Infused Ghostwood Pickaxe");
			MethodUtil.registerItem(infusedGhostwoodAxe, "Infused Ghostwood Axe");
			MethodUtil.registerItem(infusedGhostwoodShovel, "Infused Ghostwood Shovel");
			MethodUtil.registerItem(infusedGhostwoodSword, "Infused Ghostwood Sword");
			MethodUtil.registerItem(infusedDarkwoodPickaxe, "Infused Darkwood Pickaxe");
			MethodUtil.registerItem(infusedDarkwoodAxe, "Infused Darkwood Axe");
			MethodUtil.registerItem(infusedDarkwoodShovel, "Infused Darkwood Shovel");
			MethodUtil.registerItem(infusedDarkwoodSword, "Infused Darkwood Sword");
		}
	}

	public static Item infusedSkyrootPickaxe;
	public static Item infusedSkyrootAxe;
	public static Item infusedSkyrootShovel;
	public static Item infusedSkyrootSword;
	public static Item infusedHolystonePickaxe;
	public static Item infusedHolystoneAxe;
	public static Item infusedHolystoneShovel;
	public static Item infusedHolystoneSword;
	public static Item infusedZanitePickaxe;
	public static Item infusedZaniteAxe;
	public static Item infusedZaniteShovel;
	public static Item infusedZaniteSword;
	public static Item infusedGravititePickaxe;
	public static Item infusedGravititeAxe;
	public static Item infusedGravititeShovel;
	public static Item infusedGravititeSword;
	public static Item infusedZaniteHelmet;
	public static Item infusedZaniteChestplate;
	public static Item infusedZaniteLeggings;
	public static Item infusedZaniteBoots;
	public static Item infusedGravititeHelmet;
	public static Item infusedGravititeChestplate;
	public static Item infusedGravititeLeggings;
	public static Item infusedGravititeBoots;
	public static Item magicalBlueBerry;

	public static void addAether()
	{
		if(TheMistsOfRioV.getInstance().aether)
		{
			EnumToolMaterial InfusedSkyroot = EnumHelper.addToolMaterial("InfusedSkyroot", 1, 159, 3.0F, 1.0F, 16);
			EnumToolMaterial InfusedHolystone = EnumHelper.addToolMaterial("InfusedHolystone", 2, 231, 5.0F, 2.0F, 6);
			EnumToolMaterial InfusedZanite = EnumHelper.addToolMaterial("InfusedZanite", 3, 350, 7.0F, 3.0F, 15);
			EnumToolMaterial InfusedGravitite = EnumHelper.addToolMaterial("InfusedGravitite", 4, 1661, 9.0F, 4.0F, 11);

			EnumArmorMaterial InfusedZaniteArmor = EnumHelper.addArmorMaterial("InfusedZaniteArmor", 17, new int[]{3, 6, 5, 3}, 11);
			EnumArmorMaterial InfusedGravititeArmor = EnumHelper.addArmorMaterial("InfusedGravititeArmor", 35, new int[]{4, 8, 6, 4}, 12);

			infusedSkyrootPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Skyroot Pickaxe"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootPickaxe");
			infusedSkyrootAxe = (new RioVAxe(Config.addExpansionItem("Infused Skyroot Axe"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootAxe");
			infusedSkyrootShovel = (new RioVSpade(Config.addExpansionItem("Infused Skyroot Shovel"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootShovel");
			infusedSkyrootSword = (new RioVWeapon(Config.addExpansionItem("Infused Skyroot Sword"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootSword");
			infusedHolystonePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Holystone Pickaxe"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystonePickaxe");
			infusedHolystoneAxe = (new RioVAxe(Config.addExpansionItem("Infused Holystone Axe"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneAxe");
			infusedHolystoneShovel = (new RioVSpade(Config.addExpansionItem("Infused Holystone Shovel"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneShovel");
			infusedHolystoneSword = (new RioVWeapon(Config.addExpansionItem("Infused Holystone Sword"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneSword");
			infusedZanitePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Zanite Pickaxe"), InfusedZanite, true)).setUnlocalizedName("infusedZanitePickaxe");
			infusedZaniteAxe = (new RioVAxe(Config.addExpansionItem("Infused Zanite Axe"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteAxe");
			infusedZaniteShovel = (new RioVSpade(Config.addExpansionItem("Infused Zanite Shovel"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteShovel");
			infusedZaniteSword = (new RioVWeapon(Config.addExpansionItem("Infused Zanite Sword"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteSword");
			infusedGravititePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Gravitite Pickaxe"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititePickaxe");
			infusedGravititeAxe = (new RioVAxe(Config.addExpansionItem("Infused Gravitite Axe"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeAxe");
			infusedGravititeShovel = (new RioVSpade(Config.addExpansionItem("Infused Gravitite Shovel"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeShovel");
			infusedGravititeSword = (new RioVWeapon(Config.addExpansionItem("Infused Gravitite Sword"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeSword");
			infusedZaniteHelmet = (new RioVArmor(Config.addExpansionItem("Infused Zanite Helmet"), InfusedZaniteArmor, render, 0, "Zanite", true)).setUnlocalizedName("infusedZaniteHelmet");
			infusedZaniteChestplate = (new RioVArmor(Config.addExpansionItem("Infused Zanite Chestplate"), InfusedZaniteArmor, render, 1, "Zanite", true)).setUnlocalizedName("infusedZaniteChestplate");
			infusedZaniteLeggings = (new RioVArmor(Config.addExpansionItem("Infused Zanite Leggings"), InfusedZaniteArmor, render, 2, "Zanite", true)).setUnlocalizedName("infusedZaniteLeggings");
			infusedZaniteBoots = (new RioVArmor(Config.addExpansionItem("Infused Zanite Boots"), InfusedZaniteArmor, render, 3, "Zanite", true)).setUnlocalizedName("infusedZaniteBoots");
			infusedGravititeHelmet = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Helmet"), InfusedGravititeArmor, render, 0, "Gravitite", true)).setUnlocalizedName("infusedGravitieHelmet");
			infusedGravititeChestplate = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Chestplate"), InfusedGravititeArmor, render, 1, "Gravitite", true)).setUnlocalizedName("infusedGravitieChestplate");
			infusedGravititeLeggings = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Leggings"), InfusedGravititeArmor, render, 2, "Gravitite", true)).setUnlocalizedName("infusedGravitieLeggings");
			infusedGravititeBoots = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Boots"), InfusedGravititeArmor, render, 3, "Gravitite", true)).setUnlocalizedName("infusedGravitieBoots");
			magicalBlueBerry = (new RioVConsumable(Config.addExpansionItem("Magical Blue Berry"), 6, 0, true)).setUnlocalizedName("magicalBlueBerry");

			MethodUtil.registerItem(infusedZaniteHelmet, "Infused Zanite Helmet");
			MethodUtil.registerItem(infusedZaniteChestplate, "Infused Zanite Chestplate");
			MethodUtil.registerItem(infusedZaniteLeggings, "Infused Zanite Leggings");
			MethodUtil.registerItem(infusedZaniteBoots, "Infused Zanite Boots");
			MethodUtil.registerItem(infusedGravititeHelmet, "Infused Gravitite Helmet");
			MethodUtil.registerItem(infusedGravititeChestplate, "Infused Gravitite Chestplate");
			MethodUtil.registerItem(infusedGravititeLeggings, "Infused Gravitite Leggings");
			MethodUtil.registerItem(infusedGravititeBoots, "Infused Gravitite Boots");
			MethodUtil.registerItem(infusedSkyrootPickaxe, "Infused Skyroot Pickaxe");
			MethodUtil.registerItem(infusedSkyrootAxe, "Infused Skyroot Axe");
			MethodUtil.registerItem(infusedSkyrootShovel, "Infused Skyroot Shovel");
			MethodUtil.registerItem(infusedSkyrootSword, "Infused Skyroot Sword");
			MethodUtil.registerItem(infusedHolystonePickaxe, "Infused Holystone Pickaxe");
			MethodUtil.registerItem(infusedHolystoneAxe, "Infused Holystone Axe");
			MethodUtil.registerItem(infusedHolystoneShovel, "Infused Holystone Shovel");
			MethodUtil.registerItem(infusedHolystoneSword, "Infused Holystone Sword");
			MethodUtil.registerItem(infusedZanitePickaxe, "Infused Zanite Pickaxe");
			MethodUtil.registerItem(infusedZaniteAxe, "Infused Zanite Axe");
			MethodUtil.registerItem(infusedZaniteShovel, "Infused Zanite Shovel");
			MethodUtil.registerItem(infusedZaniteSword, "Infused Zanite Sword");
			MethodUtil.registerItem(infusedGravititePickaxe, "Infused Gravitite Pickaxe");
			MethodUtil.registerItem(infusedGravititeAxe, "Infused Gravitite Axe");
			MethodUtil.registerItem(infusedGravititeShovel, "Infused Gravitite Shovel");
			MethodUtil.registerItem(infusedGravititeSword, "Infused Gravitite Sword");
			MethodUtil.registerItem(magicalBlueBerry, "Magical Blue Berry");
		}
	}
}
