package sheenrox82.RioV.src.content;

import mods.natura.common.NContent;
import net.aetherteam.aether.items.AetherItems;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.EnumHelper;
import sheenrox82.RioV.src.base.Config;
import sheenrox82.RioV.src.base.TheMistsOfRioV;
import sheenrox82.RioV.src.item.ItemBamboo;
import sheenrox82.RioV.src.item.ItemBowOfWurTun;
import sheenrox82.RioV.src.item.ItemEnforcedBowOfWurTun;
import sheenrox82.RioV.src.item.ItemLongBow;
import sheenrox82.RioV.src.item.ItemVraviniteBow;
import sheenrox82.RioV.src.item.RioVActivators;
import sheenrox82.RioV.src.item.RioVArmor;
import sheenrox82.RioV.src.item.RioVAxe;
import sheenrox82.RioV.src.item.RioVBucket;
import sheenrox82.RioV.src.item.RioVConsumable;
import sheenrox82.RioV.src.item.RioVDoor;
import sheenrox82.RioV.src.item.RioVDrinkable;
import sheenrox82.RioV.src.item.RioVItem;
import sheenrox82.RioV.src.item.RioVMusicDisk;
import sheenrox82.RioV.src.item.RioVPickaxe;
import sheenrox82.RioV.src.item.RioVPotions;
import sheenrox82.RioV.src.item.RioVShield;
import sheenrox82.RioV.src.item.RioVSpade;
import sheenrox82.RioV.src.item.RioVSummoners;
import sheenrox82.RioV.src.item.RioVVoidHolder;
import sheenrox82.RioV.src.item.RioVWand;
import sheenrox82.RioV.src.item.RioVWeapon;
import sheenrox82.RioV.src.proxy.CommonProxy;
import sheenrox82.RioV.src.recipe.DarkenerRecipes;
import sheenrox82.RioV.src.recipe.InfuserRecipes;
import sheenrox82.RioV.src.util.Color;
import sheenrox82.RioV.src.util.Registry;

public class Items 
{
	public static final int render = CommonProxy.addArmor("armor");

	static EnumToolMaterial Amethyst = EnumHelper.addToolMaterial("Amethyst", 3, 400, 5F, 4, 8);
	static EnumToolMaterial InfusedAmethyst = EnumHelper.addToolMaterial("InfusedAmethyst", 3, 500, 9F, 5, 9);
	static EnumToolMaterial Onyx = EnumHelper.addToolMaterial("Onyx", 3, 600, 10F, 5, 10);
	static EnumToolMaterial InfusedOnyx = EnumHelper.addToolMaterial("InfusedOnyx", 4, 700, 11F, 6, 11);
	static EnumToolMaterial Sapphire = EnumHelper.addToolMaterial("Sapphire", 2, 300, 4F, 1, 10);
	static EnumToolMaterial Topaz = EnumHelper.addToolMaterial("Topaz", 2, 350, 4F, 1, 10);
	static EnumToolMaterial Agonite = EnumHelper.addToolMaterial("Agonite", 8, 1000, 9F, 3, 14);
	static EnumToolMaterial Dragon = EnumHelper.addToolMaterial("Dragon", 9, 3000, 15F, 10, 15);
	static EnumToolMaterial Daetori = EnumHelper.addToolMaterial("Daetori", 2, 500, 5F, 9, 12);
	static EnumToolMaterial Ani = EnumHelper.addToolMaterial("Ani", 2, 100, 5F, 1, 5);
	static EnumToolMaterial Nizonian = EnumHelper.addToolMaterial("Nizonian", 2, 200, 5F, 1, 6);
	static EnumToolMaterial Sorrow = EnumHelper.addToolMaterial("Sorrow", 2, 700, 5F, 10, 13);
	static EnumToolMaterial AxeOfAunTun = EnumHelper.addToolMaterial("AxeOfAunTun", 2, 2500, 5F, 18, 16);
	static EnumToolMaterial Slate = EnumHelper.addToolMaterial("Slate", 2, 700, 5F, 2, 7);
	static EnumToolMaterial SharpenedSlate = EnumHelper.addToolMaterial("SharpenedSlate", 2, 700, 5F, 3, 8);
	static EnumToolMaterial Vulron = EnumHelper.addToolMaterial("Vulron", 6, 200, 9F, 6, 12);
	static EnumToolMaterial InfusedDragon = EnumHelper.addToolMaterial("InfusedDragon", 11, 3400, 18F, 11, 16);
	static EnumToolMaterial DarkenedAmethyst = EnumHelper.addToolMaterial("DarkenedAmethyst", 3, 600, 7F, 5, 8);
	static EnumToolMaterial DarkenedOnyx = EnumHelper.addToolMaterial("DarkenedOnyx", 4, 800, 12F, 6, 10);
	static EnumToolMaterial DarkenedInfusedOnyx = EnumHelper.addToolMaterial("DarkenedInfusedOnyx", 2, 1100, 13F, 7, 13);
	static EnumToolMaterial DarkenedInfusedAmethyst = EnumHelper.addToolMaterial("DarkenedInfusedAmethyst", 2, 800, 8F, 6, 11);
	static EnumToolMaterial Training = EnumHelper.addToolMaterial("Training", 0, 20, 2F, 0, 29);
	static EnumToolMaterial Galokin = EnumHelper.addToolMaterial("Galokin", 4, 400, 6F, 6, 12);
	static EnumToolMaterial InfusedSapphire = EnumHelper.addToolMaterial("Sapphire", 4, 400, 5F, 2, 10);
	static EnumToolMaterial InfusedTopaz = EnumHelper.addToolMaterial("Topaz", 3, 450, 5F, 2, 10);
	static EnumToolMaterial DarkenedSapphire = EnumHelper.addToolMaterial("DarkenedSapphire", 4, 700, 7F, 2, 12);
	static EnumToolMaterial DarkenedTopaz = EnumHelper.addToolMaterial("DarkenedTopaz", 3, 600, 7F, 2, 12);
	static EnumToolMaterial DarkenedInfusedSapphire = EnumHelper.addToolMaterial("DarkenedInfusedSapphire", 5, 800, 8F, 3, 13);
	static EnumToolMaterial DarkenedInfusedTopaz = EnumHelper.addToolMaterial("DarkenedInfusedTopaz", 4, 700, 8F, 3, 13);
	static EnumToolMaterial Flame = EnumHelper.addToolMaterial("Flame", 6, 900, 9F, 7, 16);
	static EnumToolMaterial DarkenedDragon = EnumHelper.addToolMaterial("DarkenedDragon", 10, 3400, 18F, 12, 17);
	static EnumToolMaterial DarkenedInfusedDragon = EnumHelper.addToolMaterial("DarkenedInfusedDragon", 10, 3700, 20F, 14, 18);
	static EnumToolMaterial Blindonite = EnumHelper.addToolMaterial("Blindonite", 4, 400, 6F, 5, 14);
	static EnumToolMaterial InfusedBlindonite = EnumHelper.addToolMaterial("InfusedBlindonite", 5, 600, 8F, 7, 15);
	static EnumToolMaterial Glimmerwood = EnumHelper.addToolMaterial("Glimmerwood", 2, 250, 4F, 2, 20);
	static EnumToolMaterial CherryBlossom = EnumHelper.addToolMaterial("CherryBlossom", 2, 100, 2F, 0, 20);
	static EnumToolMaterial Aleris = EnumHelper.addToolMaterial("Aleris", 14, 2400, 14F, 16, 21);
	static EnumToolMaterial InfusedVravinite = EnumHelper.addToolMaterial("InfusedVravinite", 13, 1000, 13F, 11, 12);
	static EnumToolMaterial DarkenedVravinite = EnumHelper.addToolMaterial("DarkenedVravinite", 13, 1100, 14F, 12, 21);
	static EnumToolMaterial DarkenedInfusedVravinite = EnumHelper.addToolMaterial("DarkenedInfusedVravinite", 13, 1100, 14F, 13, 21);
	static EnumToolMaterial Vravinite = EnumHelper.addToolMaterial("Vravinite", 12, 900, 13F, 10, 12);

	static EnumArmorMaterial InfusedAmethystArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDAMETHYST", 17, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial InfusedOnyxArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDONYX", 18, new int[] {5, 6, 6, 5}, 20);
	static EnumArmorMaterial InfusedSapphireArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDSAPPHIRE", 15, new int[] {3, 6, 6, 3}, 20);
	static EnumArmorMaterial InfusedTopazArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDTOPAZ", 14, new int[] {3, 5, 5, 3}, 20);
	static EnumArmorMaterial InfusedDragonArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDDRAGON", 39, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial DragonArmorMaterial = EnumHelper.addArmorMaterial("DRAGON", 37, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial AunTunArmorMaterial = EnumHelper.addArmorMaterial("AUNTUN", 40, new int[] {3, 8, 6, 3}, 20);
	static EnumArmorMaterial GarnetArmorMaterial = EnumHelper.addArmorMaterial("GARNET", 22, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial AmethystArmorMaterial = EnumHelper.addArmorMaterial("AMETHYST", 15, new int[] {3, 5, 6, 3}, 20);
	static EnumArmorMaterial OnyxArmorMaterial = EnumHelper.addArmorMaterial("ONYX", 16, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial MythrilArmorMaterial = EnumHelper.addArmorMaterial("MYTHRIL", 36, new int[] {4, 8, 6, 4}, 20);
	static EnumArmorMaterial GalokinArmorMaterial = EnumHelper.addArmorMaterial("GALOKIN", 33, new int[] {3, 8, 6, 3}, 20);
	static EnumArmorMaterial SapphireArmorMaterial = EnumHelper.addArmorMaterial("SAPPHIRE", 10, new int[] {3, 5, 5, 3}, 20);
	static EnumArmorMaterial TopazArmorMaterial = EnumHelper.addArmorMaterial("TOPAZ", 9, new int[] {3, 4, 4, 3}, 20);
	static EnumArmorMaterial FlameArmorMaterial = EnumHelper.addArmorMaterial("FLAME", 30, new int[] {4, 5, 6, 4}, 20);
	static EnumArmorMaterial BlindoniteArmorMaterial = EnumHelper.addArmorMaterial("BLINDONITE", 20, new int[] {3, 4, 6, 3}, 20);
	static EnumArmorMaterial InfusedBlindoniteArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDBLINDONITE", 23, new int[] {3, 4, 6, 3}, 20);
	static EnumArmorMaterial AlerisArmorMaterial = EnumHelper.addArmorMaterial("ALERIS", 48, new int[] {5, 8, 6, 5}, 20);
	static EnumArmorMaterial InfusedVraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 33, new int[] {4, 6, 6, 4}, 20);
	static EnumArmorMaterial VraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 32, new int[] {4, 6, 6, 4}, 20);

	public static Item onyxHelmet = (new RioVArmor(Config.addItem("Onyx Helmet"), OnyxArmorMaterial, render, 0, "onyx", false)).setUnlocalizedName("onyxHelmet");
	public static Item onyxChestplate = (new RioVArmor(Config.addItem("Onyx Chestplate"), OnyxArmorMaterial, render, 1, "onyx", false)).setUnlocalizedName("onyxChestplate");
	public static Item onyxLeggings = (new RioVArmor(Config.addItem("Onyx Leggings"), OnyxArmorMaterial, render, 2, "onyx", false)).setUnlocalizedName("onyxLeggings");
	public static Item onyxBoots = (new RioVArmor(Config.addItem("Onyx Boots"), OnyxArmorMaterial, render, 3, "onyx", false)).setUnlocalizedName("onyxBoots");
	public static Item amethystHelmet = (new RioVArmor(Config.addItem("Amethyst Helmet"), AmethystArmorMaterial, render, 0, "amethyst", false)).setUnlocalizedName("amethystHelmet");
	public static Item amethystChestplate = (new RioVArmor(Config.addItem("Amethyst Chestplate"), AmethystArmorMaterial, render, 1, "amethyst", false)).setUnlocalizedName("amethystChestplate");
	public static Item amethystLeggings = (new RioVArmor(Config.addItem("Amethyst Leggings"), AmethystArmorMaterial, render, 2, "amethyst", false)).setUnlocalizedName("amethystLeggings");
	public static Item amethystBoots = (new RioVArmor(Config.addItem("Amethyst Boots"), AmethystArmorMaterial, render, 3, "amethyst", false)).setUnlocalizedName("amethystBoots");
	public static Item infusedOnyxHelmet = (new RioVArmor(Config.addItem("Infused Onyx Helmet"), InfusedOnyxArmorMaterial, render, 0, "onyx", true)).setUnlocalizedName("infusedOnyxHelmet");;
	public static Item infusedOnyxChestplate = (new RioVArmor(Config.addItem("Infused Onyx Chestplate"), InfusedOnyxArmorMaterial, render, 1, "onyx", true)).setUnlocalizedName("infusedOnyxChestplate");;
	public static Item infusedOnyxLeggings = (new RioVArmor(Config.addItem("Infused Onyx Leggings"), InfusedOnyxArmorMaterial, render, 2, "onyx", true)).setUnlocalizedName("infusedOnyxLeggings");;
	public static Item infusedOnyxBoots = (new RioVArmor(Config.addItem("Infused Onyx Boots"), InfusedOnyxArmorMaterial, render, 3, "onyx", true)).setUnlocalizedName("infusedOnyxBoots");;
	public static Item infusedAmethystHelmet = (new RioVArmor(Config.addItem("Infused Amethyst Helmet"), InfusedAmethystArmorMaterial, render, 0, "amethyst", true)).setUnlocalizedName("infusedAmethystHelmet");
	public static Item infusedAmethystChestplate = (new RioVArmor(Config.addItem("Infused Amethyst Chestplate"), InfusedAmethystArmorMaterial, render, 1, "amethyst", true)).setUnlocalizedName("infusedAmethystChestplate");
	public static Item infusedAmethystLeggings = (new RioVArmor(Config.addItem("Infused Amethyst Leggings"), InfusedAmethystArmorMaterial, render, 2, "amethyst", true)).setUnlocalizedName("infusedAmethystLeggings");
	public static Item infusedAmethystBoots = (new RioVArmor(Config.addItem("Infused Amethyst Boots"), InfusedAmethystArmorMaterial, render, 3, "amethyst", true)).setUnlocalizedName("infusedAmethystBoots");
	public static Item auntunMinionHelmet = (new RioVArmor(Config.addItem("Aun'Tun Minion Helmet"), AunTunArmorMaterial, render, 0, "auntunminion", false)).setUnlocalizedName("auntunminionHelmet");
	public static Item auntunMinionChestplate = (new RioVArmor(Config.addItem("Aun'Tun Minion Chestplate"), AunTunArmorMaterial, render, 1, "auntunminion", false)).setUnlocalizedName("auntunminionChestplate");
	public static Item auntunMinionLeggings = (new RioVArmor(Config.addItem("Aun'Tun Minion Leggings"), AunTunArmorMaterial, render, 2, "auntunminion", false)).setUnlocalizedName("auntunminionLeggings");
	public static Item auntunMinionBoots = (new RioVArmor(Config.addItem("Aun'Tun Minion Boots"), AunTunArmorMaterial, render, 3, "auntunminion", false)).setUnlocalizedName("auntunminionBoots");
	public static Item garnetHelmet = (new RioVArmor(Config.addItem("Garnet Helmet"), GarnetArmorMaterial, render, 0, "garnet", false)).setUnlocalizedName("garnetHelmet");
	public static Item garnetChestplate = (new RioVArmor(Config.addItem("Garnet Chestplate"), GarnetArmorMaterial, render, 1, "garnet", false)).setUnlocalizedName("garnetChestplate");
	public static Item garnetLeggings = (new RioVArmor(Config.addItem("Garnet Leggings"), GarnetArmorMaterial, render, 2, "garnet", false)).setUnlocalizedName("garnetLeggings");
	public static Item garnetBoots = (new RioVArmor(Config.addItem("Garnet Boots"), GarnetArmorMaterial, render, 3, "garnet", false)).setUnlocalizedName("garnetBoots");
	public static Item mythrilHelmet = (new RioVArmor(Config.addItem("Mythril Helmet"), MythrilArmorMaterial, render, 0, "mythril", false)).setUnlocalizedName("mythrilHelmet");
	public static Item mythrilChestplate = (new RioVArmor(Config.addItem("Mythril Chestplate"), MythrilArmorMaterial, render, 1, "mythril", false)).setUnlocalizedName("mythrilChestplate");
	public static Item mythrilLeggings = (new RioVArmor(Config.addItem("Mythril Leggings"), MythrilArmorMaterial, render, 2, "mythril", false)).setUnlocalizedName("mythrilLeggings");
	public static Item mythrilBoots = (new RioVArmor(Config.addItem("Mythril Boots"), MythrilArmorMaterial, render, 3, "mythril", false)).setUnlocalizedName("mythrilBoots");
	public static Item dragonHelmet = (new RioVArmor(Config.addItem("Dragon Helmet"), DragonArmorMaterial, render, 0, "dragon", false)).setUnlocalizedName("dragonHelmet");
	public static Item dragonChestplate = (new RioVArmor(Config.addItem("Dragon Chestplate"), DragonArmorMaterial, render, 1, "dragon", false)).setUnlocalizedName("dragonChestplate");
	public static Item dragonLeggings = (new RioVArmor(Config.addItem("Dragon Leggings"), DragonArmorMaterial, render, 2, "dragon", false)).setUnlocalizedName("dragonLeggings");
	public static Item dragonBoots = (new RioVArmor(Config.addItem("Dragon Boots"), DragonArmorMaterial, render, 3, "dragon", false)).setUnlocalizedName("dragonBoots");
	public static Item amethystSword = (new RioVWeapon(Config.addItem("Amethyst Sword"), Amethyst, false)).setUnlocalizedName("amethystSword");
	public static Item infusedAmethystSword = (new RioVWeapon(Config.addItem("Infused Amethyst Sword"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystSword");
	public static Item darkenedAmethystSword = (new RioVWeapon(Config.addItem("Darkened Amethyst Sword"), DarkenedAmethyst, false)).setUnlocalizedName("darkenedAmethystSword");
	public static Item darkenedInfusedAmethystSword = (new RioVWeapon(Config.addItem("Darkened Infused Amethyst Sword"), DarkenedInfusedAmethyst, true)).setUnlocalizedName("darkenedInfusedAmethystSword");
	public static Item onyxSword = (new RioVWeapon(Config.addItem("Onyx Sword"), Onyx, false)).setUnlocalizedName("onyxSword");
	public static Item infusedOnyxSword = (new RioVWeapon(Config.addItem("Infused Onyx Sword"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxSword");
	public static Item darkenedOnyxSword = (new RioVWeapon(Config.addItem("Darkened Onyx Sword"), DarkenedOnyx, false)).setUnlocalizedName("darkenedOnyxSword");
	public static Item darkenedInfusedOnyxSword = (new RioVWeapon(Config.addItem("Darkened Infused Onyx Sword"), DarkenedInfusedOnyx, true)).setUnlocalizedName("darkenedInfusedOnyxSword");
	public static Item bladeOfAni = (new RioVWeapon(Config.addItem("Blade of Ani"), Ani, false)).setUnlocalizedName("bladeOfAni");
	public static Item nizonianBlade = (new RioVWeapon(Config.addItem("Nizonian Blade"), Nizonian, false)).setUnlocalizedName("nizonianBlade");
	public static Item daetoriSword = (new RioVWeapon(Config.addItem("Daetori's Sword"), Daetori, false)).setUnlocalizedName("daetoriSword");
	public static Item sorrowSword = (new RioVWeapon(Config.addItem("Sorrow Sword"), Sorrow, false)).setUnlocalizedName("sorrowSword");
	public static Item axeOfAunTun = (new RioVWeapon(Config.addItem("Axe of Aun'Tun"), AxeOfAunTun, false)).setUnlocalizedName("axeOfAunTun");
	public static Item slateHandaxe = (new RioVWeapon(Config.addItem("Slate Handaxe"), Slate, false)).setUnlocalizedName("slateHandaxe");
	public static Item sharpenedSlateHandaxe = (new RioVWeapon(Config.addItem("Sharpened Slate Handaxe"), SharpenedSlate, false)).setUnlocalizedName("sharpenedSlateHandaxe");
	public static Item dragonSword = (new RioVWeapon(Config.addItem("Sharpened Slate Handaxe"), Dragon, false)).setUnlocalizedName("dragonSword");
	public static Item vulronSword = (new RioVWeapon(Config.addItem("Vulron Sword"), Vulron, false)).setUnlocalizedName("vulronSword");
	public static Item onyxPickaxe = (new RioVPickaxe(Config.addItem("Onyx Pickaxe"), Onyx, false)).setUnlocalizedName("onyxPickaxe");
	public static Item onyxAxe = (new RioVAxe(Config.addItem("Onyx Axe"), Onyx, false)).setUnlocalizedName("onyxAxe");
	public static Item onyxShovel = (new RioVSpade(Config.addItem("Onyx Shovel"), Onyx, false)).setUnlocalizedName("onyxShovel");
	public static Item amethystPickaxe = (new RioVPickaxe(Config.addItem("Amethyst Pickaxe"), Amethyst, false)).setUnlocalizedName("amethystPickaxe");
	public static Item amethystAxe = (new RioVAxe(Config.addItem("Amethyst Axe"), Amethyst, false)).setUnlocalizedName("amethystAxe");
	public static Item amethystShovel = (new RioVSpade(Config.addItem("Amethyst Shovel"), Amethyst, false)).setUnlocalizedName("amethystShovel");
	public static Item infusedAmethystPickaxe = (new RioVPickaxe(Config.addItem("Infused Amethyst Pickaxe"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystPickaxe");
	public static Item infusedAmethystAxe = (new RioVAxe(Config.addItem("Infused Amethyst Axe"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystAxe");
	public static Item infusedAmethystShovel = (new RioVSpade(Config.addItem("Infused Amethyst Shovel"), InfusedAmethyst, true)).setUnlocalizedName("infusedAmethystShovel");
	public static Item infusedOnyxPickaxe = (new RioVPickaxe(Config.addItem("Infused Onyx Pickaxe"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxPickaxe");
	public static Item infusedOnyxAxe = (new RioVAxe(Config.addItem("Infused Onyx Axe"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxAxe");
	public static Item infusedOnyxShovel = (new RioVSpade(Config.addItem("Infused Onyx Shovel"), InfusedOnyx, true)).setUnlocalizedName("infusedOnyxShovel");
	public static Item agonitePickaxe = (new RioVPickaxe(Config.addItem("Agonite Pickaxe"), Agonite, false)).setUnlocalizedName("agonitePickaxe");
	public static Item dragonPickaxe = (new RioVPickaxe(Config.addItem("Dragon Pickaxe"), Dragon, false)).setUnlocalizedName("dragonPickaxe");
	public static Item dragonAxe = (new RioVAxe(Config.addItem("Dragon Axe"), Dragon, false)).setUnlocalizedName("dragonAxe");
	public static Item dragonShovel = (new RioVSpade(Config.addItem("Dragon Shovel"), Dragon, false)).setUnlocalizedName("dragonShovel");
	public static Item amethyst = (new RioVItem(Config.addItem("Amethyst"))).setUnlocalizedName("amethyst");
	public static Item onyx = (new RioVItem(Config.addItem("Onyx"))).setUnlocalizedName("onyx");
	public static Item blackBone = (new RioVItem(Config.addItem("Black Bone"))).setUnlocalizedName("blackBone");
	public static Item orb = (new RioVItem(Config.addItem("Orb"))).setUnlocalizedName("orb");
	public static Item slateFragment = (new RioVItem(Config.addItem("Slate Fragment"))).setUnlocalizedName("slateFragment");
	public static Item garnet = (new RioVItem(Config.addItem("Garnet"))).setUnlocalizedName("garnet");
	public static Item agonite = (new RioVItem(Config.addItem("Agonite"))).setUnlocalizedName("agonite");
	public static Item darkMatter = (new RioVItem(Config.addItem("Dark Matter"))).setUnlocalizedName("darkMatter");
	public static Item mythrilIngot = (new RioVItem(Config.addItem("Mythril Ingot"))).setUnlocalizedName("mythrilIngot");
	public static Item dragonSoul = (new RioVItem(Config.addItem("Dragon Soul Gem"))).setUnlocalizedName("dragonSoul");
	public static Item nironite = (new RioVItem(Config.addItem("Nironite"))).setUnlocalizedName("nironite");
	public static Item burnedQuartz = (new RioVItem(Config.addItem("Black Quartz"))).setUnlocalizedName("burnedQuartz");
	public static Item vulron = (new RioVItem(Config.addItem("Vulron"))).setUnlocalizedName("vulron");
	public static Item darknessArrow = (new RioVItem(Config.addItem("Darkness Arrow"))).setUnlocalizedName("darknessArrow");
	public static Item UnfusedaxeOfAunTun = (new RioVWeapon(Config.addItem("Unfused Axe of Aun'Tun"), Training, false)).setUnlocalizedName("UnfusedaxeOfAunTun");
	public static Item HalfFusedaxeOfAunTun = (new RioVWeapon(Config.addItem("Half Fused Axe of Aun'Tun"), Training, false)).setUnlocalizedName("HalfFusedaxeOfAunTun");
	public static Item ambrosia = (new RioVConsumable(Config.addItem("Ambrosia"), 6, 0, false)).setUnlocalizedName("ambrosia");
	public static Item tomato = (new RioVConsumable(Config.addItem("Tomato"), 5, 0, false)).setUnlocalizedName("tomato");
	public static Item cookedHorseMeat = (new RioVConsumable(Config.addItem("Cooked Horse Meat"), 5, 0, false)).setUnlocalizedName("cookedHorseMeat");
	public static Item horseMeat = (new RioVConsumable(Config.addItem("Horse Meat"), 3, 0, false)).setUnlocalizedName("horseMeat");
	public static Item blackDurii = (new RioVConsumable(Config.addItem("Black Durii"), 3, 0, false)).setUnlocalizedName("blackDurii");
	public static Item baseCrystal = (new RioVItem(Config.addItem("Base Crystal"))).setUnlocalizedName("baseCrystal");
	public static Item terronCrystal = (new RioVSummoners(Config.addItem("Terron Crystal"))).setUnlocalizedName("terronCrystal");
	public static Item demonAngelCrystal = (new RioVSummoners(Config.addItem("Demon Angel Crystal"))).setUnlocalizedName("demonAngelCrystal");
	public static Item auntunSummoner = (new RioVSummoners(Config.addItem("Aun'Tun Summoner"))).setCreativeTab(null).setUnlocalizedName("auntunSummoner");
	public static Item khuulisScythe = (new RioVWeapon(Config.addItem("Khuuli's Scythe"), Onyx, false)).setUnlocalizedName("khuulisScythe");
	public static Item shifter = (new RioVWeapon(Config.addItem("Shifter"), Amethyst, false)).setUnlocalizedName("shifter");
	public static Item bowOfWurTun = (new ItemBowOfWurTun(Config.addItem("Bow of Wur'Tun"))).setUnlocalizedName("bowOfWurTun");
	public static Item wineGlass = (new RioVItem(Config.addItem("Wine Glass"))).setUnlocalizedName("wineGlass");
	public static Item potionGlass = (new RioVPotions(Config.addItem("Potion Glass"), 0)).setUnlocalizedName("potionGlass");
	public static Item grapes = (new RioVConsumable(Config.addItem("Grapes"), 3, 0, true)).setUnlocalizedName("grapes");
	public static Item wine = (new RioVDrinkable(Config.addItem("Wine"), 2, 0, true)).setUnlocalizedName("wine");
	public static Item greenApple = (new RioVConsumable(Config.addItem("Green Apple"), 4, 0, true)).setUnlocalizedName("greenApple");
	public static Item spicedWine = (new RioVDrinkable(Config.addItem("Spiced Wine"), 3, 0, true)).setUnlocalizedName("spicedWine");
	public static Item pepper = (new RioVConsumable(Config.addItem("Pepper"), 2, 0, true)).setUnlocalizedName("pepper");
	public static Item pepperSpices = (new RioVConsumable(Config.addItem("Pepper Spices"), 1, 0, true)).setUnlocalizedName("pepperSpices");
	public static Item sapphire = (new RioVItem(Config.addItem("Sapphire"))).setUnlocalizedName("sapphire");
	public static Item sapphirePickaxe = (new RioVPickaxe(Config.addItem("Sapphire Pickaxe"), Sapphire, false)).setUnlocalizedName("sapphirePickaxe");
	public static Item sapphireAxe = (new RioVAxe(Config.addItem("Sapphire Axe"), Sapphire, false)).setUnlocalizedName("sapphireAxe");
	public static Item sapphireShovel = (new RioVSpade(Config.addItem("Sapphire Shovel"), Sapphire, false)).setUnlocalizedName("sapphireShovel");
	public static Item sapphireSword = (new RioVWeapon(Config.addItem("Sapphire Sword"), Sapphire, false)).setUnlocalizedName("sapphireSword");
	public static Item sapphireHelmet = (new RioVArmor(Config.addItem("Sapphire Helmet"), SapphireArmorMaterial, render, 0, "sapphire", false)).setUnlocalizedName("sapphireHelmet");
	public static Item sapphireChestplate = (new RioVArmor(Config.addItem("Sapphire Chestplate"), SapphireArmorMaterial, render, 1, "sapphire", false)).setUnlocalizedName("sapphireChestplate");
	public static Item sapphireLeggings = (new RioVArmor(Config.addItem("Sapphire Leggings"), SapphireArmorMaterial, render, 2, "sapphire", false)).setUnlocalizedName("sapphireLeggings");
	public static Item sapphireBoots = (new RioVArmor(Config.addItem("Sapphire Boots"), SapphireArmorMaterial, render, 3, "sapphire", false)).setUnlocalizedName("sapphireBoots");
	public static Item opal = (new RioVItem(Config.addItem("Opal"))).setUnlocalizedName("opal");
	public static Item topaz = (new RioVItem(Config.addItem("Mystic Topaz"))).setUnlocalizedName("topaz");
	public static Item topazPickaxe = (new RioVPickaxe(Config.addItem("Mystic Topaz Pickaxe"), Topaz, false)).setUnlocalizedName("topazPickaxe");
	public static Item topazAxe = (new RioVAxe(Config.addItem("Mystic Topaz Axe"), Topaz, false)).setUnlocalizedName("topazAxe");
	public static Item topazShovel = (new RioVSpade(Config.addItem("Mystic Topaz Shovel"), Topaz, false)).setUnlocalizedName("topazShovel");
	public static Item topazSword = (new RioVWeapon(Config.addItem("Mystic Topaz Sword"), Topaz, false)).setUnlocalizedName("topazSword");
	public static Item topazHelmet = (new RioVArmor(Config.addItem("Mystic Topaz Helmet"), TopazArmorMaterial, render, 0, "topaz", false)).setUnlocalizedName("topazHelmet");
	public static Item topazChestplate = (new RioVArmor(Config.addItem("Mystic Topaz Chestplate"), TopazArmorMaterial, render, 1, "topaz", false)).setUnlocalizedName("topazChestplate");
	public static Item topazLeggings = (new RioVArmor(Config.addItem("Mystic Topaz Leggings"), TopazArmorMaterial, render, 2, "topaz", false)).setUnlocalizedName("topazLeggings");
	public static Item topazBoots = (new RioVArmor(Config.addItem("Mystic Topaz Boots"), TopazArmorMaterial, render, 3, "topaz", false)).setUnlocalizedName("topazBoots");
	public static Item manchet = (new RioVConsumable(Config.addItem("Manchet"), 6, 0, true)).setUnlocalizedName("manchet");
	public static Item cherry = (new RioVConsumable(Config.addItem("Cherry"), 8, 0, true)).setUnlocalizedName("cherry");
	public static Item silverCoin = (new RioVItem(Config.addItem("Silver Coin"))).setUnlocalizedName("silverCoin");
	public static Item goldCoin = (new RioVItem(Config.addItem("Gold Coin"))).setUnlocalizedName("goldCoin");
	public static Item trainingSword = (new RioVWeapon(Config.addItem("Training Sword"), Training, false)).setUnlocalizedName("trainingSword");
	public static Item galokinHelmet = (new RioVArmor(Config.addItem("Galokin Helmet"), GalokinArmorMaterial, render, 0, "galokin", false)).setUnlocalizedName("galokinHelmet");
	public static Item galokinChestplate = (new RioVArmor(Config.addItem("Galokin Chestplate"), GalokinArmorMaterial, render, 1, "galokin", false)).setUnlocalizedName("galokinChestplate");
	public static Item galokinLeggings = (new RioVArmor(Config.addItem("Galokin Leggings"), GalokinArmorMaterial, render, 2, "galokin", false)).setUnlocalizedName("galokinLeggings");
	public static Item galokinBoots = (new RioVArmor(Config.addItem("Galokin Boots"), GalokinArmorMaterial, render, 3, "galokin", false)).setUnlocalizedName("galokinBoots");
	public static Item galokinSword = (new RioVWeapon(Config.addItem("Galokin Sword"), Galokin, false)).setUnlocalizedName("galokinSword");
	public static Item galokinCrystal = (new RioVItem(Config.addItem("Galokin Crystal"))).setUnlocalizedName("galokinCrystal");
	public static Item clothOfMagic = (new RioVItem(Config.addItem("Cloth of Magic"))).setUnlocalizedName("clothOfMagic");
	public static Item magickaHelmet = (new RioVArmor(Config.addItem("Magicka Helmet"), EnumArmorMaterial.CHAIN, render, 0, "magic", true)).setUnlocalizedName("magickaHelmet");
	public static Item magickaChestplate = (new RioVArmor(Config.addItem("Magicka Chestplate"), EnumArmorMaterial.CHAIN, render, 1, "magic", true)).setUnlocalizedName("magickaChestplate");
	public static Item magickaLeggings = (new RioVArmor(Config.addItem("Magicka Leggings"), EnumArmorMaterial.CHAIN, render, 2, "magic", true)).setUnlocalizedName("magickaLeggings");
	public static Item magickaBoots = (new RioVArmor(Config.addItem("Magicka Boots"), EnumArmorMaterial.CHAIN, render, 3, "magic", true)).setUnlocalizedName("magickaBoots");
	public static Item theDarknessCrystal = (new RioVSummoners(Config.addItem("The Darkness Crystal"))).setUnlocalizedName("theDarknessCrystal");
	public static Item infusedSapphirePickaxe = (new RioVPickaxe(Config.addItem("Infused Sapphire Pickaxe"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphirePickaxe");
	public static Item infusedSapphireAxe = (new RioVAxe(Config.addItem("Infused Sapphire Axe"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireAxe");
	public static Item infusedSapphireShovel = (new RioVSpade(Config.addItem("Infused Sapphire Shovel"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireShovel");
	public static Item infusedSapphireSword = (new RioVWeapon(Config.addItem("Infused Sapphire Sword"), InfusedSapphire, true)).setUnlocalizedName("infusedSapphireSword");
	public static Item infusedSapphireHelmet = (new RioVArmor(Config.addItem("Infused Sapphire Helmet"), InfusedSapphireArmorMaterial, render, 0, "sapphire", true)).setUnlocalizedName("infusedSapphireHelmet");
	public static Item infusedSapphireChestplate = (new RioVArmor(Config.addItem("Infused Sapphire Chestplate"), InfusedSapphireArmorMaterial, render, 1, "sapphire", true)).setUnlocalizedName("infusedSapphireChestplate");
	public static Item infusedSapphireLeggings = (new RioVArmor(Config.addItem("Infused Sapphire Leggings"), InfusedSapphireArmorMaterial, render, 2, "sapphire", true)).setUnlocalizedName("infusedSapphireLeggings");
	public static Item infusedSapphireBoots = (new RioVArmor(Config.addItem("Infused Sapphire Boots"), InfusedSapphireArmorMaterial, render, 3, "sapphire", true)).setUnlocalizedName("infusedSapphireBoots");
	public static Item infusedTopazPickaxe = (new RioVPickaxe(Config.addItem("Infused Mystic Topaz Pickaxe"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazPickaxe");
	public static Item infusedTopazAxe = (new RioVAxe(Config.addItem("Infused Mystic Topaz Axe"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazAxe");
	public static Item infusedTopazShovel = (new RioVSpade(Config.addItem("Infused Mystic Topaz Shovel"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazShovel");
	public static Item infusedTopazSword = (new RioVWeapon(Config.addItem("Infused Mystic Topaz Sword"), InfusedTopaz, true)).setUnlocalizedName("infusedTopazSword");
	public static Item infusedTopazHelmet = (new RioVArmor(Config.addItem("Infused Mystic Topaz Helmet"), InfusedTopazArmorMaterial, render, 0, "topaz", true)).setUnlocalizedName("infusedTopazHelmet");
	public static Item infusedTopazChestplate = (new RioVArmor(Config.addItem("Infused Mystic Topaz Chestplate"), InfusedTopazArmorMaterial, render, 1, "topaz", true)).setUnlocalizedName("infusedTopazChestplate");
	public static Item infusedTopazLeggings = (new RioVArmor(Config.addItem("Infused Mystic Topaz Leggings"), InfusedTopazArmorMaterial, render, 2, "topaz", true)).setUnlocalizedName("infusedTopazLeggings");
	public static Item infusedTopazBoots = (new RioVArmor(Config.addItem("Infused Mystic Topaz Boots"), InfusedTopazArmorMaterial, render, 3, "topaz", true)).setUnlocalizedName("infusedTopazBoots");
	public static Item darkenedTopazSword = (new RioVWeapon(Config.addItem("Darkened Mystic Topaz Sword"), DarkenedTopaz, false)).setUnlocalizedName("darkenedTopazSword");
	public static Item darkenedSapphireSword = (new RioVWeapon(Config.addItem("Darkened Sapphire Sword"), DarkenedSapphire, false)).setUnlocalizedName("darkenedSapphireSword");
	public static Item darkenedInfusedTopazSword = (new RioVWeapon(Config.addItem("Darkened Infused Mystic Topaz Sword"), DarkenedInfusedTopaz, true)).setUnlocalizedName("darkenedInfusedTopazSword");
	public static Item darkenedInfusedSapphireSword = (new RioVWeapon(Config.addItem("Darkened Infused Sapphire Sword"), DarkenedInfusedSapphire, true)).setUnlocalizedName("darkenedInfusedSapphireSword");
	public static Item ingotOfFlame = (new RioVItem(Config.addItem("Ingot of Flame"))).setUnlocalizedName("ingotOfFlame");
	public static Item swordOfFlame = (new RioVWeapon(Config.addItem("Sword of Flame"), Flame, false)).setUnlocalizedName("swordOfFlame");
	public static Item purpleFeather = (new RioVItem(Config.addItem("Purple Feather"))).setUnlocalizedName("purpleFeather");
	public static Item helmetOfFlame = (new RioVArmor(Config.addItem("Helmet of Flame"), FlameArmorMaterial, render, 0, "flame", false)).setUnlocalizedName("helmetOfFlame");
	public static Item chestplateOfFlame = (new RioVArmor(Config.addItem("Chestplate of Flame"), FlameArmorMaterial, render, 1, "flame", false)).setUnlocalizedName("chestplateOfFlame");
	public static Item leggingsOfFlame = (new RioVArmor(Config.addItem("Leggings of Flame"), FlameArmorMaterial, render, 2, "flame", false)).setUnlocalizedName("leggingsOfFlame");
	public static Item bootsOfFlame = (new RioVArmor(Config.addItem("Boots of Flame"), FlameArmorMaterial, render, 3, "flame", false)).setUnlocalizedName("bootsOfFlame");
	public static Item infusedDragonHelmet = (new RioVArmor(Config.addItem("Infused Dragon Helmet"), InfusedDragonArmorMaterial, render, 0, "dragon", true)).setUnlocalizedName("infusedDragonHelmet");
	public static Item infusedDragonChestplate = (new RioVArmor(Config.addItem("Infused Dragon Chestplate"), InfusedDragonArmorMaterial, render, 1, "dragon", true)).setUnlocalizedName("infusedDragonChestplate");
	public static Item infusedDragonLeggings = (new RioVArmor(Config.addItem("Infused Dragon Leggings"), InfusedDragonArmorMaterial, render, 2, "dragon", true)).setUnlocalizedName("infusedDragonLeggings");
	public static Item infusedDragonBoots = (new RioVArmor(Config.addItem("Infused Dragon Boots"), InfusedDragonArmorMaterial, render, 3, "dragon", true)).setUnlocalizedName("infusedDragonBoots");
	public static Item infusedDragonSword = (new RioVWeapon(Config.addItem("Infused Dragon Sword"), InfusedDragon, true)).setUnlocalizedName("infusedDragonSword");
	public static Item infusedDragonPickaxe = (new RioVPickaxe(Config.addItem("Infused Dragon Pickaxe"), InfusedDragon, true)).setUnlocalizedName("infusedDragonPickaxe");
	public static Item infusedDragonAxe = (new RioVAxe(Config.addItem("Infused Dragon Axe"), InfusedDragon, true)).setUnlocalizedName("infusedDragonAxe");
	public static Item infusedDragonShovel = (new RioVSpade(Config.addItem("Infused Dragon Shovel"), InfusedDragon, true)).setUnlocalizedName("infusedDragonShovel");
	public static Item darkenedDragonSword = (new RioVWeapon(Config.addItem("Darkened Dragon Sword"), DarkenedDragon, false)).setUnlocalizedName("darkenedDragonSword");
	public static Item darkenedInfusedDragonSword = (new RioVWeapon(Config.addItem("Darkened Infused Dragon Sword"), DarkenedInfusedDragon, true)).setUnlocalizedName("darkenedInfusedDragonSword");
	public static Item enforcedBowOfWurTun = (new ItemEnforcedBowOfWurTun(Config.addItem("Enforced Bow of Wur'Tun"))).setUnlocalizedName("enforcedbowOfWurTun");
	public static Item longbow = (new ItemLongBow(Config.addItem("Longbow"))).setUnlocalizedName("longbow");
	public static Item blindonite = (new RioVItem(Config.addItem("Blindonite"))).setUnlocalizedName("blindonite");
	public static Item blindOasisActivator = (new RioVActivators(Config.addItem("Blind Oasis Activator"))).setUnlocalizedName("blindOasisActivator");
	public static Item tefHelmet = (new RioVArmor(Config.addItem("Tef Helmet"), FlameArmorMaterial, render, 0, "tef", false)).setUnlocalizedName("tefHelmet");
	public static Item tefChestplate = (new RioVArmor(Config.addItem("Tef Chestplate"), FlameArmorMaterial, render, 1, "tef", false)).setUnlocalizedName("tefChestplate");
	public static Item tefLeggings = (new RioVArmor(Config.addItem("Tef Leggings"), FlameArmorMaterial, render, 2, "tef", false)).setUnlocalizedName("tefLeggings");
	public static Item tefBoots = (new RioVArmor(Config.addItem("Tef Boots"), FlameArmorMaterial, render, 3, "tef", false)).setUnlocalizedName("tefBoots");
	public static Item tefCrystal = (new RioVSummoners(Config.addItem("Tef Crystal"))).setUnlocalizedName("tefCrystal");
	public static Item blindoniteHelmet = (new RioVArmor(Config.addItem("Blindonite Helmet"), BlindoniteArmorMaterial, render, 0, "blindonite", false)).setUnlocalizedName("blindoniteHelmet");
	public static Item blindoniteChestplate = (new RioVArmor(Config.addItem("Blindonite Chestplate"), BlindoniteArmorMaterial, render, 1, "blindonite", false)).setUnlocalizedName("blindoniteChestplate");
	public static Item blindoniteLeggings = (new RioVArmor(Config.addItem("Blindonite Leggings"), BlindoniteArmorMaterial, render, 2, "blindonite", false)).setUnlocalizedName("blindoniteLeggings");
	public static Item blindoniteBoots = (new RioVArmor(Config.addItem("Blindonite Boots"), BlindoniteArmorMaterial, render, 3, "blindonite", false)).setUnlocalizedName("blindoniteBoots");
	public static Item blindonitePickaxe = (new RioVPickaxe(Config.addItem("Blindonite Pickaxe"), Blindonite, false)).setUnlocalizedName("blindonitePickaxe");
	public static Item blindoniteAxe = (new RioVAxe(Config.addItem("Blindonite Axe"), Blindonite, false)).setUnlocalizedName("blindoniteAxe");
	public static Item blindoniteShovel = (new RioVSpade(Config.addItem("Blindonite Shovel"), Blindonite, false)).setUnlocalizedName("blindoniteShovel");
	public static Item blindoniteSword = (new RioVWeapon(Config.addItem("Blindonite Sword"), Blindonite, false)).setUnlocalizedName("blindoniteSword");
	public static Item infusedBlindoniteHelmet = (new RioVArmor(Config.addItem("Infused Blindonite Helmet"), InfusedBlindoniteArmorMaterial, render, 0, "blindonite", true)).setUnlocalizedName("infusedBlindoniteHelmet");
	public static Item infusedBlindoniteChestplate = (new RioVArmor(Config.addItem("Infused Blindonite Chestplate"), InfusedBlindoniteArmorMaterial, render, 1, "blindonite", true)).setUnlocalizedName("infusedBlindoniteChestplate");
	public static Item infusedBlindoniteLeggings = (new RioVArmor(Config.addItem("Infused Blindonite Leggings"), InfusedBlindoniteArmorMaterial, render, 2, "blindonite", true)).setUnlocalizedName("infusedBlindoniteLeggings");
	public static Item infusedBlindoniteBoots = (new RioVArmor(Config.addItem("Infused Blindonite Boots"), InfusedBlindoniteArmorMaterial, render, 3, "blindonite", true)).setUnlocalizedName("infusedBlindoniteBoots");
	public static Item infusedBlindonitePickaxe = (new RioVPickaxe(Config.addItem("Infused Blindonite Pickaxe"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindonitePickaxe");
	public static Item infusedBlindoniteAxe = (new RioVAxe(Config.addItem("Infused Blindonite Axe"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteAxe");
	public static Item infusedBlindoniteShovel = (new RioVSpade(Config.addItem("Infused Blindonite Shovel"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteShovel");
	public static Item infusedBlindoniteSword = (new RioVWeapon(Config.addItem("Infused Blindonite Sword"), InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteSword");
	public static Item vaerynActivator = (new RioVActivators(Config.addItem("Vaeryn Activator"))).setUnlocalizedName("vaerynActivator");
	public static Item glimmerwoodSticks = (new RioVItem(Config.addItem("Glimmerwood Sticks"))).setUnlocalizedName("glimmerwoodSticks");
	public static Item glimmerwoodPickaxe = (new RioVPickaxe(Config.addItem("Glimmerwood Pickaxe"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodPickaxe");
	public static Item glimmerwoodAxe = (new RioVAxe(Config.addItem("Glimmerwood Axe"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodAxe");
	public static Item glimmerwoodShovel = (new RioVSpade(Config.addItem("Glimmerwood Shovel"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodShovel");
	public static Item glimmerwoodSword = (new RioVWeapon(Config.addItem("Glimmerwood Sword"), Glimmerwood, false)).setUnlocalizedName("glimmerwoodSword");
	public static Item blueMagicApple = (new RioVConsumable(Config.addItem("Magical Blue Apple"), 8, 0, true)).setUnlocalizedName("blueApple");
	public static Item vraviniteBow = (new ItemVraviniteBow(Config.addItem("Vravinite Bow"))).setUnlocalizedName("vraviniteBow");
	public static Item vraviniteArrow = (new RioVItem(Config.addItem("Vravinite Arrow"))).setUnlocalizedName("vraviniteArrow");
	public static Item vravinite = (new RioVItem(Config.addItem("Vravinite"))).setUnlocalizedName("vravinite");
	public static Item vraviniteHelmet = (new RioVArmor(Config.addItem("Vravinite Helmet"), VraviniteArmorMaterial, render, 0, "vravinite", false)).setUnlocalizedName("vraviniteHelmet");
	public static Item vraviniteChestplate = (new RioVArmor(Config.addItem("Vravinite Chestplate"), VraviniteArmorMaterial, render, 1, "vravinite", false)).setUnlocalizedName("vraviniteChestplate");
	public static Item vraviniteLeggings = (new RioVArmor(Config.addItem("Vravinite Leggings"), VraviniteArmorMaterial, render, 2, "vravinite", false)).setUnlocalizedName("vraviniteLeggings");
	public static Item vraviniteBoots = (new RioVArmor(Config.addItem("Vravinite Boots"), VraviniteArmorMaterial, render, 3, "vravinite", false)).setUnlocalizedName("vraviniteBoots");
	public static Item vravinitePickaxe = (new RioVPickaxe(Config.addItem("Vravinite Pickaxe"), Vravinite, false)).setUnlocalizedName("vravinitePickaxe");
	public static Item vraviniteAxe = (new RioVAxe(Config.addItem("Vravinite Axe"), Vravinite, false)).setUnlocalizedName("vraviniteAxe");
	public static Item vraviniteShovel = (new RioVSpade(Config.addItem("Vravinite Shovel"), Vravinite, false)).setUnlocalizedName("vraviniteShovel");
	public static Item vraviniteSword = (new RioVWeapon(Config.addItem("Vravinite Sword"), Vravinite, false)).setUnlocalizedName("vraviniteSword");
	public static Item glimmerwoodDoorItem = (new RioVDoor(Config.addItem("Glimmerwood Door Item"), Material.wood)).setUnlocalizedName("glimmerwoodDoorItem");
	public static Item flamonorActivator = (new RioVActivators(Config.addItem("Flamonor Activator"))).setUnlocalizedName("flamonorActivator");
	public static Item drakiuz = (new RioVItem(Config.addItem("Drakiuz"))).setUnlocalizedName("drakiuz");
	public static Item fireballWand = (new RioVWand(Config.addItem("Fireball Wand"), 0, 1, 4)).setUnlocalizedName("fireballWand");
	public static Item cherryBlossomDoorItem = (new RioVDoor(Config.addItem("Cherry Blossom Door Item"), Material.wood)).setUnlocalizedName("cherryBlossomDoorItem");
	public static Item cherryBlossomSticks = (new RioVItem(Config.addItem("Cherry Blossom Sticks"))).setUnlocalizedName("cherryBlossomSticks");
	public static Item cherryBlossomPickaxe = (new RioVPickaxe(Config.addItem("Cherry Blossom Pickaxe"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomPickaxe");
	public static Item cherryBlossomAxe = (new RioVAxe(Config.addItem("Cherry Blossom Axe"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomAxe");
	public static Item cherryBlossomShovel = (new RioVSpade(Config.addItem("Cherry Blossom Shovel"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomShovel");
	public static Item cherryBlossomSword = (new RioVWeapon(Config.addItem("Cherry Blossom Sword"), CherryBlossom, false)).setUnlocalizedName("cherryBlossomSword");
	public static Item glimmerwoodBucket = (new RioVBucket(Config.addItem("Glimmerwood Bucket"), 0)).setUnlocalizedName("glimmerwoodBucket").setMaxStackSize(16);
	public static Item glimmerwoodBucketWater = (new RioVBucket(Config.addItem("Glimmerwood Bucket Water"), Block.waterMoving.blockID)).setUnlocalizedName("glimmerwoodBucketWater").setContainerItem(glimmerwoodBucket);
	public static Item glimmerwoodBucketLava = (new RioVBucket(Config.addItem("Glimmerwood Bucket Lava"), Block.lavaMoving.blockID)).setUnlocalizedName("glimmerwoodBucketLava").setContainerItem(glimmerwoodBucket);
	public static Item bloodBucket = (new RioVBucket(Config.addItem("Blood Bucket"), 0)).setUnlocalizedName("bloodBucket").setMaxStackSize(16);
	public static Item bloodBucketWater = (new RioVBucket(Config.addItem("Blood Bucket Water"), Block.waterMoving.blockID)).setUnlocalizedName("bloodBucketWater").setContainerItem(bloodBucket);
	public static Item bloodBucketLava = (new RioVBucket(Config.addItem("Blood Bucket Lava"), Block.lavaMoving.blockID)).setUnlocalizedName("bloodBucketLava").setContainerItem(bloodBucket);
	public static Item potionGlassSanctuatite = (new RioVPotions(Config.addItem("Potion Glass Sanctuatite"), Blocks.sanctuatiteMoving.blockID)).setUnlocalizedName("potionGlassSanctuatite");
	public static Item sanctuatiteActivator = (new RioVActivators(Config.addItem("Sanctuatite Activator"))).setUnlocalizedName("sanctuatiteActivator");
	public static Item skywoodDoorItem = (new RioVDoor(Config.addItem("Skywood Door Item"), Material.wood)).setUnlocalizedName("skywoodDoorItem");
	public static Item bloodDoorItem = (new RioVDoor(Config.addItem("Blood Door Item"), Material.wood)).setUnlocalizedName("bloodDoorItem");
	public static Item skywoodSticks = (new RioVItem(Config.addItem("Skywood Sticks"))).setUnlocalizedName("skywoodSticks");
	public static Item skywoodPickaxe = (new RioVPickaxe(Config.addItem("Skywood Pickaxe"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodPickaxe");
	public static Item skywoodAxe = (new RioVAxe(Config.addItem("Skywood Axe"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodAxe");
	public static Item skywoodShovel = (new RioVSpade(Config.addItem("Skywood Shovel"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodShovel");
	public static Item skywoodSword = (new RioVWeapon(Config.addItem("Skywood Sword"), EnumToolMaterial.STONE, false)).setUnlocalizedName("skywoodSword");
	public static Item bloodSticks = (new RioVItem(Config.addItem("Blood Sticks"))).setUnlocalizedName("bloodSticks");
	public static Item bloodPickaxe = (new RioVPickaxe(Config.addItem("Blood Pickaxe"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodPickaxe");
	public static Item bloodAxe = (new RioVAxe(Config.addItem("Blood Axe"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodAxe");
	public static Item bloodShovel = (new RioVSpade(Config.addItem("Blood Shovel"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodShovel");
	public static Item bloodSword = (new RioVWeapon(Config.addItem("Blood Sword"), EnumToolMaterial.WOOD, false)).setUnlocalizedName("bloodSword");
	public static Item sanctuaryStonePickaxe = (new RioVPickaxe(Config.addItem("Sanctuary Stone Pickaxe"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStonePickaxe");
	public static Item sanctuaryStoneAxe = (new RioVAxe(Config.addItem("Sanctuary Stone Axe"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneAxe");
	public static Item sanctuaryStoneShovel = (new RioVSpade(Config.addItem("Sanctuary Stone Shovel"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneShovel");
	public static Item sanctuaryStoneSword = (new RioVWeapon(Config.addItem("Sanctuary Stone Sword"), EnumToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneSword");
	public static Item aleris = (new RioVItem(Config.addItem("Aleris"))).setUnlocalizedName("aleris");
	public static Item alerisHelmet = (new RioVArmor(Config.addItem("Aleris Helmet"), AlerisArmorMaterial, render, 0, "aleris", false)).setUnlocalizedName("alerisHelmet");
	public static Item alerisChestplate = (new RioVArmor(Config.addItem("Aleris Chestplate"), AlerisArmorMaterial, render, 1, "aleris", false)).setUnlocalizedName("alerisChestplate");
	public static Item alerisLeggings = (new RioVArmor(Config.addItem("Aleris Leggings"), AlerisArmorMaterial, render, 2, "aleris", false)).setUnlocalizedName("alerisLeggings");
	public static Item alerisBoots = (new RioVArmor(Config.addItem("Aleris Boots"), AlerisArmorMaterial, render, 3, "aleris", false)).setUnlocalizedName("alerisBoots");
	public static Item alerisPickaxe = (new RioVPickaxe(Config.addItem("Aleris Pickaxe"), Aleris, false)).setUnlocalizedName("alerisPickaxe");
	public static Item alerisAxe = (new RioVAxe(Config.addItem("Aleris Axe"), Aleris, false)).setUnlocalizedName("alerisStoneAxe");
	public static Item alerisShovel = (new RioVSpade(Config.addItem("Aleris Shovel"), Aleris, false)).setUnlocalizedName("alerisShovel");
	public static Item alerisSword = (new RioVWeapon(Config.addItem("Aleris Sword"), Aleris, false)).setUnlocalizedName("alerisSword");
	public static Item onyxShield = (new RioVShield(Config.addItem("Onyx Shield"), Onyx, 1)).setUnlocalizedName("onyxShield");
	public static Item amethystShield = (new RioVShield(Config.addItem("Amethyst Shield"), Amethyst, 1)).setUnlocalizedName("amethystShield");
	public static Item vraviniteShield = (new RioVShield(Config.addItem("Vravinite Shield"), Vravinite, 5)).setUnlocalizedName("vraviniteShield");
	public static Item sapphireShield = (new RioVShield(Config.addItem("Sapphire Shield"), Sapphire, 1)).setUnlocalizedName("sapphireShield");
	public static Item topazShield = (new RioVShield(Config.addItem("Mystic Topaz Shield"), Topaz, 1)).setUnlocalizedName("topazShield");
	public static Item shieldOfFlame = (new RioVShield(Config.addItem("Shield of Flame"), Flame, 2)).setUnlocalizedName("shieldOfFlame");
	public static Item blindoniteShield = (new RioVShield(Config.addItem("Blindonite Shield"), Blindonite, 2)).setUnlocalizedName("blindoniteShield");
	public static Item woodenShield = (new RioVShield(Config.addItem("Wooden Shield"), EnumToolMaterial.WOOD, 0)).setUnlocalizedName("woodenShield");
	public static Item stoneShield = (new RioVShield(Config.addItem("Stone Shield"), EnumToolMaterial.STONE, 1)).setUnlocalizedName("stoneShield");
	public static Item ironShield = (new RioVShield(Config.addItem("Iron Shield"), EnumToolMaterial.IRON, 2)).setUnlocalizedName("ironShield");
	public static Item goldShield = (new RioVShield(Config.addItem("Gold Shield"), EnumToolMaterial.GOLD, 1)).setUnlocalizedName("goldShield");
	public static Item diamondShield = (new RioVShield(Config.addItem("Diamond Shield"), EnumToolMaterial.EMERALD, 4)).setUnlocalizedName("diamondShield");
	public static Item dragonShield = (new RioVShield(Config.addItem("Dragon Shield"), Dragon, 3)).setUnlocalizedName("dragonShield");
	public static Item auntunShield = (new RioVShield(Config.addItem("Aun'Tun Shield"), AxeOfAunTun, 4)).setUnlocalizedName("auntunShield");
	public static Item mythrilShield = (new RioVShield(Config.addItem("Mythril Shield"), Dragon, 3)).setUnlocalizedName("mythrilShield");
	public static Item galokinShield = (new RioVShield(Config.addItem("Galokin Shield"), Galokin, 2)).setUnlocalizedName("galokinShield");
	public static Item infusedVraviniteHelmet = (new RioVArmor(Config.addItem("Infused Vravinite Helmet"), InfusedVraviniteArmorMaterial, render, 0, "vravinite", true)).setUnlocalizedName("infusedVraviniteHelmet");
	public static Item infusedVraviniteChestplate = (new RioVArmor(Config.addItem("Infused Vravinite Chestplate"), InfusedVraviniteArmorMaterial, render, 1, "vravinite", true)).setUnlocalizedName("infusedVraviniteChestplate");
	public static Item infusedVraviniteLeggings = (new RioVArmor(Config.addItem("Infused Vravinite Leggings"), InfusedVraviniteArmorMaterial, render, 2, "vravinite", true)).setUnlocalizedName("infusedVraviniteLeggings");
	public static Item infusedVraviniteBoots = (new RioVArmor(Config.addItem("Infused Vravinite Boots"), InfusedVraviniteArmorMaterial, render, 3, "vravinite", true)).setUnlocalizedName("infusedVraviniteBoots");
	public static Item infusedVravinitePickaxe = (new RioVPickaxe(Config.addItem("Infused Vravinite Pickaxe"), InfusedVravinite, true)).setUnlocalizedName("infusedVravinitePickaxe");
	public static Item infusedVraviniteAxe = (new RioVAxe(Config.addItem("Infused Vravinite Axe"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteAxe");
	public static Item infusedVraviniteShovel = (new RioVSpade(Config.addItem("Infused Vravinite Shovel"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteShovel");
	public static Item infusedVraviniteSword = (new RioVWeapon(Config.addItem("Infused Vravinite Sword"), InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteSword");
	public static Item darkenedVraviniteSword = (new RioVWeapon(Config.addItem("Darkened Vravinite Sword"), DarkenedVravinite, false)).setUnlocalizedName("darkenedVraviniteSword");
	public static Item darkenedInfusedVraviniteSword = (new RioVWeapon(Config.addItem("Darkened Infused Vravinite Sword"), DarkenedInfusedVravinite, true)).setUnlocalizedName("darkenedInfusedVraviniteSword");
	public static Item voidHolder = (new RioVVoidHolder(Config.addItem("Void Holder"), 0)).setUnlocalizedName("voidHolder");
	public static Item voidHolderFilled = (new RioVVoidHolder(Config.addItem("Void Holder Filled"), Blocks.voidMoving.blockID)).setUnlocalizedName("voidHolder");
	public static Item berry = (new RioVConsumable(Config.addItem("Berry"), 4, 0, false)).setUnlocalizedName("berry");
	public static Item bambooItem = (new ItemBamboo(Config.addItem("Bamboo Item"), Blocks.bamboo)).setUnlocalizedName("bamboo");
	public static Item bambooPlanks = (new RioVItem(Config.addItem("Bamboo Planks"))).setUnlocalizedName("bambooPlank");
	public static Item blackBerry = (new RioVConsumable(Config.addItem("Blackberry"), 4, 0, false)).setUnlocalizedName("blackBerry");
	public static Item jaavik = (new RioVItem(Config.addItem("Jaavik"))).setUnlocalizedName("jaavik");
	public static Item raspBerry = (new RioVConsumable(Config.addItem("Raspberry"), 3, 0, false)).setUnlocalizedName("raspBerry");
	public static Item bloodBerry = (new RioVConsumable(Config.addItem("Bloodberry"), 6, 0, false)).setUnlocalizedName("bloodBerry");
	public static Item strawBerry = (new RioVConsumable(Config.addItem("Strawberry"), 3, 0, false)).setUnlocalizedName("strawBerry");

	/**PALADIN**/
	public static Item paladinHelmet;
	public static Item paladinChestplate;
	public static Item paladinLeggings;
	public static Item paladinBoots;
	public static Item paladinLongsword;

	public static void add()
	{		
		Registry.registerItem(blackBerry, "Blackberry");
		Registry.registerItem(raspBerry, "Raspberry");
		Registry.registerItem(bloodBerry, "Bloodberry");
		Registry.registerItem(strawBerry, "Strawberry");
		Registry.registerItem(jaavik, "Jaavik");
		Registry.registerItem(berry, "Berry");
		Registry.registerItem(bambooPlanks, "Bamboo Planks");
		Registry.registerItem(bambooItem, "Bamboo Rods");
		Registry.registerItem(voidHolderFilled, "Void Liquid Holder Filled");
		Registry.registerItem(voidHolder, "Void Liquid Holder");
		Registry.registerItem(darkenedVraviniteSword, "Darkened Vravinite Sword");
		Registry.registerItem(darkenedInfusedVraviniteSword, "Darkened Infused Vravinite Sword");
		Registry.registerItem(infusedVraviniteHelmet, "Infused Vravinite Helmet");
		Registry.registerItem(infusedVraviniteChestplate, "Infused Vravinite Chestplate");
		Registry.registerItem(infusedVraviniteLeggings, "Infused Vravinite Leggings");
		Registry.registerItem(infusedVraviniteBoots, "Infused Vravinite Boots");
		Registry.registerItem(infusedVravinitePickaxe, "Infused Vravinite Pickaxe");
		Registry.registerItem(infusedVraviniteAxe, "Infused Vravinite Axe");
		Registry.registerItem(infusedVraviniteShovel, "Infused Vravinite Shovel");
		Registry.registerItem(infusedVraviniteSword, "Infused Vravinite Sword");
		Registry.registerItem(dragonShield, "Dragon Shield");
		Registry.registerItem(auntunShield, "Aun'Tun Shield");
		Registry.registerItem(mythrilShield, "Mythril Shield");
		Registry.registerItem(galokinShield, "Galokin Shield");
		Registry.registerItem(woodenShield, "Wooden Shield");
		Registry.registerItem(stoneShield, "Stone Shield");
		Registry.registerItem(ironShield, "Iron Shield");
		Registry.registerItem(goldShield, "Gold Shield");
		Registry.registerItem(diamondShield, "Diamond Shield");
		Registry.registerItem(blindoniteShield, "Blindonite Shield");
		Registry.registerItem(shieldOfFlame, "Shield of Flame");
		Registry.registerItem(sapphireShield, "Sapphire Shield");
		Registry.registerItem(topazShield, "Mystic Topaz Shield");
		Registry.registerItem(vraviniteShield, "Vravinite Shield");
		Registry.registerItem(onyxShield, "Onyx Shield");
		Registry.registerItem(amethystShield, "Amethyst Shield");
		Registry.registerItem(alerisPickaxe, "Aleris Pickaxe");
		Registry.registerItem(alerisAxe, "Aleris Axe");
		Registry.registerItem(alerisShovel, "Aleris Shovel");
		Registry.registerItem(alerisSword, "Aleris Sword");
		Registry.registerItem(alerisHelmet, "Aleris Helmet");
		Registry.registerItem(alerisChestplate, "Aleris Chestplate");
		Registry.registerItem(alerisLeggings, "Aleris Leggings");
		Registry.registerItem(alerisBoots, "Aleris Boots");
		Registry.registerItem(aleris, "Aleris");
		Registry.registerItem(sanctuaryStonePickaxe, "Sanctuary Stone Pickaxe");
		Registry.registerItem(sanctuaryStoneAxe, "Sanctuary Stone Axe");
		Registry.registerItem(sanctuaryStoneShovel, "Sanctuary Stone Shovel");
		Registry.registerItem(sanctuaryStoneSword, "Sanctuary Stone Sword");
		Registry.registerItem(skywoodPickaxe, "Skywood Pickaxe");
		Registry.registerItem(skywoodAxe, "Skywood Axe");
		Registry.registerItem(skywoodShovel, "Skywood Shovel");
		Registry.registerItem(skywoodSword, "Skywood Sword");
		Registry.registerItem(skywoodSticks, "Skywood Sticks");
		Registry.registerItem(bloodPickaxe, "Blood Pickaxe");
		Registry.registerItem(bloodAxe, "Blood Axe");
		Registry.registerItem(bloodShovel, "Blood Shovel");
		Registry.registerItem(bloodSword, "Blood Sword");
		Registry.registerItem(bloodSticks, "Blood Sticks");
		Registry.registerItem(skywoodDoorItem, "Skywood Door");
		Registry.registerItem(bloodDoorItem, "Blood Door");
		Registry.registerItem(sanctuatiteActivator, "Sanctuatite Activator");
		Registry.registerItem(potionGlassSanctuatite, "Sanctuatite Potion");
		Registry.registerItem(bloodBucketWater, "Blood Water Bucket");
		Registry.registerItem(bloodBucket, "Blood Bucket");
		Registry.registerItem(bloodBucketLava, "Blood Lava Bucket");
		Registry.registerItem(glimmerwoodBucketWater, "Glimmerwood Water Bucket");
		Registry.registerItem(glimmerwoodBucket, "Glimmerwood Bucket");
		Registry.registerItem(glimmerwoodBucketLava, "Glimmerwood Lava Bucket");
		Registry.registerItem(cherryBlossomDoorItem, "Cherry Blossom Door");
		Registry.registerItem(cherryBlossomPickaxe, "Cherry Blossom Pickaxe");
		Registry.registerItem(cherryBlossomAxe, "Cherry Blossom Axe");
		Registry.registerItem(cherryBlossomShovel, "Cherry Blossom Shovel");
		Registry.registerItem(cherryBlossomSword, "Cherry Blossom Sword");
		Registry.registerItem(cherryBlossomSticks, "Cherry Blossom Sticks");
		Registry.registerItem(fireballWand, "Fireball Wand");
		Registry.registerItem(drakiuz, "Drakiuz");
		Registry.registerItem(flamonorActivator, "Flamonor Activator");
		Registry.registerItem(glimmerwoodDoorItem, "Glimmerwood Door");
		Registry.registerItem(vraviniteHelmet, "Vravinite Helmet");
		Registry.registerItem(vraviniteChestplate, "Vravinite Chestplate");
		Registry.registerItem(vraviniteLeggings, "Vravinite Leggings");
		Registry.registerItem(vraviniteBoots, "Vravinite Boots");
		Registry.registerItem(vravinitePickaxe, "Vravinite Pickaxe");
		Registry.registerItem(vraviniteAxe, "Vravinite Axe");
		Registry.registerItem(vraviniteShovel, "Vravinite Shovel");
		Registry.registerItem(vraviniteSword, "Vravinite Sword");
		Registry.registerItem(vravinite, "Vravinite");
		Registry.registerItem(vraviniteArrow, "Vravinite Arrow");
		Registry.registerItem(vraviniteBow, "Vravinite Bow");
		Registry.registerItem(blueMagicApple, "Magical Blue Apple");
		Registry.registerItem(glimmerwoodPickaxe, "Glimmerwood Pickaxe");
		Registry.registerItem(glimmerwoodAxe, "Glimmerwood Axe");
		Registry.registerItem(glimmerwoodShovel, "Glimmerwood Shovel");
		Registry.registerItem(glimmerwoodSword, "Glimmerwood Sword");
		Registry.registerItem(glimmerwoodSticks, "Glimmerwood Sticks");
		Registry.registerItem(vaerynActivator, "Vaeryn Activator");
		Registry.registerItem(infusedBlindoniteHelmet, "Infused Blindonite Helmet");
		Registry.registerItem(infusedBlindoniteChestplate, "Infused Blindonite Chestplate");
		Registry.registerItem(infusedBlindoniteLeggings, "Infused Blindonite Leggings");
		Registry.registerItem(infusedBlindoniteBoots, "Infused Blindonite Boots");
		Registry.registerItem(infusedBlindonitePickaxe, "Infused Blindonite Pickaxe");
		Registry.registerItem(infusedBlindoniteAxe, "Infused Blindonite Axe");
		Registry.registerItem(infusedBlindoniteShovel, "Infused Blindonite Shovel");
		Registry.registerItem(infusedBlindoniteSword, "Infused Blindonite Sword");
		Registry.registerItem(blindoniteHelmet, "Blindonite Helmet");
		Registry.registerItem(blindoniteChestplate, "Blindonite Chestplate");
		Registry.registerItem(blindoniteLeggings, "Blindonite Leggings");
		Registry.registerItem(blindoniteBoots, "Blindonite Boots");
		Registry.registerItem(blindonitePickaxe, "Blindonite Pickaxe");
		Registry.registerItem(blindoniteAxe, "Blindonite Axe");
		Registry.registerItem(blindoniteShovel, "Blindonite Shovel");
		Registry.registerItem(blindoniteSword, "Blindonite Sword");
		Registry.registerItem(tefCrystal, "Tef Crystal");
		Registry.registerItem(tefHelmet, "Tef's Legendary Helmet");
		Registry.registerItem(tefChestplate, "Tef's Legendary Chestplate");
		Registry.registerItem(tefLeggings, "Tef's Legendary Leggings");
		Registry.registerItem(tefBoots, "Tef's Legendary Boots");
		Registry.registerItem(blindOasisActivator, "Blind Oasis Activator");
		Registry.registerItem(blindonite, "Blindonite");
		Registry.registerItem(longbow, "Longbow");
		Registry.registerItem(enforcedBowOfWurTun, "Enforced Bow Of Wur-Tun");
		Registry.registerItem(helmetOfFlame, "Helmet of Flame");
		Registry.registerItem(chestplateOfFlame, "Chestplate of Flame");
		Registry.registerItem(leggingsOfFlame, "Leggings of Flame");
		Registry.registerItem(bootsOfFlame, "Boots of Flame");
		Registry.registerItem(ingotOfFlame, "Ingot of Flame");
		Registry.registerItem(purpleFeather, "Purple Feather");
		Registry.registerItem(clothOfMagic, "Cloth of Magic");
		Registry.registerItem(swordOfFlame, "Sword of Flame");
		Registry.registerItem(darkenedSapphireSword, "Darkened Sapphire Sword");
		Registry.registerItem(darkenedInfusedSapphireSword, "Darkened Infused Sapphire Sword");
		Registry.registerItem(darkenedTopazSword, "Darkened Mystic Topaz Sword");
		Registry.registerItem(darkenedInfusedTopazSword, "Darkened Infused Mystic Topaz Sword");
		Registry.registerItem(infusedTopazHelmet, "Infused Mystic Topaz Helmet");
		Registry.registerItem(infusedTopazChestplate, "Infused Mystic Topaz Chestplate");
		Registry.registerItem(infusedTopazLeggings, "Infused Mystic Topaz Leggings");
		Registry.registerItem(infusedTopazBoots, "Infused Mystic Topaz Boots");
		Registry.registerItem(infusedTopazPickaxe, "Infused Mystic Topaz Pickaxe");
		Registry.registerItem(infusedTopazAxe, "Infused Mystic Topaz Axe");
		Registry.registerItem(infusedTopazShovel, "Infused Mystic Topaz Shovel");
		Registry.registerItem(infusedTopazSword, "Infused Mystic Topaz Sword");
		Registry.registerItem(infusedSapphireHelmet, "Infused Sapphire Helmet");
		Registry.registerItem(infusedSapphireChestplate, "Infused Sapphire Chestplate");
		Registry.registerItem(infusedSapphireLeggings, "Infused Sapphire Leggings");
		Registry.registerItem(infusedSapphireBoots, "Infused Sapphire Boots");
		Registry.registerItem(infusedSapphirePickaxe, "Infused Sapphire Pickaxe");
		Registry.registerItem(infusedSapphireAxe, "Infused Sapphire Axe");
		Registry.registerItem(infusedSapphireShovel, "Infused Sapphire Shovel");
		Registry.registerItem(infusedSapphireSword, "Infused Sapphire Sword");
		Registry.registerItem(theDarknessCrystal, "Crystal of Darkness");
		Registry.registerItem(magickaHelmet, "Hood of Magic");
		Registry.registerItem(magickaChestplate, "Robe of Magic");
		Registry.registerItem(magickaLeggings, "Leggings of Magic");
		Registry.registerItem(magickaBoots, "Boots of Magic");
		Registry.registerItem(galokinCrystal, "Galokin Crystal");
		Registry.registerItem(galokinSword, "Galokin Sword");
		Registry.registerItem(galokinHelmet, "Galokin Helmet");
		Registry.registerItem(galokinChestplate, "Galokin Chestplate");
		Registry.registerItem(galokinLeggings, "Galokin Leggings");
		Registry.registerItem(galokinBoots, "Galokin Boots");
		Registry.registerItem(trainingSword, "Training Sword");
		Registry.registerItem(silverCoin, "Silver Coin");
		Registry.registerItem(goldCoin, "Gold Coin");
		Registry.registerItem(cherry, "Cherry");
		Registry.registerItem(manchet, "Manchet");
		Registry.registerItem(topazHelmet, "Mystic Topaz Helmet");
		Registry.registerItem(topazChestplate, "Mystic Topaz Chestplate");
		Registry.registerItem(topazLeggings, "Mystic Topaz Leggings");
		Registry.registerItem(topazBoots, "Mystic Topaz Boots");
		Registry.registerItem(topazPickaxe, "Mystic Topaz Pickaxe");
		Registry.registerItem(topazAxe, "Mystic Topaz Axe");
		Registry.registerItem(topazShovel, "Mystic Topaz Shovel");
		Registry.registerItem(topazSword, "Mystic Topaz Sword");
		Registry.registerItem(topaz, "Mystic Topaz");
		Registry.registerItem(opal, "Opal");
		Registry.registerItem(sapphireHelmet, "Sapphire Helmet");
		Registry.registerItem(sapphireChestplate, "Sapphire Chestplate");
		Registry.registerItem(sapphireLeggings, "Sapphire Leggings");
		Registry.registerItem(sapphireBoots, "Sapphire Boots");
		Registry.registerItem(sapphirePickaxe, "Sapphire Pickaxe");
		Registry.registerItem(sapphireAxe, "Sapphire Axe");
		Registry.registerItem(sapphireShovel, "Sapphire Shovel");
		Registry.registerItem(sapphireSword, "Sapphire Sword");
		Registry.registerItem(sapphire, "Sapphire");
		Registry.registerItem(pepper, "Pepper");
		Registry.registerItem(pepperSpices, "Pepper Spices");
		Registry.registerItem(spicedWine, "Spiced Wine");
		Registry.registerItem(greenApple, "Green Apple");
		Registry.registerItem(wine, "Wine");
		Registry.registerItem(grapes, "Grapes");
		Registry.registerItem(potionGlass, "Potion Glass");
		Registry.registerItem(wineGlass, "Wine Glass");
		Registry.registerItem(cookedHorseMeat, "Cooked Horse Meat");
		Registry.registerItem(horseMeat, "Horse Meat");
		Registry.registerItem(tomato, "Tomato");
		Registry.registerItem(shifter, "Shifter");
		Registry.registerItem(khuulisScythe, "Khuuli's Scythe");
		Registry.registerItem(blackDurii, "Black Durii");
		Registry.registerItem(auntunSummoner, "Aun'Tun Summoner");
		Registry.registerItem(vulron, "Vulron");
		Registry.registerItem(vulronSword, "Vulron Sword");
		Registry.registerItem(bowOfWurTun, "Bow of Wur-Tun");
		Registry.registerItem(darknessArrow, "Arrow of Darkness");
		Registry.registerItem(sharpenedSlateHandaxe, "Sharpened Slate Handaxe");
		Registry.registerItem(bladeOfAni, "Blade Of Ani");
		Registry.registerItem(slateHandaxe, "Slate Handaxe");
		Registry.registerItem(nizonianBlade, "Nizonian Blade");
		Registry.registerItem(daetoriSword, "Daetori's Sword");
		Registry.registerItem(sorrowSword, "Sorrow Sword");
		Registry.registerItem(axeOfAunTun, "Axe of Aun'Tun");
		Registry.registerItem(HalfFusedaxeOfAunTun, "Half Fused Axe of Aun'Tun");
		Registry.registerItem(UnfusedaxeOfAunTun, "Unfused Axe of Aun'Tun");
		Registry.registerItem(blackBone, "Black Bone");
		Registry.registerItem(amethyst, "Amethyst");
		Registry.registerItem(onyx, "Onyx");
		Registry.registerItem(slateFragment, "Slate Fragment");
		Registry.registerItem(orb, "Orb");
		Registry.registerItem(nironite, "Nironite");
		Registry.registerItem(agonite, "Agonite");
		Registry.registerItem(terronCrystal, "Terron Crystal");
		Registry.registerItem(baseCrystal, "Base Crystal");
		Registry.registerItem(garnet, "Garnet");
		Registry.registerItem(infusedAmethystShovel, "Infused Amethyst Shovel");
		Registry.registerItem(infusedAmethystPickaxe, "Infused Amethyst Pickaxe");
		Registry.registerItem(infusedAmethystAxe, "Infused Amethyst Axe");
		Registry.registerItem(infusedOnyxShovel, "Infused Onyx Shovel");
		Registry.registerItem(infusedOnyxPickaxe, "Infused Onyx Pickaxe");
		Registry.registerItem(infusedOnyxAxe, "Infused Onyx Axe");
		Registry.registerItem(auntunMinionHelmet, "Aun'Tun Minion Helmet");
		Registry.registerItem(auntunMinionChestplate, "Aun'Tun Minion Chestplate");
		Registry.registerItem(auntunMinionLeggings, "Aun'Tun Minion Leggings");
		Registry.registerItem(auntunMinionBoots, "Aun'Tun Minion Boots");
		Registry.registerItem(onyxHelmet, "Onyx Helmet");
		Registry.registerItem(onyxChestplate, "Onyx Chestplate");
		Registry.registerItem(onyxLeggings, "Onyx Leggings");
		Registry.registerItem(onyxBoots, "Onyx Boots");
		Registry.registerItem(amethystHelmet, "Amethyst Helmet");
		Registry.registerItem(amethystChestplate, "Amethyst Chestplate");
		Registry.registerItem(amethystLeggings, "Amethyst Leggings");
		Registry.registerItem(amethystBoots, "Amethyst Boots");
		Registry.registerItem(infusedOnyxHelmet, "Infused Onyx Helmet");
		Registry.registerItem(infusedOnyxChestplate, "Infused Onyx Chestplate");
		Registry.registerItem(infusedOnyxLeggings, "Infused Onyx Leggings");
		Registry.registerItem(infusedOnyxBoots, "Infused Onyx Boots");
		Registry.registerItem(infusedAmethystHelmet, "Infused Amethyst Helmet");
		Registry.registerItem(infusedAmethystChestplate, "Infused Amethyst Chestplate");
		Registry.registerItem(infusedAmethystLeggings, "Infused Amethyst Leggings");
		Registry.registerItem(infusedAmethystBoots, "Infused Amethyst Boots");
		Registry.registerItem(amethystPickaxe, "Amethyst Pickaxe");
		Registry.registerItem(amethystAxe, "Amethyst Axe");
		Registry.registerItem(amethystShovel, "Amethyst Shovel");
		Registry.registerItem(amethystSword, "Amethyst Sword");
		Registry.registerItem(infusedAmethystSword, "Infused Amethyst Sword");
		Registry.registerItem(darkenedAmethystSword, "Darkened Amethyst Sword");
		Registry.registerItem(darkenedInfusedAmethystSword, "Darkened Infused Amethyst Sword");
		Registry.registerItem(onyxSword, "Onyx Sword");
		Registry.registerItem(infusedOnyxSword, "Infused Onyx Sword");
		Registry.registerItem(darkenedOnyxSword, "Darkened Onyx Sword");
		Registry.registerItem(darkenedInfusedOnyxSword, "Darkened Infused Onyx Sword");
		Registry.registerItem(onyxPickaxe, "Onyx Pickaxe");
		Registry.registerItem(agonitePickaxe, "Agonite Pickaxe");
		Registry.registerItem(onyxAxe, "Onyx Axe");
		Registry.registerItem(onyxShovel, "Onyx Shovel");
		Registry.registerItem(garnetHelmet, "Garnet Helmet");
		Registry.registerItem(garnetChestplate, "Garnet Chestplate");
		Registry.registerItem(garnetLeggings, "Garnet Leggings");
		Registry.registerItem(garnetBoots, "Garnet Boots");
		Registry.registerItem(mythrilHelmet, "Mythril Helmet");
		Registry.registerItem(mythrilChestplate, "Mythril Chestplate");
		Registry.registerItem(mythrilLeggings, "Mythril Leggings");
		Registry.registerItem(mythrilBoots, "Mythril Boots");
		Registry.registerItem(darkMatter, "Dark Matter");
		Registry.registerItem(ambrosia, "Ambrosia");
		Registry.registerItem(mythrilIngot, "Mythril Ingot");
		Registry.registerItem(burnedQuartz, "Black Quartz");
		Registry.registerItem(dragonSword, Color.DARK_RED + "Dragon Sword");
		Registry.registerItem(dragonSoul, Color.DARK_RED + "Dragon Soul Gem");
		Registry.registerItem(demonAngelCrystal, Color.DARK_RED + "Demon Angel Crystal");
		Registry.registerItem(dragonHelmet, Color.DARK_RED + "Dragon Helmet");
		Registry.registerItem(dragonChestplate, Color.DARK_RED + "Dragon Chestplate");
		Registry.registerItem(dragonLeggings, Color.DARK_RED + "Dragon Leggings");
		Registry.registerItem(dragonBoots, Color.DARK_RED + "Dragon Boots");
		Registry.registerItem(dragonPickaxe, Color.DARK_RED + "Dragon Pickaxe");
		Registry.registerItem(dragonAxe, Color.DARK_RED + "Dragon Axe");
		Registry.registerItem(dragonShovel, Color.DARK_RED + "Dragon Shovel");
		Registry.registerItem(darkenedInfusedDragonSword, Color.DARK_RED + "Darkened Infused Dragon Sword");
		Registry.registerItem(darkenedDragonSword, Color.DARK_RED + "Darkened Dragon Sword");
		Registry.registerItem(infusedDragonHelmet, Color.DARK_RED + "Infused Dragon Helmet");
		Registry.registerItem(infusedDragonChestplate, Color.DARK_RED + "Infused Dragon Chestplate");
		Registry.registerItem(infusedDragonLeggings, Color.DARK_RED + "Infused Dragon Leggings");
		Registry.registerItem(infusedDragonBoots, Color.DARK_RED + "Infused Dragon Boots");
		Registry.registerItem(infusedDragonPickaxe, Color.DARK_RED + "Infused Dragon Pickaxe");
		Registry.registerItem(infusedDragonAxe, Color.DARK_RED + "Infused Dragon Axe");
		Registry.registerItem(infusedDragonShovel, Color.DARK_RED + "Infused Dragon Shovel");
		Registry.registerItem(infusedDragonSword, Color.DARK_RED + "Infused Dragon Sword");
	}

	public static void RioVPaladin()
	{
		if(TheMistsOfRioV.riovPaladin)
		{
			paladinHelmet = (new RioVArmor(8000, FlameArmorMaterial, render, 0, "paladin", false)).setUnlocalizedName("paladinHelmet");
			paladinChestplate = (new RioVArmor(8001, FlameArmorMaterial, render, 1, "paladin", false)).setUnlocalizedName("paladinChestplate");
			paladinLeggings = (new RioVArmor(8002, FlameArmorMaterial, render, 2, "paladin", false)).setUnlocalizedName("paladinLeggings");
			paladinBoots = (new RioVArmor(8003, FlameArmorMaterial, render, 3, "paladin", false)).setUnlocalizedName("paladinBoots");
			paladinLongsword = (new RioVWeapon(8004, InfusedOnyx, false)).setUnlocalizedName("paladinLongsword");

			Registry.registerItem(paladinHelmet, "Paladin Helmet");
			Registry.registerItem(paladinChestplate, "Paladin Chestplate");
			Registry.registerItem(paladinLeggings, "Paladin Leggings");
			Registry.registerItem(paladinBoots, "Paladin Boots");
			Registry.registerItem(paladinLongsword, "Paladin Longsword");
		}
	}

	public static void RioVTrees()
	{
		if(TheMistsOfRioV.riovTrees)
		{

		}
	}
}
